### PR TITLE
win: fix/redo the uv_rwlock implementation

### PR DESCRIPTION
**Pull request by piscisaureus**
The reader count would not be incremented when a thread successfully
acquired a read lock while another thread *also* held a read lock.

R=@bnoordhuis
R=@saghul

PS: anyone has an XP and 2k3 VM to run the tests with? I have, but the external hard disk that has it is on a different continent...

### CODE REVIEW

**Comment by saghul** [comment]
Doh. I think I have one, I'll see if I can run the tests.

**Comment by piscisaureus** [comment]
Actually there are no tests for this -- I'm writing one.

**Comment by piscisaureus** [comment]
See c410677. Note that this test currently doesn't pass even on newer versions of windows. This seems related to the fact that `TryAcquireSRWLockExclusive` succeeds when the calling thread already owns the write lock.

@bnoordhuis, @saghul - it would be great if you guys could review this test and make sure it at least passes on unix.

**Comment by saghul** [comment]
Hello! I traveled to the past and tested this patch with Windows XP and Visual Studio 2008.  Test doesn't pass:

~~~~
[%  97|+ 240|-  10|T   1|S  14]: thread_rwlock_trylock
`thread_rwlock_trylock` failed: exit code 3
Output from process `thread_rwlock_trylock`:
Assertion failed in .\test\test-mutexes.c on line 81: r == UV_EBUSY
~~~~

**Comment by saghul** [comment]
> See c410677. Note that this test currently doesn't pass even on newer versions of windows. This seems related to the fact that TryAcquireSRWLockExclusive succeeds when the calling thread already owns the write lock.

That's what [the last comment on MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/dd405523%28v=vs.85%29.aspx) seems to suggest. But it shouldn't matter since we don't the fallback on Windows > Vista, right?

**Comment by saghul** [comment]
@piscisaureus c410677 passes (there you check for EAGAIN or EBUSY), but 29af69d doesn't, since EAGAIN is returned.

On Unix we can get either, so maybe we should use the more relaxed variant.

The test passes on Unix and LGTM, FWIW.

**Comment by piscisaureus** [comment]
> That's what the last comment on MSDN seems to suggest. But it shouldn't matter since we don't the fallback on Windows > Vista, right?

`TryAcquireSRWLockExclusive` is the *modern* solution. We use it on Vista and later, which is why this behaviour is problematic. I was able to create a workaround for the double-write-lock scenario, but the same behavior happens when a thread that already has a read lock then tries to acquire the write lock, and that's not so easy to work around (because it would require keeping a list of all threads that own read locks).

> (there you check for EAGAIN or EBUSY), but 29af69d doesn't, since EAGAIN is returned.

I don't really understand when unix reports EBUSY and when it does EAGAIN. The linux man pages suggest that EAGAIN is never used, except when more than X (a lot) threads all try to acquire a read lock. @bnoordhuis - can you enlighten me?

**Comment by piscisaureus** [comment]
Generally speaking, my feeling is that the windows *non-fallback* rwlock implementation is just semantically incompatible with unix, and we should remove the modern path, and use the fallback implementation everywhere.

Or we could just delete the rwlock stuff outright. It seemed like a good idea at the time maybe, but in this day and age I think it has no place in libuv.

**Comment by bnoordhuis** [comment]
> I don't really understand when unix reports EBUSY and when it does EAGAIN.

I think that's something I missed when reviewing 22f004db.  POSIX allows pthreads implementations to return either status code but we should really just report a single one, probably just UV_EBUSY.

**Comment by saghul** [comment]
> TryAcquireSRWLockExclusive is the modern solution.

Ouch.

> Generally speaking, my feeling is that the windows non-fallback rwlock implementation is just semantically incompatible with unix, and we should remove the modern path, and use the fallback implementation everywhere.
> 

Fine by me!

> Or we could just delete the rwlock stuff outright. It seemed like a good idea at the time maybe, but in this day and age I think it has no place in libuv.

We cannot do that in v1.x...

**Comment by saghul** [comment]
> POSIX allows pthreads implementations to return either status code but we should really just report a single one, probably UV_EBUSY.

We could consolidate the error codes also on the Unix side then.

**Comment by piscisaureus** [comment]
I've updated the PR - the test and the windows bits are good to land I think, but please review @bnoordhuis and @saghul.

> We could consolidate the error codes also on the Unix side then.

I agree, but this PR doesn't address that.

**Comment by saghul** [comment]
@piscisaureus sorry for the delay! LGTM. I tested in on XP. Here is the CI for the newer ones, just in case: https://ci.nodejs.org/view/libuv/job/libuv+any-pr+multi/150/

I'll make the fix for Unixes.

**Comment by saghul** [comment]
Damn, the Windows bots are drunk tonight, I'll manually check on Windows 7.

**Comment by saghul** [comment]
My Windows 7 machine also says yes :-)

**Comment by saghul** [comment]
Here is the Unix patch for folding EAGAIN and EBUSY into EBUSY: https://github.com/libuv/libuv/pull/535

**Comment by piscisaureus** [comment]
Thanks for the review, @saghul - just landed this stuff.

**Comment by saghul** [comment]
Do we want to make a new point release since now this is properly fixed?

**Comment by saghul** [comment]
> Do we want to make a new point release since now this is properly fixed?

/cc @bnoordhuis @piscisaureus ^^

**Comment by bnoordhuis** [comment]
I'd say so.

**Comment by piscisaureus** [comment]
What @bnoordhuis said.

**Comment by saghul** [comment]
Okidoki, will do!

**Comment by jack-pappas** [comment]
@piscisaureus Lockless Inc., implemented a BSD-licensed pthreads layer (header-only) for Windows a few years ago; they also wrote a very detailed article documenting *how* they implemented the pthreads APIs to be semantically correct in the face of impedance mismatches with the Windows APIs (e.g., ``TryAcquireSRWLockExclusive``): [Pthreads on Microsoft Windows](http://locklessinc.com/articles/pthreads_on_windows/)

Given the newer Windows APIs like reader-writer locks and condition variables offer better performance than the older, more-heavyweight APIs like ``mutex``, it may be worth seeing if the code reverted by this PR can be fixed by adapting some of the techniques from that article (or, if the libuv license allows for it, just using their header).

**Comment by saghul** [comment]
@jack-pappas Thanks for the link! It's BSD licensed, but check this out:

~~~~
A full implementation of this library is on the downloads page. It is licensed under the BSD license. However, be aware that it does use undocumented windows internals for a few of the synchronization primitives. These may be changed by Microsoft in the future, so probably should not be relied on for anything important.
~~~~

I'm not sure we want to rely on obscure undocumented stuff. Also, we'd need some benchmarks proving that the alternative is actually faster/better :-)

**Pull request merged**
