### PR TITLE
unix: set non-block mode in uv_{pipe,tcp,udp}_open

### PR DESCRIPTION
**Pull request by bnoordhuis**
R=@saghul

I didn't have time to write a test.  Feel free to steal this PR and put your own changes in.

### CODE REVIEW

**Comment by saghul** [comment]
Thanks, Ben! I'll add some versionchanged thing to the docs and update some tests a bit later then.

**Comment by saghul** [comment]
@bnoordhuis can you PTAL at this? https://github.com/saghul/libuv/compare/libuv:v1.x...do_you_even_open Pay special attention to the change to test-spawn.c, we used to set the fd to non-blocking *before* spawning a child process, it would now be *after*.

Also, I wonder if we should do the same for poll handles, WDYT? Windows doesn't do it either. /cc @piscisaureus

**Comment by piscisaureus** [comment]
@saghul 

For windows:
* Doesn't matter for poll handles
* For imported tcp handles it gets done: https://github.com/libuv/libuv/blob/550147fd67f03aba27545b80d4b62d3fd3a6ed39/src/win/tcp.c#L90

**Comment by saghul** [comment]
Why doesn't it matter for poll handles? I see we do put the fd as
nonblocking in the tests.

**Comment by saghul** [comment]
I added another patch for poll handles. PTAL: https://github.com/saghul/libuv/compare/libuv:v1.x...do_you_even_open

**Comment by piscisaureus** [comment]
> Why doesn't it matter for poll handles? I see we do put the fd as nonblocking in the tests.

The problem with uv_pipe_open() arises because libuv itself tries to do a nonblocking operation, but the fd is not in nonblocking mode. With uv_poll() we don't actually do any nonblocking stuff, we just do epoll-like things for the user.

The test must set SOCK_NONLBLOCK because it does nonblocking sends and receives.

**Comment by saghul** [comment]
> The problem with uv_pipe_open() arises because libuv itself tries to do a nonblocking operation, but the fd is not in nonblocking mode. With uv_poll() we don't actually do any nonblocking stuff, we just do epoll-like things for the user.
> 
> The test must set SOCK_NONLBLOCK because it does nonblocking sends and receives.

I'm a bit confused :-/ AFAIK, all uv_{pipe, tcp, udp}_open work correctly on Windows. Apparently there are tricks on uv_pipe_open but It Just Works (TM), right?

Now, on poll handles the user needs to set the fd to non-blocking mode manually, which is what one of the patches here solves, for consistency with the other functions where the user doesn't need to do it.

Is there anything I'm missing? Thanks!

**Comment by piscisaureus** [comment]
Had some discussion with Saùl on IRC.
This PR lgtm.

**Comment by saghul** [comment]
As discussed with @piscisaureus on IRC, the PR landed, I'll take the poll handles thing to another PR.

**Pull request closed without merging**
