### PR TITLE
build: turn on -fno-strict-aliasing

### PR DESCRIPTION
**Pull request by bnoordhuis**
Turn on `-fno-strict-aliasing` and, in the case of the gyp build, export
it to projects that depend on libuv.

Fixes: #1230
CI: https://ci.nodejs.org/job/libuv-test-commit/1668/

### CODE REVIEW

**Comment by vcunat** [comment]
Well, note that it doesn't solve the whole problem, as some fields of the aliasing types are meant to be used directly.

**Comment by vtjnash** [comment]
@bnoordhuis rebase and merge this?

**Comment by vtjnash** [comment]
bump?

**Comment by vtjnash** [comment]
Hopefully I got the cmake part correct in the rebase.

CI: https://ci.nodejs.org/job/libuv-test-commit/2083/

**Pull request merged**
