### PR TITLE
configure: add -Wstrict-prototypes

### LINKED ISSUE #1320: add -Wstrict-prototypes flag
I noticed that many of the functions declarations in src/win/internal.h are using old K&R-style function definitions, rather than ANSI C declarations. The `-Wstrict-prototypes` flag would enable warning when the code accidentally declares a function as unprototyped (`void uv__func();`) instead of as taking zero arguments (`void uv__func(void)`). In practice, this doesn't usually matter (the calling-convention for zero arguments is the same either way), although it does somewhat reduce the type-safety one would usually get from declaring the function in a header.

https://stackoverflow.com/questions/693788/is-it-better-to-use-c-void-arguments-void-foovoid-or-not-void-foo

### PR DESCRIPTION
**Pull request by vtjnash**
fix #1320

### CODE REVIEW

**Comment by cjihrig** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/251/

**Comment by santigimeno** [comment]
There's this failure in one of the windows bots that looks unrelated but don't remember seeing it before
```
not ok 242 - fs_utime
# exit code 3
# Output from process `fs_utime`: (no output)
```

**Comment by cjihrig** [comment]
New CI to see what happens with `fs_utime`: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/257/

**Comment by santigimeno** [comment]
Landed in: https://github.com/libuv/libuv/commit/fd39cec4b848b27be6bf3f8a3e0bce29474366bb. Thanks!

**Comment by santigimeno** [comment]
CI was green BTW

**Pull request closed without merging**
