### PR TITLE
Merge v1.x into master

### PR DESCRIPTION
**Pull request by saghul**
HAd to manually solve a bunch of conflicts, let's see what the CI says.

### CODE REVIEW

**Comment by saghul** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/323/

**Comment by saghul** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/324/

**Comment by saghul** [comment]
Here we go again: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/325/

Note: some Windows bots will fail because we dropped support for older Windows and VS versions.

**Comment by saghul** [comment]
More fixes...

CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/326/

**Comment by saghul** [comment]
We are green (on Unix) can any @libuv/collaborators PTAL? Also, something seems wrong with the Windows bots... who can we ping about that?

**Comment by cjihrig** [comment]
> Also, something seems wrong with the Windows bots... who can we ping about that?

@joaocgreis or @jbergstroem maybe?

**Comment by saghul** [comment]
Thanks, Colin!

**Comment by jBarz** [comment]
Looks good on z/OS :-)

**Comment by joaocgreis** [comment]
Windows failure is because the label `vs-set-2015` is missing in `vcbuild.bat`, was probably an oversight in the merge. I did not test, but this should fix it:

```diff
--- a/vcbuild.bat
+++ b/vcbuild.bat
@@ -64,6 +64,7 @@ goto select-target


 @rem Look for Visual Studio 2015
+:vs-set-2015
 if not defined VS140COMNTOOLS goto vc-set-notfound
 if not exist "%VS140COMNTOOLS%\..\..\vc\vcvarsall.bat" goto vc-set-notfound
 call "%VS140COMNTOOLS%\..\..\vc\vcvarsall.bat" %vs_toolset%
```

**Comment by saghul** [comment]
Thanks @joaocgreis!! Good catch, I'll update and rerun the CI later today.

**Comment by saghul** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/331/

**Comment by saghul** [comment]
Damn, I hope this is the last one: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/332/

**Comment by saghul** [comment]
Sigh, 2 tests are failing due to the API changes in fs. I'll push fixes and silently run the CI in order to avoid more noise here...

**Comment by saghul** [comment]
Finally! Windows went Hulk 💚  https://ci.nodejs.org/view/libuv/job/libuv-test-commit/335/

@libuv/collaborators can you PTAL again? The commits to be looked at are the ones after "Merge branch 'v1.x' into merge-v1". Thanks!

**Comment by bzoz** [comment]
LGTM, great work!

**Comment by saghul** [comment]
Thanks for the reviews, landed everything!

**Pull request merged**
