### PR TITLE
Merge 1.44.2 to master

### PR DESCRIPTION
**Pull request by vtjnash**
Same as usual. Last PR of this sort was for v1.44.1 (https://github.com/libuv/libuv/pull/3518)

### CODE REVIEW

**Comment by vtjnash** [comment]
Seems like the CI machine got overloaded, since we see failures such as this one:
```
2: not ok 230 - semaphore_1
2: # exit code 3
2: # Output from process `semaphore_1`:
2: # Assertion failed in D:\a\libuv\libuv\test\test-semaphore.c on line 62: wc.posted == 1
```
which is checking whether a particular event happens within 100ms.

**Comment by vtjnash** [comment]
Anyone willing to rubberstamp (or review) this? As usual, there is an automated merge commit, then a second commit where I fix all of the conflicts (not too many, nothing particularly complicated), and then I will squash everything into the merge commit eventually and push it.

**Review by bnoordhuis — APPROVED** [review]
RSLGTM for the most part. I looked in more detail at the fixups. They look okay to me.

**Comment by vtjnash** [comment]
I made a small functional mistake and forgot to prevent https://github.com/JuliaLang/libuv/commit/a6ba1d709eea338df4a6ba125a01efa20de34ad7 from ending up on master. I will plan to revert that next time.

**Pull request merged**
