### PR TITLE
test: make tap output the default

### PR DESCRIPTION
**Pull request by bnoordhuis**
CI: https://ci.nodejs.org/job/libuv-test-commit/60/

### CODE REVIEW

**Comment by jbergstroem** [comment]
Should we create another job to test tap output (parse in jenkins)?

**Comment by bnoordhuis** [comment]
If there is a way to - quickly - get the aggregated output from all buildbots, that would be great.

**Comment by jbergstroem** [comment]
I don't know. Can play around but yeah, jenkins.

**Comment by saghul** [comment]
LGTM

**Pull request merged**
