### PR TITLE
Revert "unix,tcp: avoid marking server sockets connected"

### PR DESCRIPTION
**Pull request by bnoordhuis**
Reverted for breaking Node.js in rather spectacular fashion.

The bug is arguably on the Node.js side.  It looks like Node.js starts
reading before the socket is actually connected to something.
Until that is fixed downstream, let's revert the change.

This reverts commit fd049399aa4ed8495928e375466970d98cb42e17.

Fixes: https://github.com/libuv/libuv/issues/1716
Fixes: https://github.com/nodejs/node/issues/18225

### CODE REVIEW

**Comment by gireeshpunathil** [comment]
LGTM

**Comment by bnoordhuis** [comment]
Needs some more investigation, I still get a couple of failures on macos.

**Comment by bnoordhuis** [comment]
Okay, found it - looks like we didn't have one but two PRs that introduced regressions.  Reverting them in isolation doesn't fix the node.js failures but reverting them both does.

https://ci.nodejs.org/job/libuv-test-commit/674/
https://ci.nodejs.org/job/node-test-commit/15499/ (node + libuv integration)

**Comment by santigimeno** [comment]
What problems was causing the "partial reads/writes" commit?

**Comment by bnoordhuis** [comment]
@santigimeno Here's an example:
```
$ python tools/test.py parallel/test-vm-syntax-error-message
=== release test-vm-syntax-error-message ===
Path: parallel/test-vm-syntax-error-message
events.js:116
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at _errnoException (util.js:1069:13)
    at Socket._read (net.js:527:20)
    at Socket.Readable.read (_stream_readable.js:450:10)
    at Socket.read (net.js:400:43)
    at new Socket (net.js:277:12)
    at createSocket (internal/child_process.js:241:11)
    at ChildProcess.spawn (internal/child_process.js:357:23)
    at Object.exports.spawn (child_process.js:532:9)
    at Object.<anonymous> (/Users/bnoordhuis/src/v1.x/test/parallel/test-vm-syntax-error-message.js:6:25)
    at Module._compile (module.js:660:30)
```

**Comment by santigimeno** [comment]
Hmm that looks a lot like a failure from the [other commit](https://github.com/libuv/libuv/commit/fd049399aa4ed8495928e375466970d98cb42e17), not the _partial reads/writes_ one

**Comment by santigimeno** [comment]
> I agree, but node's tests don't pass when only one of the commits is reverted.

Got it. Is it happening on every platform or specific? Just saying because of [this comment](https://github.com/libuv/libuv/pull/1655#issuecomment-358377993) from Colin:

> I reverted this commit and Node's test suite passed for me locally.

**Comment by bnoordhuis** [comment]
I tested on linux and macos.  Reverting fd049399 is enough to fix the failures on linux but not on macos.

**Comment by cjihrig** [comment]
Kind of funny because I only reverted fd049399aa4ed8495928e375466970d98cb42e17 and got a clean `make test` on macos. I certainly don't doubt any failures you encountered though. Maybe something version specific or just flakey.

**Comment by bnoordhuis** [comment]
I did another run without the second revert and now it passes for me too... Not sure what's up with that but I guess I'll drop that commit.

**Comment by bnoordhuis** [comment]
https://ci.nodejs.org/job/libuv-test-commit/676/
https://ci.nodejs.org/job/node-test-commit/15511/

**Comment by bnoordhuis** [comment]
I've added back the revert, see #1720.

**Comment by bnoordhuis** [comment]
Landed in 1366e741...9f07a367.

**Comment by cjihrig** [comment]
@bnoordhuis thoughts on releasing 1.19.1 now?

**Comment by bnoordhuis** [comment]
Good idea.

**Pull request closed without merging**
