### PR TITLE
[pipe] use cached name for unix sockets

### PR DESCRIPTION
**Pull request by ovalenti**
## Description
 
In order to unlink unix sockets, we already need to keep a copy of the path in their handle struct. When getting the name of a pipe, we currently default to calling getsockname() on the underlying socket, which is notoriously broken on some systems, notably FreeBSD and GNU/Hurd.

This change proposes to make use of the cached path whenever available.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
getsockname() being broken on freebsd is news to me. What exactly is the issue you ran into there?

**Comment by ovalenti** [comment]
@bnoordhuis, I based my comment on the BUGS section of the getsockname() man-page. https://man.freebsd.org/cgi/man.cgi?query=getsockname#end

In general, there seem to be a fundamental problem with getsockname() on AF_UNIX sockets, because different callers can live in different file-system contexts. https://lists.gnu.org/archive/html/bug-hurd/2005-03/msg00216.html

**Comment by bnoordhuis** [comment]
>  Names  bound  to	 sockets  in  the  UNIX	  domain   are	 inaccessible; getsockname() returns a zero length name.

Maybe that man page is outdated? We have tests to that effect and they pass on freebsd.

I don't really want to make this change just for hurd because of the possibility of regressions / user-visible changes in behavior on other platforms.

**Comment by ovalenti** [comment]
> I don't really want to make this change just for hurd because of the possibility of regressions / user-visible changes in behavior on other platforms.

This is understandable, I will figure out a better solution ! :)

**Comment by ovalenti** [comment]
> Maybe that man page is outdated?

It would seem so : https://cgit.freebsd.org/src/tree/sys/kern/uipc_usrreq.c#n1735

**Pull request closed without merging**
