### PR TITLE
win,fs: fix flag validation

### PR DESCRIPTION
**Pull request by RaisinTen**
Signed-off-by: Darshan Sen <raisinten@gmail.com>

### CODE REVIEW

**Comment by RaisinTen** [comment]
@vtjnash I think the `EPERM` was being thrown from:

https://github.com/libuv/libuv/blob/99eb736b4c81c8a00aa52ebd75de7198fbbcddbe/src/win/fs.c#L1114

So, I've moved the validation from the `*_filemap()` functions to the `fs__write()` and `fs__read()` functions to exit early in case of any flag related error.

**Review by vtjnash — APPROVED** [review]
SGTM: https://ci.nodejs.org/job/libuv-test-commit-windows-cmake/361/

**Comment by vtjnash** [comment]
hm, this seems much worse??

**Comment by RaisinTen** [comment]
@vtjnash Since other functions are failing now, I've left `fs__*_filemap()` intact because the check is needed for other functions too. Hope this change works now. :crossed_fingers:

**Comment by RaisinTen** [comment]
A Windows CI on GitHub Actions would be really helpful. Could we add a workflow that uses https://github.com/ilammy/msvc-dev-cmd?

**Comment by vtjnash** [comment]
I agree that would be helpful, if you would like to set something up.

CI: https://ci.nodejs.org/job/libuv-test-commit-windows-cmake/363/

**Comment by RaisinTen** [comment]
@vtjnash PR to revert the change: https://github.com/libuv/libuv/pull/3211
I think I can work on this after a GH Action for Windows lands. I'll try to make a PR for that when I can.

**Comment by RaisinTen** [comment]
> I agree that would be helpful, if you would like to set something up.

Published the PR: https://github.com/libuv/libuv/pull/3212 :partying_face:

**Comment by vtjnash** [comment]
Looking closer, I don't think this is going anywhere, as I think this field is unassigned in the req object? We would perhaps need to translate EPERM -> EBADF after ReadFile / WriteFile failure to handle this case to match posix?

**Pull request closed without merging**
