### PR TITLE
unix: keep the TCP keep-alive settings on Solaris in sync with other OS's

### PR DESCRIPTION
**Pull request by panjf2000**

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Can you go into more detail? a9381cdb03f756cc42307584aeec084fd31fee3d wasn't fully correct then?

**Comment by panjf2000** [comment]
> Can you go into more detail? [a9381cd](https://github.com/libuv/libuv/commit/a9381cdb03f756cc42307584aeec084fd31fee3d) wasn't fully correct then?

#4272 is functionally correct. But it didn't make the TCP keep-alive timeout on Solaris consistent with other OS. You see, the TCP keep-alive timeout on other OS's is `idle+1s*10` while the timeout on Solaris is `idle+idle`. This PR is created to keep them in sync.

**Comment by panjf2000** [comment]
Kindly ping @bnoordhuis

**Comment by panjf2000** [comment]
Ping @bnoordhuis

**Review by bnoordhuis — APPROVED** [review]
LGTM and sorry for the delay, lots on my plate at the moment.

**Comment by bnoordhuis** [comment]
I reworded the commit log to make it fit in 50 columns. Our commit logs are something of a creative writing master class sometimes.

**Pull request merged**
