### PR TITLE
test: skip signal_multiple_loops test on QEMU

### PR DESCRIPTION
**Pull request by gengjiawen**
Fix https://github.com/libuv/libuv/issues/2859

### CODE REVIEW

**Comment by richardlau** [comment]
Could you reword the commit? libuv doesn't have the same concept of flaky tests as Node.js does and this PR is skipping the test in question on QEMU.

**Comment by gengjiawen** [comment]
> Could you reword the commit? libuv doesn't have the same concept of flaky tests as Node.js does and this PR is skipping the test in question on QEMU.

Updated, PTAL.

**Comment by gengjiawen** [comment]
> LGTM but can I ask you to update the comment and include the error message (and explain why that is _probably_ a qemu issue rather than a libuv issue)?

Updated, PTAL.

**Comment by gengjiawen** [comment]
Can one of you merge this ? Thanks.

**Comment by cjihrig** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1921/ ✔️

**Comment by cjihrig** [comment]
Landed in https://github.com/libuv/libuv/commit/91a38b18c61643f31f2ec1d98baa15ed009641a7. Thanks!

**Pull request closed without merging**
