### PR TITLE
thread: support for affinity and detach

### PR DESCRIPTION
**Pull request by kpamnany**
Adds 3 calls:
```
int uv_thread_setaffinity(uv_thread_t *tid,
                          char *cpumask,
                          char *oldmask,
                          size_t mask_size);
```
Sets the specified thread's affinity to ``cpumask``, which must be specified in bytes. Returns the previous affinity setting in ``oldmask``, if provided. On Unix, uses ``pthread_getaffinity_np()`` to get the affinity setting and maps the ``cpu_set_t`` to bytes in ``oldmask``. Then maps the bytes in ``cpumask`` to a ``cpu_set_t`` and uses ``pthread_setaffinity_np()``. On Windows, maps the bytes in ``cpumask`` to a bitmask and uses ``SetThreadAffinityMask()`` which returns the previous affinity setting.
```
int uv_thread_getaffinity(uv_thread_t *tid,
                          char *cpumask,
                          size_t mask_size);
```
Gets the specified thread's affinity setting. On Unix, maps the ``cpu_set_t`` returned by ``pthread_getaffinity_np()`` to bytes in ``cpumask``. Unsupported on Windows, which doesn't have any way to get the current affinity setting.
```
int uv_thread_detach(uv_thread_t *tid);
```
Detaches the specified thread so it will be cleaned up on exit automatically; joining it is no longer necessary or possible. Uses ``pthread_detach()`` on Unix and ``CloseHandle()`` on Windows.

### CODE REVIEW

**Comment by kpamnany** [comment]
This is a follow-up to PR https://github.com/libuv/libuv/pull/273. The discussion there sets context.

The uv_thread_getaffinity() call offers an interesting dilemma which I'm sure you guys see all the time--go with the lowest common denominator, or with some calls unsupported on some platforms?

**Comment by petkaantonov** [comment]
On Windows you should probably get the [process affinity](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683213(v=vs.85).aspx) to see what cores are possible to use. For getting affinity in windows, you should be able to use `SetThreadAffinityMask` twice - first with some bogus but valid mask (so it doesn't error out) to get the old mask, and second call to restore the old mask and then return the old mask.

+1 for this feature in general, it will be useful to io.js workers feature.

**Comment by kpamnany** [comment]
Added get affinity support for Windows per @petkaantonov's input as well as validation against the process affinity mask.

As before, I only have ready access to a Linux development environment, so assistance with compiling and testing on other platforms would be very welcome.

**Comment by kpamnany** [comment]
I'm told this looks fine on Win32 and Win64.

**Comment by hayd** [comment]
cc @bnoordhuis @saghul

**Comment by amurzeau** [comment]
Note that, if I'm not mistaken, `pthread_setaffinity_np` function is a non standard GNU extension (http://man7.org/linux/man-pages/man3/pthread_setaffinity_np.3.html) and is not available on every Unices (AIX does not have it, maybe OSX too)
See also: [for AIX](http://www.ibm.com/developerworks/aix/library/au-processinfinity.html#list1), [for OSX](http://yyshen.github.io/2015/01/18/binding_threads_to_cores_osx.html)

**Comment by kpamnany** [comment]
git clumsiness, sorry. Still not sure what I did wrong when I rebased. Will open a new PR.

**Pull request closed without merging**
