### PR TITLE
unix,win: fix threadpool race condition

### PR DESCRIPTION
**Pull request by addaleax**
90891b4232e91dbd7a2e2077e4d23d16a374b41d introduced a race
condition when accessing `slow_io_work_running` – it is being
increased and later decreased as part of the worker thread loop,
but was accessed with different mutexes during these operations.

This fixes the race condition by making sure both accesses
are protected through the global `mutex` of `threadpool.c`.

This fixes a number of flaky Node.js tests.

Refs: https://github.com/libuv/libuv/pull/1845
Refs: https://github.com/nodejs/reliability/issues/18
Refs: https://github.com/nodejs/node/issues/23089
Refs: https://github.com/nodejs/node/issues/23067
Refs: https://github.com/nodejs/node/issues/23066
Refs: https://github.com/nodejs/node/issues/23219

### CODE REVIEW

**Comment by gireeshpunathil** [comment]
https://github.com/libuv/libuv/blob/28139bfb08411c5726444bc8edce4d6cb460ca2c/src/threadpool.c#L115

should we signal only if `slow_work_thread_threshold()` is met? else the idle workers get notified and go to dormancy for no reasons?

**Comment by addaleax** [comment]
> should we signal only if `slow_work_thread_threshold()` is met? else the idle workers get notified and go to dormancy for no reasons?

I think you’re right, but I kind of don’t want to mix that improvement with a fix for a bug which has been haunting us for weeks :smile: Would you mind opening a separate PR?

**Comment by gireeshpunathil** [comment]
@addaleax  - I am trying to reason out the problem, and the fix; please help me.

with `90891b4`, the mutex was partially open for operations involving `slow_io` variable, and other threads were able to access those before one tread completes its work

implication to that is the `slow_io` workload is more carried out more than expected but seen as lesser than its defined threshold.

this PR fixes that by adjusting the `slow_io` work count through exclusive mutex so only one source of truth is visible.

But then it just takes us to the same point as the behavior prior to `90891b4` ? how the tests weer failing? I am unable to understand that. will you please clarify?

**Comment by addaleax** [comment]
@gireeshpunathil I’m not sure whether you’ve seen it, but is https://github.com/nodejs/node/pull/23099#issuecomment-427254595 the answer to your question?

**Comment by gireeshpunathil** [comment]
yes, I just saw it, thanks.

**Comment by santigimeno** [comment]
@addaleax would it be possible adding a test that reproduces the issue you described (sending lots of fast DNS requests) ?

**Comment by addaleax** [comment]
@santigimeno I’m not sure – this seems to be platform-dependent in some way. In theory, just raising the `CONCURRENT_COUNT` in `test-getaddrinfo.c` should work, but it always passes for me regardless of how high I set it (as do the flaky Node.js tests).

**Comment by Trott** [comment]
Code and Learn is in less than a week and it would be really great to have Node.js CI green for it. I imagine a libuv release between now and then would be asking a lot, but maybe if this lands here, we can float it as a patch on our master branch?

**Comment by gireeshpunathil** [comment]
I was attempting for a stable recreate for the problem that PR addresses, but could not: my (JS) test case involved a unique domain name generator, a tight loop in which those are looked up, and the whole thing is repeated at intervals, with the interval frequency lying on the boundary of the  speed of the resolution; expectation is being some looks up being piled up and eventual hang. Pileup happens, but it looks like the system recovers from it. I tried with a 2 CPU MAC and a 120 CPU Linux; but the pattern is same.  So may be that `slow_io_work_running` though mis-computed, when work ceases, it comes back to normal? End result is that the tests just run slow; with issue indistinguishable from non-issue. It is just my theory.

**Comment by addaleax** [comment]
@gireeshpunathil I think the issue is more of a platform-dependent one in some way, so trying to reproduce on WIndows might be a better idea? (I couldn’t do so on Linux either.)

> So may be that `slow_io_work_running` though mis-computed, when work ceases, it comes back to normal?

I don’t see how it could “magically” recover by itself…

**Comment by gireeshpunathil** [comment]
I mean  - irrespective of the degree of race condition and data corruption, when one or more engaged workers return, those decrement the slow io work count, and there by allow some work to progress, though not optimally, but eventually completes all the pending work? Isn't it a possibility?

**Comment by addaleax** [comment]
@cjihrig I guess we want 48 hours before Code + Learn for the libuv upgrade PR, which would mean a release before Wednesday… would that be okay with you?

**Comment by cjihrig** [comment]
I'll make the release tomorrow (assuming this lands). There are actually a number of other Node bug fixes queued up for release. Proposal: https://github.com/libuv/libuv/issues/2024

**Comment by addaleax** [comment]
@cjihrig Thanks!

Went ahead and landed this in daf04e83cb4551f0dcb7d62c17e0c8bfd5379d56. If somebody has strong feelings about the test I’ve mentioned above, feel free to let me know and I’ll gladly open a PR.

**Pull request closed without merging**
