### PR TITLE
Fix windows compile

### PR DESCRIPTION
**Pull request by mmicko**
Tested on mingw 32bit and 64bit and on Visual Studio 2013

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Can you explain in the commit log why this fixes the build?  Bonus points if you include the actual build error.

PS: Please see CONTRIBUTING.md for the preferred format of the commit log.

**Comment by mmicko** [comment]
Here is error log, actually this is warning, thing is we try to keep compile in our project warning free so treat all warnings are errors  (sorry was not aware of preferred format): 

src/win/util.c: In function 'uv_os_homedir':
src/win/util.c:1189:46: warning: passing argument 3 of 'GetUserProfileDirectoryW' from incompatible pointer type
   if (!GetUserProfileDirectoryW(token, path, &bufsize)) {
                                              ^
In file included from src/win/util.c:39:0:
C:/buildtools/vendor/mingw64/x86_64-w64-mingw32/include/userenv.h:52:29: note: expected 'LPDWORD' but argument is of type 'size_t *'
   USERENVAPI WINBOOL WINAPI GetUserProfileDirectoryW(HANDLE hToken,LPWSTR lpProfileDir,LPDWORD lpcchSize);
                             ^

**Comment by saghul** [comment]
Oh. LGTM

**Comment by saghul** [comment]
Landed in 7552305, thanks!

**Pull request closed without merging**
