### PR TITLE
build,osx: fix warnings on tests compilation with gyp

### PR DESCRIPTION
**Pull request by santigimeno**
Add `-Wno-long-long` to `WARNING_CFLAGS`.

### CODE REVIEW

**Comment by saghul** [comment]
LGTM

**Comment by santigimeno** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/133/

**Comment by santigimeno** [comment]
In https://ci.nodejs.org/job/libuv-test-commit-osx/nodes=osx1010/129/ there are no warnings, whereas in https://ci.nodejs.org/job/libuv-test-commit-osx/nodes=osx1010/128/ there are.

**Comment by santigimeno** [comment]
Landed as https://github.com/libuv/libuv/commit/1a96fe33343f82721ba8bc93adb5a67ddcf70ec4

**Pull request closed without merging**
