### PR TITLE
aix,ibmi: Fix compilation errors in fs_copyfile

### LINKED ISSUE #4403: Build currently failing on AIX and OS/400 (IBM i)
```sh
src/unix/fs.c: In function 'uv__fs_copyfile':
src/unix/fs.c:1321:14: error: incompatible types when assigning to type 'struct timespec' from type 'st_timespec_t' {aka 'struct st_timespec'}
 1321 |   times[0] = src_statsbuf.st_atim;
      |              ^~~~~~~~~~~~
src/unix/fs.c:1322:14: error: incompatible types when assigning to type 'struct timespec' from type 'st_timespec_t' {aka 'struct st_timespec'}
 1322 |   times[1] = src_statsbuf.st_mtim;
      |              ^~~~~~~~~~~~
  CC       src/unix/libuv_la-poll.lo
gmake[1]: *** [Makefile:2730: src/unix/libuv_la-fs.lo] Error 1
gmake[1]: *** Waiting for unfinished jobs....
```

### PR DESCRIPTION
**Pull request by johnsonjh**
Fix compilation on IBM AIX and OS/400 (PASE for IBM i).

Closes #4403

### CODE REVIEW

**Comment by saghul** [comment]
Can we use uv_timespec_t here instead?

**Comment by richardlau** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/2287/

The IBM i CI is now passing: https://ci.nodejs.org/job/libuv-test-commit-ibmi/1378/

AIX has failed in `fs_copyfile`:
https://ci.nodejs.org/job/libuv-test-commit-aix/2290/nodes=aix72-ppc64/console 
```console
not ok 50 - fs_copyfile
# exit code 393222
# Output from process `fs_copyfile`:
# Assertion failed in test/test-fs-copyfile.c on line 145: `r == 0` (-22 == 0)
```

**Comment by juanarbol** [comment]
In the AIX build log I see the next warning:

```
src/unix/fs.c: In function 'uv__fs_copyfile':
src/unix/fs.c:1329:23: warning: passing argument 2 of 'futimens' from incompatible pointer type [-Wincompatible-pointer-types]
 1329 |   if (futimens(dstfd, times) == -1) {
      |                       ^~~~~
      |                       |
      |                       st_timespec_t * {aka struct st_timespec *}
In file included from ./include/uv/unix.h:26,
                 from ./include/uv.h:71,
                 from src/unix/fs.c:29:
/usr/include/sys/stat.h:445:27: note: expected 'const struct timespec *' but argument is of type 'st_timespec_t *' {aka 'struct st_timespec *'}
  445 |  extern int futimens(int, const struct timespec *);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~
```

Maybe I needs a more specific condition for `AIX`? and use `const struct timespec *`

**Comment by johnsonjh** [comment]
Sorry, I'll take a look again later today.

I made sure it compiled on both AIX and i, but I only ran the full tests under i (which passed), which apparently wasn't sufficient.

**Comment by juanarbol** [comment]
I saw this conditionals which seems to be related to this compile issue:

https://github.com/libuv/libuv/blob/bf61390769068de603e6deec8e16623efcbe761a/src/unix/fs.c#L1138

And this one seems to be validating a specific version of AIX

https://github.com/libuv/libuv/blob/bf61390769068de603e6deec8e16623efcbe761a/src/unix/fs.c#L1155

**Comment by johnsonjh** [comment]
All versions of AIX < 7.2 are unsupported and EOL.  PASE on i 7.2 is based on AIX 7.1, so I believe that checking for just AIX is sufficient, since libuv doesn't target any lower versions, so I think it is OK as it is.  I'm not sure what the policy is for this though.  I only have access to i 7.5 to test against.  I'll take a look at the test failing later, unless someone beats me to it.

**Comment by juanarbol** [comment]
@abmusse thanks for investigating <3; I don't have access to a IBMi nor a AIX system and I'm the one who broke the whole thing. I'm sorry for not being that helpful on this one.

**Comment by johnsonjh** [comment]
I haven't tested the revised patch from @abmusse yet... but I should be able to in the next day or so on i 7.5 and latest TL/SP AIX 7.2 and 7.3 in the next day or so.

**Comment by johnsonjh** [comment]
@abmusse FYI, `_ALL_SOURCE` is always defined for libuv builds on both AIX and i.  (So the solution only needs to work there, since there isn't any possible build that doesn't define it (and not defining it would likely introduce other breakage that would need to be fixed), so I think the solution is OK.)

The `_XOPEN_SOURCE` definition happens in standards.h.  On AIX 7.2 and 7.3, when defining `_ALL_SOURCE`, it causes `_XOPEN_SOURCE` to be undefined and redefined to `700` explicitly.

**Comment by johnsonjh** [comment]
Updated with the solution from https://github.com/libuv/libuv/pull/4404#issuecomment-2113670919 for further testing

**Comment by juanarbol** [comment]
cc @richardlau

**Comment by juanarbol** [comment]
I tried to trigger the jenkins job for this, but apparently I don't have permissions. @richardlau is it possible that I  could get permissions?

**Comment by richardlau** [comment]
> I tried to trigger the jenkins job for this, but apparently I don't have permissions. @richardlau is it possible that I could get permissions?

Done

**Comment by johnsonjh** [comment]
Looks OK in my testing.

**Review by saghul — APPROVED** [review]

**Review by santigimeno — APPROVED** [review]

**Pull request merged**
