### PR TITLE
Test for interface mac, ip, and subnet discovery

### PR DESCRIPTION
**Pull request by CurlyMoo**
In addition to PR #1375 and my comment https://github.com/libuv/libuv/pull/1375#issuecomment-313756085 to the discussing that followed regarding a proper unit test, here it is.

This creates a tap device, configures that tap device with a custom ip, mac, and subnet, then uses libuv to discover the attributes of that tap device, and it finally removes the tap device again.

The test does require the `tun` kernel module to be loaded.

### CODE REVIEW

**Comment by CurlyMoo** [comment]
@bnoordhuis can you run the test for this PR including the 1375 fix as well?

**Comment by CurlyMoo** [comment]
@XadillaX can you confirm this test works for your fix?

**Comment by CurlyMoo** [comment]
@bnoordhuis i created a new branch on my account which incorporaties both PR #1375 and  #1412 so it's easier to trigger a jenkins test.
https://github.com/CurlyMoo/libuv/tree/mac-fix

**Comment by santigimeno** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/327/

**Comment by CurlyMoo** [comment]
@santigimeno  Not sure if it ran correctly due to several aborting messages?

**Comment by XadillaX** [comment]
@CurlyMoo Compilation error under my OSX.

```
test/test-interface-address.c:29:10: fatal error: 'linux/if.h' file not
      found
#include <linux/if.h>
         ^
1 error generated.
make[1]: *** [test/test_run_tests-test-interface-address.o] Error 1
make: *** [check-am] Error 2
```

**Comment by CurlyMoo** [comment]
@XadillaX was the fix you did necessary for OSX, because i believe `linux-core.c` isn't used on that system.

**Comment by XadillaX** [comment]
@CurlyMoo no, still failed

**Comment by CurlyMoo** [comment]
Ok. I will make sure it is only used on linux.

**Comment by CurlyMoo** [comment]
@XadillaX can you try again on OSX and Linux?

**Comment by XadillaX** [comment]
```
not ok 66 - tcp_connect_timeout
# exit code 6
# Output from process `tcp_connect_timeout`:
# Assertion failed in test/test-tcp-connect-timeout.c on line 42: status == UV_ECANCELED
```

I'm not sure is this failure because of my OSX or because of the test case.

**Comment by CurlyMoo** [comment]
The test we're interested in is number 193 on linux. It isn't ran on OSX. So the error you're are getting is unrelated to this PR.

**Comment by XadillaX** [comment]
@CurlyMoo 193 passed

**Comment by CurlyMoo** [comment]
@santigimeno @saghul @bnoordhuis can either of you restart the test?

**Comment by santigimeno** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/

**Comment by CurlyMoo** [comment]
@santigimeno Do you know if the tap module is available on the linux test system.

**Comment by santigimeno** [comment]
I don't think so. See: https://github.com/libuv/libuv/issues/1006

**Comment by CurlyMoo** [comment]
If not built in then at least loadable (`tun.ko`)?

**Comment by santigimeno** [comment]
Sorry I misunderstood. I thought you were referring to [Test Anything Protocol](https://en.wikipedia.org/wiki/Test_Anything_Protocol).
WRT to the original question, I don't know. You should probably ask someone from the [nodejs build group.](https://github.com/nodejs/build)

**Comment by CurlyMoo** [comment]
Ok, the test now uses a bridge network adapter instead of a tap network adapter. I believe a bridge adapter should just be supported without additional modules.

So @santigimeno can you restart the test?
@XadillaX can you also test again?

**Comment by CurlyMoo** [comment]
@bnoordhuis can we check the new version of this test as well?

**Comment by CurlyMoo** [comment]
Can someone restart the test for this code?

**Comment by CurlyMoo** [comment]
Bump

**Comment by santigimeno** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/353/

**Comment by CurlyMoo** [comment]
Hmm, seems like the network bridge module is also not available. Will add a printf in the code to check the actual value of `ret` to make sure.

**Comment by CurlyMoo** [comment]
I've added the `fprintf` so can the test be restarted?

**Comment by santigimeno** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/356/

**Comment by CurlyMoo** [comment]
@santigimeno Something went wrong not related to my changes. Can you restart?

**Comment by santigimeno** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/360/

**Comment by CurlyMoo** [comment]
@santigimeno it was on me, sorry :smile: Can we restart?

**Comment by santigimeno** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/361/

**Comment by CurlyMoo** [comment]
Hmm, let's try with an added `strerror`. errno 1 is too vague for me. So can you restart again?

**Comment by santigimeno** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/384/

**Comment by CurlyMoo** [comment]
So we are also not allowed to create network bridges. We are testing as root right?

**Comment by vtjnash** [comment]
> We are testing as root right?

I can't really comment quickly on anything else, but no, there's some tests to verify that file permissions work, and those would fail if we were running as root. So I think the answer is, no, we don't test as root.

**Pull request closed without merging**
