### PR TITLE
[requestify]: uv_read

### PR DESCRIPTION
**Pull request by saghul**
Still in very early stages, I want to collect some initial feedback, since updating / fixing all tests will take a while.

Notes on the implementation: I initially wanted to add the "completed requests" queue to the loop and start off by putting completed read and write requests there, but it's too involved and I'd need to add shutdown and connect requests there from the start. So, adjustments will be necessary for the "pull based event loop" approach, but this gets us much closer.

Things to be done:

- [x] Unix implementation
- [ ] Update tests
- [ ] Add new tests
- [ ] Windows implementation
- [ ] Merge uv_read and uv_try_read?
- [ ] Update documentation

R=@bnoordhuis
R=@piscisaureus

### CODE REVIEW

**Comment by saghul** [comment]
Updated the code restoring the UV_STREAM_READ_PARTIAL flag. While it's currently not used, something tells me we might find some use to it if we switch to edge triggered i/o, for `uv_stream_poll`.

**Comment by saghul** [comment]
UV_STREAM_READING can probably go away though.

**Comment by txdv** [comment]
what happened? why did you close it?

**Comment by saghul** [comment]
I mentioned it in #192, but I'll mention it here for the record: due to the un-fork of the repo, GH no longer updates this branch so I created a new PR.

**Pull request closed without merging**
