### PR TITLE
thread: add affinity support

### PR DESCRIPTION
**Pull request by qdaoming-intel**
Back port thread affinity support from master branch.
Add new uv_thread_getcpu() api to get the cpu number on which the calling thread is running.

### CODE REVIEW

**Comment by qdaoming-intel** [comment]
@vtjnash  Could you please review here?
I thought that the CI failures are due to incorrect URL for deb pkg, which is not related with this commit.

**Comment by bnoordhuis** [comment]
Sorry about that, that was my screw-up. If you rebase on top of v1.x, CI should work properly again.

**Comment by vtjnash** [comment]
The first commit doesn't seem to quite match what is on master. Could you split this into two PRs, and make that an exact clone of the content of master for the first one, and adding the new functionality in the second one?

**Comment by qdaoming-intel** [comment]
@vtjnash I did small modifications to the commit on the master branch to make it better.
As you prefer the exact content of master, I will split into 2 PRs as you suggested.

**Comment by vtjnash** [comment]
Yes, it will fail to merge cleanly in its present state

**Comment by qdaoming-intel** [comment]
@vtjnash There are several commits in master relate with thread-affinity feature.
So I should create a PR which squashes all of those commits, so v1.x will have same status as the latest master?

**Comment by vtjnash** [comment]
yep

**Comment by qdaoming-intel** [comment]
I have created first PR https://github.com/libuv/libuv/pull/3774 to back port thread affinity feature and related dependency commits from master. After the PR is merged, I will create second PR to add my new features.
So this PR will be closed.

**Pull request closed without merging**
