### PR TITLE
zos: improvements to uv_interface_addresses()

### PR DESCRIPTION
**Pull request by zsw007**
This PR includes several improvements to `uv_interface_addresses()` on z/OS:

- The interface address name contains EBCDIC which needs to be converted from EBCDIC to ASCII.
- The interface address name may be padded with whitespaces, which needs to be trimmed.
- Resolves an issue where `address->is_internal` is not correctly set for IPv6.
- Fixes an issue where under certain conditions, dynamically allocated ip addresses, strings, and buffers were either leaking memory, being incorrectly freed, or not performing error checks.
- Fixes an issue where the `uv_interface_address_t` struct was not correctly initialized to 0.
- Add netmask support for both IPv4 and IPv6.

Previously, `platform_output` may display something similar to:

```
#   name: ▒▒▒▒▒▒▒▒▒@@@@@@@▒▒▒▒▒@@@
#   internal: 0
#   physical address: 00:00:00:00:00:00
#   address: ::1
#   netmask: none
```

Now, `platform_output` will correctly display:

```
#   name: LOOPBACK6
#   internal: 1
#   physical address: 00:00:00:00:00:00
#   address: ::1
#   netmask: ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
```

### CODE REVIEW

**Comment by richardlau** [comment]
CI: https://ci.nodejs.org/job/libuv-test-commit/2249/

**Comment by zsw007** [comment]
> CI: https://ci.nodejs.org/job/libuv-test-commit/2249/

The failing `fs_event_close_with_pending_delete_event` tests in CI will be resolved by https://github.com/libuv/libuv/pull/3620.

**Review by richardlau — APPROVED** [review]

**Comment by richardlau** [comment]
> * The interface address name may be padded with whitespaces, which needs to be trimmed.

Are whitespaces only allowed at the end (as padding) or can interface names contain whitespace?

**Comment by zsw007** [comment]
> > * The interface address name may be padded with whitespaces, which needs to be trimmed.
> 
> Are whitespaces only allowed at the end (as padding) or can interface names contain whitespace?

To me and my team's knowledge, whitespaces would only appear at the end as padding, and not in the middle of the interface name itself.

**Pull request closed without merging**
