### PR TITLE
Add IBM i as a supported platform

### PR DESCRIPTION
**Pull request by ThePrez**
Humbly requesting IBM i be added as a supported platform via this PR.

### CODE REVIEW

**Comment by ThePrez** [comment]
Actual porting work has been contributed via PR #1601 , this is only to list IBM i as a supported platform.

**Comment by gireeshpunathil** [comment]
LGTM.
 - Do we have / plan to have `IBM i` systems added to the CI infrastructure?
 - Is it worthwhile to schedule session(s) for interested parties on the basics and peculiarities of `IBM i` and how it differs from standard UNIX systems? this helps in wider participation for development, problem determination and customer support.

**Comment by saghul** [comment]
LGTM, since there is a bunch of you, how about a team so the maintainer is libuv/ibmi or something like that?

**Comment by ThePrez** [comment]
Thanks for the prompt attention to this PR! 

Comments and responses to questions:
- **Do we have / plan to have IBM i systems added to the CI infrastructure?** Yes. This is a goal, at least from IBM i's side. We'd like to integrate into libuv and Node.js builds. We are looking at improving performance of Node.js builds currently, before fully engaging the libuv/node community. 
- **Is it worthwhile to schedule session(s) for interested parties on the basics and peculiarities of IBM i and how it differs from standard UNIX systems?** Yes, I'd love to do this. Just let me know what you're looking for.
- **Who am I?** Sorry, didn't mean to be all incognito. I'm Jesse Gorzinski, fellow IBM'er, working on open source technologies for IBM i. In lieu of a team, I can be the official maintainer and involve my team as needed (for instance, @dmabupt) 
- **Creation of specific team** Also +1 from me. Who do I engage to help make that happen? Should I just submit an issue? 

Thanks!

**Comment by gireeshpunathil** [comment]
> Just let me know what you're looking for.

roughly:
 - introduction to IBM i
 - comparison with AIX: compatibility (ABI, binary), porting guidance
 - build tools: libuv specific considerations if any
 - problem determination tips (debugger tools and debugging methodologies)

**Comment by bnoordhuis** [comment]
@ThePrez I can create a team.  Who should be in it?

**Comment by ThePrez** [comment]
@bnoordhuis, that'd be great! For starters, let's have myself, @dmabupt, and @kadler.

**Comment by ThePrez** [comment]
@gireeshpunathil, TODO taken!

**Comment by bnoordhuis** [comment]
@libuv/ibmi invites sent.

**Comment by ThePrez** [comment]
Thanks, @bnoordhuis. We could invite @mgoffmn also to the team.

**Comment by bnoordhuis** [comment]
@ThePrez Done.

**Comment by mhdawson** [comment]
@gireeshpunathil just to mention I have been talking to @ThePrez over the last while, I probably should have introduced you two as well.

**Comment by bnoordhuis** [comment]
Thanks everyone, landed in 733adae22.

**Pull request closed without merging**
