### PR TITLE
thread: utility for setting priority for thread

### PR DESCRIPTION
**Pull request by hhu8**
Add uv_thread_setpriority for setting priority for threads created by uv_thread_create. Add uv_thread_getpriority for getting thread priority.

For Linux by default, the scheduling policy is SCHED_OTHER and the priority is 0, we need to set the nice value.

### CODE REVIEW

**Comment by richardlau** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/2269/

There's a lot of red there -- some of it are test failures that are likely to be flakes/problems on the `master` branch. FWIW if you want functionality in Node.js you should target the `v1.x` libuv branch.

Specifically on Linux, a number of platforms are failing to compile:
https://ci.nodejs.org/job/libuv-test-commit-linux/2353/
e.g. 
- https://ci.nodejs.org/job/libuv-test-commit-linux/2353/nodes=debian10-x64/console
- https://ci.nodejs.org/job/libuv-test-commit-linux/2353/nodes=rhel8-x64/console

```console
  CC       src/unix/libuv_la-core.lo
src/unix/core.c: In function ‘uv_thread_getpriority’:
src/unix/core.c:1574:17: warning: implicit declaration of function ‘gettid’; did you mean ‘getgid’? [-Wimplicit-function-declaration]
     pid_t pid = gettid();
                 ^~~~~~
                 getgid
...
/usr/bin/ld: ./.libs/libuv.so: undefined reference to `gettid'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:2136: test/run-tests] Error 1
make[1]: Leaving directory '/home/iojs/build/workspace/libuv-test-commit-linux/nodes/debian10-x64'
```

From the [man pages](https://man7.org/linux/man-pages/man2/gettid.2.html), it looks like `gettid` is glibc 2.30. libuv is documented as supporting glibc 2.17 (both the master and v1.x branches): https://github.com/libuv/libuv/blob/a877ca2435134ef86315326ef4ef0c16bdbabf17/SUPPORTED_PLATFORMS.md?plain=1#L5

**Comment by hhu8** [comment]
@richardlau Thank you so much for your comment. I think I will  check the issue and create a new PR.
I made the pull request target to master, because it's the first time I submit a PR for libuv, and I read it saying in the readme file that "As a rule of thumb, bug fixes go into the stable branch while new features go into the master branch."
Regarding the CI errors, I didn't mention it before. May I ask how did you go the Jenkins page from here? Because I didn't see links or red flags here in the GitHub page. Thank you.

**Comment by mhdawson** [comment]
@hhu8 the CI is here - https://github.com/nodejs/node-gyp/issues/2860. 

I belive @richardlau kicked off a run on your PR here - https://ci.nodejs.org/view/libuv/job/libuv-test-commit/2269/

**Comment by hhu8** [comment]
@mhdawson Thank you for your answer. I think I will check the CI issues.

**Comment by hhu8** [comment]
A new PR  #4075 is created to target the v1.x branch. This PR is no longer valid.

**Comment by cjihrig** [comment]
Please close abandoned PRs.

**Pull request closed without merging**
