### PR TITLE
Make sure UDP send callbacks are always fired asynchronously

### PR DESCRIPTION
**Pull request by saghul**
R=@bnoordhuis

Fixes: https://github.com/libuv/libuv/issues/301

### CODE REVIEW

**Comment by saghul** [comment]
Well, fuck.I'm afraid the change to `uv__run_pending` has some *interesting* side effects, as in 40 failing tests or something :-(

**Comment by saghul** [comment]
The problem seems to be the following:

* The first time around, `uv_udp_send` sends immediately, so `uv__udp_sendmsg` is called and the io handle is set as pending with `uv__io_feed`, in order to run the callback on the next tick.

* On the next tick, while in `uv__run_pending`, we call `uv_udp_send` again, and because we get UV__POLLOUT, we also try to write the queued send requests, and we succeed! so we call `uv__io_feed` again, to call its callback.

* Since we're ietarting the pending queue, and `uv__io_feed` adds the handle to that very same queue, we enter an infinite loop.

I'll keep digging...

**Comment by saghul** [comment]
Solved it! All tests pass, it was a fuckup in using QUEUE_FOREACH. @bnoordhuis can you PTAL?

**Comment by bnoordhuis** [comment]
LGTM

**Comment by saghul** [comment]
Thanks Ben! Adjusted the comment and landed.

**Pull request merged**
