### PR TITLE
Linux abstract namespace socket for uv_pipe_connect, uv_pipe_bind

### PR DESCRIPTION
**Pull request by jensbjorgensen**
In current libuv, uv_pipe_connect and uv_pipe_bind cannot be used for Linux abstract namespace sockets because the leading \0 character in the address is interpreted as the end of the string. New versions of uv_pipe_connect/uv_pipe_bind are added with explicit string length (and flags, currently unused) to directly support such sockets.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
I agree abstract UNIX socket support would be valuable to have but character substitution is problematic. Paths starting with an at-sign are of course valid file paths on most operating systems.

The best I can come up with is a new `uv_pipe_bind2(uv_pipe_t*, const char*, size_t)` function (actual name TBD), ditto for connecting. They should probably take a `flags` argument as well, if we're extending the API anyway.

**Comment by jensbjorgensen** [comment]
Ok, sure, I'm interested in getting something merge-able. The topic has come up frequently and it's of interested to me personally so seems like there's demand for it. 

So I was just reading some of the discussion in https://github.com/joyent/libuv/issues/1486 

I can work over the changes to break it into such a function.

**Comment by jensbjorgensen** [comment]
so if we're adding flags, is it interesting to support things like SOCK_DGRAM and/or SOCK_SEQPACKET?

**Comment by bnoordhuis** [comment]
SOCK_DGRAM is explicitly not supported because there is no equivalent on Windows. It's why I created https://github.com/bnoordhuis/node-unix-dgram back in the day - Node.js 0.4 supported them, being UNIX-only; 0.6, the first release to support Windows, did not.

**Comment by jensbjorgensen** [comment]
ok, understood I know libuv is designed as cross-platform but I was unsure about philosophy with regards to supporting platform-specific functionality...

**Comment by jensbjorgensen** [comment]
ok so you didn't have anything in mind for flags at the moment?

**Comment by bnoordhuis** [comment]
Sorry, missed your last comment. I'd say no flags in the first iteration, just return `UV_EINVAL` when `flags != 0`.

**Comment by jensbjorgensen** [comment]
ok, I have added the function and an additional unit test. I'll let you see those before I update the documentation

**Comment by jensbjorgensen** [comment]
So I was still waiting for feedback on my updated commit.

**Comment by jensbjorgensen** [comment]
any word out there?

**Comment by jensbjorgensen** [comment]
@bnoordhuis do you mind to take a look at this again? the tests etc I think are in good shape

**Comment by cocktail828** [comment]
Mark and wait for the next merged version.

**Comment by bnoordhuis** [comment]
Closing, superseded by (merged and released) #4030. Thanks anyway for the PR.

**Pull request closed without merging**
