### PR TITLE
win: add support for recursive file watching

### PR DESCRIPTION
**Pull request by saghul**
Original patch by @ghostoy, modified by @bpasero and yours truly.

Refs: https://github.com/joyent/libuv/pull/1473
Refs: https://github.com/libuv/libuv/pull/198

R=@piscisaureus
CI: https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/114/

### CODE REVIEW

**Comment by saghul** [comment]
@piscisaureus, you already gave this a thumbs up on #198. I just took that code and fixed the flag clash and style issues, can you PTAL?

**Comment by piscisaureus** [comment]
I didn't test, but no objections from me.

**Comment by piscisaureus** [comment]
Spawning .bat files is kind-of unsupported right now - parameter passing is completely unreliable as soon as any special characters are involved. But I'm not objected to making it slightly better.

HOWEVER I'm pretty sure that this will break certain `.exe` files, because their `argv[0]` will become unreliable. So in order to land this patch I would want it to only apply to .bat and .cmd files.

**Comment by saghul** [comment]
Landed in 188e0e9, thanks!

**Comment by saghul** [comment]
@piscisaureus was [this comment](https://github.com/libuv/libuv/pull/421#issuecomment-119738686) meant for #358 ?

**Comment by piscisaureus** [comment]
> @piscisaureus was this comment meant for #358 ?

Yes it was. Oops, thanks for letting me know.

**Comment by jorangreef** [comment]
Thanks for seeing this through.

**Pull request closed without merging**
