### PR TITLE
win: support >64 processors on <Window 11

### PR DESCRIPTION
**Pull request by aachrisg**
This works around the win32 processor groups issue, allowing apps to take advanatge of multisocket systems or systems with >128 threads (such as AMD threadripper 64 core). Without this change, code using  libUV to create threads will only use 1/2 to 1/8 of the CPUs on high end windows systems.

I tested on a dual-socket Xeon with 44 cores/88 threads running Windows 10. Without this patch, no matter how many threads you create, it will only use 1/2 of the cpus (as seen in task manager). With it, you will be able to use all the cores.

This has a big affect on the Julia language, which uses libuv for its threads.

It was carefully coded to make sure it would do _nothing_ on CPU setups without the issue.

### CODE REVIEW

**Review by vtjnash — COMMENTED** [review]
Can you reformat this to libuv style?

**Comment by aachrisg** [comment]
Yes, I tried to generally follow the style I saw. I guess the indentation is off because of tabs, will fix

**Comment by aachrisg** [comment]
fixed

**Comment by vtjnash** [comment]
there needs to be spaces after keywords, and not inside `()`, but `{` needs to be on the same line. There is a more complete style guide however in https://github.com/libuv/libuv/blob/v1.x/CONTRIBUTING.md

**Comment by aachrisg** [comment]
> there needs to be spaces after keywords, and not inside `()`, but `{` needs to be on the same line. There is a more complete style guide however in https://github.com/libuv/libuv/blob/v1.x/CONTRIBUTING.md


I guess consider this working  sample code if anyone wants to fix libuv in windows.

**Comment by aachrisg** [comment]
> there needs to be spaces after keywords, and not inside `()`, but `{` needs to be on the same line. There is a more complete style guide however in https://github.com/libuv/libuv/blob/v1.x/CONTRIBUTING.md

is there a clang-format setup for this? I don't indent code, my ide does.
Is there interest in this patch if I fix the formatting? Every threaded program using libuv is kinda broken on high end xeons and threadrippers.

**Comment by vtjnash** [comment]
Windows 11 already fixes this problem, so I am inclined to just not add this. But if formatting is fixed, I could reconsider.

**Comment by GermanAizek** [comment]
> Windows 11 already fixes this problem, so I am inclined to just not add this. But if formatting is fixed, I could reconsider.

they didn't fix getting the number of threads, a good example was here: https://github.com/git-for-windows/git/issues/4766

**Comment by GermanAizek** [comment]
> Windows 11 already fixes this problem, so I am inclined to just not add this. But if formatting is fixed, I could reconsider.

@vtjnash have you still not fixed incorrect calculate threads in all Windows systems when there are multiple NUMA nodes?

**Pull request closed without merging**
