### PR TITLE
Merge 1.19.2 into master

### PR DESCRIPTION
**Pull request by santigimeno**
CI: https://ci.nodejs.org/job/libuv-test-commit/728/.

Except for the `zos` buildbot and a couple of warnings here and there, it seems mostly good.

### CODE REVIEW

**Comment by cjihrig** [comment]
Awesome. Thanks @santigimeno! There are merge conflicts and errors on zos, but other than that 👍

**Comment by jasnell** [comment]
Guess I'd better finish up the timing stats pr ! What timeframe are y'all considering for 2.0?

**Comment by santigimeno** [comment]
The `zos` [error](https://ci.nodejs.org/job/libuv-test-commit-zos/480/nodes=zos-s390x/console) I'm getting is this:

```
make: Entering directory '/u/iojs/build/workspace/libuv-test-commit-zos/nodes/zos-s390x/out'
  /bin/xlc '-D_UNIX03_THREADS' '-D_UNIX03_SOURCE' '-D_UNIX03_WITHDRAWN' '-D_OPEN_SYS_IF_EXT' '-D_OPEN_SYS_SOCK_IPV6' '-D_OPEN_MSGQ_EXT' '-D_XOPEN_SOURCE_EXTENDED' '-D_ALL_SOURCE' '-D_LARGE_TIME_API' '-D_OPEN_SYS_FILE_EXT' '-D_AE_BIMODAL' '-DPATH_MAX=255' '-DNDEBUG' -I../include -I../src  -O3  -qmakedep=gcc -MF /u/iojs/build/workspace/libuv-test-commit-zos/nodes/zos-s390x/out/Release/.deps//u/iojs/build/workspace/libuv-test-commit-zos/nodes/zos-s390x/out/Release/obj.target/libuv/src/fs-poll.o.d.raw  -q64 -c -o /u/iojs/build/workspace/libuv-test-commit-zos/nodes/zos-s390x/out/Release/obj.target/libuv/src/fs-poll.o ../src/fs-poll.c
ERROR CCN3277 ../include/uv.h:468   Syntax error: possible missing ';' or ','?
ERROR CCN3485 ../include/uv.h:468   Parameter declaration list is incompatible with declarator for inline.
ERROR CCN3045 ../include/uv.h:492   Undeclared identifier fd.
CCN0793(I) Compilation failed for file ../src/fs-poll.c.  Object file not created.
```

It seems it might be related to [this `INLINE` macro](https://github.com/santigimeno/libuv/blob/merge_1.19.2/include/uv.h#L451-L466). cc/ @libuv/zos

**Comment by santigimeno** [comment]
@bnoordhuis you're right. I've manually changed it. Does it work for you now?

**Comment by bnoordhuis** [comment]
Yep, thanks.  Apropos the zos build failure, I think this patch should do it:
```diff
diff --git a/include/uv.h b/include/uv.h
index fb5425f76..e1bc4d992 100644
--- a/include/uv.h
+++ b/include/uv.h
@@ -459,7 +459,7 @@ UV_EXTERN uv_buf_t uv_buf_init(char* base, unsigned int len);
 #if !defined(BUILDING_UV_SHARED)
 #if defined(_MSC_VER)
 # define INLINE __inline
-#elif defined(__GNUC__)
+#elif defined(__GNUC__) || defined(__MVS__)
 # define INLINE __inline__
 #else
 # define INLINE inline
```
`inline` is a c99-ism that you need to enable explicitly in xlc with `-qlanglvl=stdc99` or `-qkeyword=inline`.

**Comment by santigimeno** [comment]
Thanks. That seems to do it though lots of warnings show:

> INFORMATIONAL CCN4108 ../include/uv.h:468   The use of keyword '__inline__' is non-portable.
INFORMATIONAL CCN4108 ../include/uv.h:481   The use of keyword '__inline__' is non-portable.

Would it be better using the options you mentioned?

**Comment by bnoordhuis** [comment]
I can live with warnings for now.  cc @jBarz

**Comment by bnoordhuis** [comment]
And BTW, LGTM if everything builds.

**Comment by santigimeno** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/729/

**Comment by santigimeno** [comment]
Only one `zos` error:

```
not ok 307 - udp_multicast_join6
# exit code 3
# Output from process `udp_multicast_join6`:
# Assertion failed in ../test/test-udp-multicast-join6.c on line 136: r == 0
# CEE5207E The signal SIGABRT was received.
```

**Comment by santigimeno** [comment]
The other failures are the usual flakes

**Comment by santigimeno** [comment]
Landed in https://github.com/libuv/libuv/commit/f94282c7abc613c388a4172d8b121a3ccc1adbf5. Thanks!

**Pull request closed without merging**
