### PR TITLE
Add libuv-static pkg-config file

### PR DESCRIPTION
**Pull request by hmel**
Create a different pkg-config file for static linking. Ref. #2988

### CODE REVIEW

**Review by bnoordhuis — APPROVED** [review]
LGTM, thanks, but caveat emptor: your PR targets the master branch while releases are cut from the v1.x branch; that's also the branch where most day-to-day development takes place.

I suspect it cherry-picks cleanly so it's probably alright. CI: https://ci.nodejs.org/job/libuv-test-commit/2042/ (against master)

**Comment by cjihrig** [comment]
@hmel I see that you changed the target branch to v1.x, but then changed it back to master. Was that intentional?

**Comment by hmel** [comment]
I tried to take into account @bnoordhuis comment but that created other problems so I reverted it. Simple cherry-picking should do the job just fine.

**Comment by bnoordhuis** [comment]
CI run against v1.x: https://ci.nodejs.org/job/libuv-test-commit/2054/

I tested it locally with `cmake -DCMAKE_INSTALL_PREFIX=<path>` and it worked fine for me.

**Comment by cjihrig** [comment]
I kicked off a resume CI build and got a green run: https://ci.nodejs.org/job/libuv-test-commit/2057/

**Comment by cjihrig** [comment]
Landed in https://github.com/libuv/libuv/commit/3ee60fa72a3a562a50436a5384494e4b429ac7f0. Thanks!

**Pull request closed without merging**
