### PR TITLE
[Windows] Write out minidumps on reception of SIGQUIT

### PR DESCRIPTION
**Pull request by staticfloat**
This commit adds the ability to dump core when sending the `SIGQUIT` signal on Windows.  The change reads in the current registry setting for local dumps, and attempts to write out to that location before killing the process.  See [collecting-user-mode-dumps] for registry and pathing details. This behavior mimics that of the dumps created by the typical Windows Error Reporting mechanism.

[collecting-user-mode-dumps]: https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Seems somewhat out of place for a library like libuv.

@vtjnash I see you reviewed the JuliaLang PR. What's your reasoning?

**Comment by vtjnash** [comment]
The reasoning is that we already emulate many other common signals, but we did not emulate this one, and this is what posix would do if you send this signal. Our secondary reasoning is that we want our CI machines to save coredump files whenever we have them kill stuck processes (for later debugging), and that now works on any posix system, but SIGQUIT was unimplemented before for Windows here.

**Comment by bnoordhuis** [comment]
Maybe this is better as an opt-in since some programs may not want to get coredumped? Always-on sounds like it might open up new angles of attack for malicious actors.

The build failures are due to missing changes to CMakeLists.txt, by the way.

**Comment by staticfloat** [comment]
> Maybe this is better as an opt-in since some programs may not want to get coredumped?

It's opt-in in that an administrator has to explicitly add a registry key to get dumps to be emitted; the same registry key that would cause segfaults and other problems to create a core dump.  Because there's no reason to use `SIGQUIT` over `SIGTERM` other than to create a coredump, we figured that if someone is sending a `SIGQUIT`, they are explicitly requesting a core dump to be created (modulo administrator's permission in the form of a registry key) which serves as enough user intention.

Making the analogy to POSIX, the registry key is similar to `ulimit` providing the core dump enable and filename pattern, and SIGQUIT always making a core dump if allowed.

**Pull request merged**
