### PR TITLE
Add documentation for ninja support

### PR DESCRIPTION
**Pull request by deleisha**
This PR add documentation on how to use ninja for building libuv.

ninja files can be generated by gyp and we don't need any code change.
Please let me know, if this has to be updated in the master also

### CODE REVIEW

**Comment by bnoordhuis** [comment]
LGTM but can you sign the commit with your real name?

**Comment by deleisha** [comment]
Ben, I just did a ammendment in the same comment. 

Will you please check if it is reflecting.

**Comment by saghul** [comment]
@deleisha it still doesn't show the full name: 

~~~~
From: Devchandra <dlmeetei@gmail.com>
~~~~

**Comment by deleisha** [comment]
Oh, Thanks, Ben. 
Will Devchandra do? In fact my name is pretty long and conbersome. So I go with Devchandra only.

For just info. My full name is 
Devchandra Meetei Leishangthem.

If Devchandra is fine, That's great. Or else. I can correct the commit. Not an issue

**Comment by bnoordhuis** [comment]
Thanks Devchandra, landed under your full name in 2eb1c18.

**Comment by deleisha** [comment]
Thank you Ben. Hereafter I will use my full name in all. Learn this by working with you :)

**Pull request closed without merging**
