### PR TITLE
Revert "stream: squelch ECONNRESET error if already closed"

### PR DESCRIPTION
**Pull request by saghul**
This reverts commit 05a003a3f78d07185b7137601fe8e93561855a8d.

Refs: https://github.com/nodejs/io.js/pull/2310#issuecomment-128656552

### CODE REVIEW

**Comment by saghul** [comment]
R=@bnoordhuis

**Comment by bnoordhuis** [comment]
Rubber-stamp LGTM but can I suggest you mention in the commit log that it was causing regressions in the io.js test suite?

/cc @santigimeno

**Comment by saghul** [comment]
@bnoordhuis I added a "Refs" there, do you want me to elaborate further?

**Comment by bnoordhuis** [comment]
Just that it's nice for people that work offline (or just lazy, like me, that don't want to copy/paste the link into a browser) if the commit log tells you why the revert was necessary (test failures.)

**Comment by santigimeno** [comment]
Maybe we could just revert the Linux part (`EPOLLRDHUP`) and leave the BSD (`EV_EOF`) to address the io.js bug: https://github.com/nodejs/io.js/issues/1885 that originally caused the PR as that problem didn't appear on Linuxes

**Comment by saghul** [comment]
@bnoordhuis updated.

**Comment by saghul** [comment]
@santigimeno This patch caused other problems as well, see #474, I'd rather revert it in full now and reevaluate afterwards.

**Comment by santigimeno** [comment]
Fair enough

**Comment by reqshark** [comment]
doesnt matter the system, closing a descriptor due to an error sounds inherently tricky

**Comment by saghul** [comment]
@reqshark What do you mean? The patch didn't close any file descriptor due to an error, it replaced ECONNRESET with EOF under certain conditions.

**Comment by reqshark** [comment]
ECONNRESET means the other side closes the connection I think. If the system doesn't automatically close that descriptor shouldn't the programmer?

**Comment by saghul** [comment]
The fd is closed when you call `uv_close` on the stream, never before.

**Comment by reqshark** [comment]
@saghul I just mean to say it seems like a tricky scenario.. 

btw i looked here https://github.com/libuv/libuv/pull/475/files#diff-c9c9805d800eb132a191a9e40da6d813R1220 

UV__POLLHUP could be set and ignored. If the connection is gets closed why bother doing read?

**Comment by saghul** [comment]
> UV__POLLHUP could be set and ignored. If the connection is gets closed why bother doing read?

How would the user know otherwise? `uv__read` does more than reading, it will trigger the read callback with the appropriate error, which is what we need.

**Comment by reqshark** [comment]
ah I see. makes sense to me. thank you :)

**Comment by brendanashworth** [comment]
Question: I thought the patch would make behavior on linux & OSX equal, but OSX passed just fine. What caused linux to break but not OSX?

**Pull request merged**
