### PR TITLE
unix: add if_indextoname

### PR DESCRIPTION
**Pull request by pekkanikander**
`if_indextoname(...)` is a function defined in <net/if.h>

It is used to convert an IPv6 `scope_id` into an interface
identifier string such as `%eth0` or `%lo`

There is an identical function in Windows, but I don't have
Windows compilation environment.  Hence, Windows 
help would be appreciated.

This is needed by https://github.com/nodejs/node/pull/14500

### CODE REVIEW

**Comment by saghul** [comment]
Can you provide some justification as to why you'd like to see this in libuv?

**Comment by pekkanikander** [comment]
As I indicated above, it is needed so that my improvement to NodeJS would be accepted.
See https://github.com/nodejs/node/pull/14500

**Comment by saghul** [comment]
Ah, I see, sorry. We need a Windows implementation in order to proceed though. And at least a test.

**Comment by pekkanikander** [comment]
@saghul The implementation _may_ or may not work on Windows.  Unfortunately I have no possibility to test.  If it does not run, the probable reason is that in Windows you need to include some header file that is currently not included.  Windows does have the same underlying API.

I will add a test case later today.  But it will take some time since I will need to learn how to write test cases for uv.

**Comment by pekkanikander** [comment]
@saghul I added an `ASSERT` to the relevant test case.  I tested it on Mac OS X, which is the only platform that I have.  It _should_ run also on Windows.

If you can trigger your CI on this PR, I presume it will tell if the addition compiles and works on all platforms or not.

**Comment by santigimeno** [comment]
@pekkanikander I would target the PR to the `v1.x` branch which is the current active branch.

**Comment by pekkanikander** [comment]
I don't know how to retarget an open PR, so I am closing this one and opening a new one.

**Pull request closed without merging**
