### PR TITLE
timer: add assertion to 'uv_timer_start' that handle is not being closed

### LINKED ISSUE #2416: timer: restarting a closing timer succeeds and leads to a limbo
* **Version**: 1.29.1, 1.30.1
* **Platform**: All

Calling `uv_timer_start()` on a closing timer unexpectedly succeeds and leads to a limbo (`uv_run()` does not exit).

```c
#include <uv.h>

static void close_cb(uv_handle_t *handle) {
    printf("close_cb(%p)\n", handle);
}

static void timer_cb(uv_timer_t *handle) {
    printf("timer_cb(%p)\n", handle);
    if (uv_is_closing((uv_handle_t *)handle)) {
        uv_print_all_handles(handle->loop, stderr);
        return;
    }
    uv_close((uv_handle_t *)handle, close_cb);
    uv_timer_start(handle, timer_cb, 1000, 0);
}

int main() {
    uv_loop_t *loop = uv_default_loop();
    uv_timer_t timer;

    uv_timer_init(loop, &timer);
    uv_timer_start(&timer, timer_cb, 1000, 0);

    uv_run(loop, UV_RUN_DEFAULT);

    /* Omit cleanup */
    return 0;
}
```

Output:
```
$ ./a.out
timer_cb(0xfffaa7f4)
close_cb(0xfffaa7f4)
timer_cb(0xfffaa7f4)
[--I] signal   0xf7ede2f4
[-AI] async    0xf7ede200
^C
```

### PR DESCRIPTION
**Pull request by neoxic**
Fix #2416

### CODE REVIEW

**Comment by neoxic** [comment]
It appears there's no clear error policy as to where an assertion (compile time error) is preferred rather than returning an error code (runtime error). Some handle starting routines make an assertion that a handle isn't closing, some return EINVAL whereas others don't bother checking at all. Some housekeeping may be required.

**Comment by saghul** [comment]
> It appears there's no clear error policy as to where an assertion (compile time error) is preferred rather than returning an error code (runtime error). Some handle starting routines make an assertion that a handle isn't closing, some return EINVAL whereas others don't bother checking at all. Some housekeeping may be required.

True that. Sice we are here, however, let's decide on the way forward @libuv/collaborators I'm for a runtime error, otherwise users may run into problems in release builds, since they won't know. I'd be ok with also leaving the assert in, so it screams louder in debug builds, but that means writing a test for it is unwieldy, so I take that back. Runtime error only.

Thoughts?

Once we agree on something this PR can be adjusted and then we can align the behavior wholesale on a separate PR.

**Comment by neoxic** [comment]
I am ok with having a runtime error *everywhere* (not both for good's sake). This way, the API looks more consistent with being more like a wrapper around system calls.

It will also look more in order because there's another problem when arguments unrelated to the loop's state are currently checked in a runtime fashion (like callback pointers for example) where an assertion may be more favourable. Again, no consistency is observed.

I will fix this PR appropriately.

**Comment by neoxic** [comment]
Assertions are very helpful and efficient in most libraries as API checks when the user (programmer) is in control how they change the internal state of the library. When the user is done debugging their code, they switch them off in release builds. On the other hand, runtime errors are used when the internal state changes independently of the user's will.

So if libuv is "more like a library", assertions are preferred when the internal state is controlled solely by the user. In this regard, opening/closing handles is not possible by any means other than via API. Argument checks and other sanity checks adhere to this rule.

If libuv is "more like a wrapper around system calls" and "less like a library", then yes, error codes must be used everywhere. Your call.

**Comment by saghul** [comment]
The world is not that black and white. In libuv I'd say we have a lot more error reporting than we do assertions, which we typically keep for making sure *internal* state is correct.

If a user starts a timer, then closes it then tries to start it again, an assert is useless, because in non-debug mode it won't help. A runtime error, however, will. The fact that most our APIs return `int` is a good indication that we do report errors back as a general rule of thumb.

So I'm -1 on the current approach this PR takes.

**Comment by neoxic** [comment]
> If a user starts a timer, then closes it then tries to start it again, an assert is useless, because in non-debug mode it won't help. A runtime error, however, will.

If libuv tries to babysit users and prevent them from shooting their own foot at all costs, this approach looks legitimate. Most libraries simply state that "starting a timer after it has been closed is undefined behaviour" adding that "as a curtesy, we put an assertion for you in case you are still developing which you can easily turn off should you feel more confident".

> The fact that most our APIs return int is a good indication that we do report errors back as a general rule of thumb.

I see we are not on the same wave length regarding *compile time* vs *runtime* errors.

Again, I was simply *invited* to submit a PR and I am not here to educate anyone. I will comply to your requirements.

**Comment by saghul** [comment]
Thanks! :-)

**Comment by neoxic** [comment]
Done.

**Comment by cjihrig** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1532/

**Comment by santigimeno** [comment]
Landed in https://github.com/libuv/libuv/commit/2ee2d4622a6f00133f2a46f5cf5956ea1485c5ba. Thanks!

**Pull request closed without merging**
