### PR TITLE
build: check for warnings for -fvisibility=hidden

### PR DESCRIPTION
**Pull request by iWuzHere**
Continuation of https://github.com/libuv/libuv/pull/908
Fixes: https://github.com/libuv/libuv/issues/911

### CODE REVIEW

**Comment by iWuzHere** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/62/

**Comment by saghul** [comment]
TBH I don't know what the change does, so I defer to other with more knowledge in the area.

**Comment by bnoordhuis** [comment]
LGTM

**Comment by iWuzHere** [comment]
@saghul so currently, during `configure` we are checking if we can compile with the flag `-fvisibility=hidden` but are ignoring any warnings by not also compiling with the flag `-Werror`. This results in the massive amount of warnings being generated when compiling on AIX (and maybe other platforms, haven't checked).
The way we are doing this is calling our macro/function `CC_CHECK_CFLAGS_APPEND([-fvisibility=hidden])` but there exists another function that does the same thing but with `-Werror`, which is `CC_FLAG_VISIBILITY`.
So this change is merely replacing the check without `-Werror` with the check that does.
End result is on platforms that don't generating a warning (eg. linux) nothing changes. On platforms that do generate a warning (eg. AIX) we now no longer compile with `-fvisibility=hidden` and hence do not generate warnings for every file compiled!

**Comment by iWuzHere** [comment]
If there is no objections I will land this later today/tomorrow morning!

**Comment by indutny** [comment]
@iWuzHere Question: does these warning mean that `-fvisibility=hidden` is not supported on AIX?

**Comment by iWuzHere** [comment]
@indutny Going off the warning message when compiling with it, I would assume so.
```warning: visibility attribute not supported in this configuration; ignored [-Wattributes]```

Going off [this](https://groups.google.com/forum/#!topic/phusion-passenger/j_lIRV7CukA) (and few others from googling) it seems gcc on AIX uses AIX's assembler which does not support the visibility stuff

**Comment by indutny** [comment]
Ok, LGTM then. Thank you!

**Comment by saghul** [comment]
@iWuzHere TIL, thanks for the explanation! LGTM then!

**Comment by iWuzHere** [comment]
Landed https://github.com/libuv/libuv/commit/9940b84041402f85ec90596a47ea5c4dec6efd14. Cheers!

**Pull request closed without merging**
