### PR TITLE
Revert #1284

### PR DESCRIPTION
**Pull request by cjihrig**
This is a wholesale revert of #1284. The hope is to get AppVeyor working again in order to cut a 1.13.1 release.

### CODE REVIEW

**Comment by saghul** [comment]
Wait, this is not what I meant :-) I really don't want to see this reverted. Our CI is happy, which means it's probably some AppVeyor specific problem.

I hope this can be solved quickly and we can cut a 1.13.1 which would have Windows binaries, we can live without them for 1.13.0 IMHO.

**Comment by cjihrig** [comment]
OK, well I'll leave this open until we get the situation resolved in case it turns into a can of worms.

**Comment by saghul** [comment]
Sounds good! Thanks a lot Colin!

**Comment by cjihrig** [comment]
Closing in favor of https://github.com/libuv/libuv/pull/1405.

**Pull request closed without merging**
