### PR TITLE
build: enable warnings in autotools build

### PR DESCRIPTION
**Pull request by bnoordhuis**
Turn on -Wall -Wextra -Wno-unused-parameter, just like we do in gyp
builds.

R=@saghul

### CODE REVIEW

**Comment by saghul** [comment]
@bnoordhuis ping?

**Comment by bnoordhuis** [comment]
@saghul Sorry, missed your original reply.  Doing it from configure.ac is easiest/robustest.  I've updated the patch, PTAL.

**Comment by saghul** [comment]
@bnoordhuis LGTM. Shouldn't we remove the duplicated flags from Makefile.am then?

**Comment by bnoordhuis** [comment]
@saghul Good point, PTAL. :-)

**Comment by saghul** [comment]
OSX complains:

~~~~
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
~~~~

AFAIS we only used "-pthread" in SunOS, right?

**Comment by bnoordhuis** [comment]
@saghul Sigh.  Okay, undid the -pthread change.  PTAL?

**Comment by saghul** [comment]
LGTM :+1:

**Pull request merged**
