### PR TITLE
uv_poll_ex now alertable

### PR DESCRIPTION
**Pull request by codepilot**
Allows QueueUserAPC to run code during idle periods

### CODE REVIEW

**Comment by saghul** [comment]
Can you elaborate on why this is needed / what it fixes? Thanks!

**Comment by codepilot** [comment]
I want to user QueueUserAPC in nodejs using https://github.com/codepilot/apc
I would be moving some of the tests from there in the future

But, uv_poll_ex is not alertable, it has FALSE as the last parameter to GetQueuedCompletionStatusEx. By changing the parameter fAlertable to TRUE, and handling the return status, QueueUserAPC can now cause functions to be run and queued from inside the process, and even better, from outside.

QueueUserAPC has really low latency, and high call throughput, and there are many compelling use cases that I haven't thought up yet.

**Comment by bnoordhuis** [comment]
This would need a test at the very least.  Also, it's not clear to me why the loop time needs to be updated.

/cc @piscisaureus

**Comment by codepilot** [comment]
The reason for `uv_update_time(loop);` after an APC is called is the same as just below the commit... 
```
    /* Some time might have passed waiting for I/O,
     * so update the loop time here.
     */

```

I'm trying to think up a good test for pure libuv, not involving nodejs. I will take a look at the tests section to see what makes sense.

**Comment by piscisaureus** [comment]
> QueueUserAPC has really low latency, and high call throughput, and there are many compelling use cases that I haven't thought up yet.

Please think up the compelling cases first :) Libuv is a little too widely used to land features for shits and giggles only.

In particular, why is QueueUserAPC more useful than PostQueuedCompletionStatus (and it's wrapper uv_async) ?

There are situations where I think libuv could internally use APCs, but I think scheduling a callback from the outside is incredibly ill-advised; the code that can safely be run inside an APC is restricted, much like in a signal handler in unix.

**Pull request closed without merging**
