### PR TITLE
Docs typos

### PR DESCRIPTION
**Pull request by davisjam**
Address a few typos in the docs.

### CODE REVIEW

**Comment by davisjam** [comment]
Well, half the docs refer to "file system" and the other half refer to "filesystem". We have to pick one. It could be "file system" if that's preferred.

**Comment by cjihrig** [comment]
Ah. Yea, I agree that consistency would be better.

**Comment by sam-github** [comment]
consistency is great, I think "file system" is a bit more standard English, though "filesystem" shows up as a tech term sometimes.

**Comment by cjihrig** [comment]
Not that Wikipedia is the definitive source, but:

> In computing, a file system or filesystem...

I think either is fine, let's just be consistent.

**Comment by sam-github** [comment]
Note that after that, wikipedia goes on to use "file system" everywhere in the article, though, because "political system" not "politicalsystem"! . If its tons of work, "filesystem" is fine, but I think its a trivial search-n-replace, might as well go with actual English in our docs instead of technical slang.

**Comment by davisjam** [comment]
Alright, 4964a50 takes care of the "file system"/"filesystem" debate. Any other concerns?

**Comment by santigimeno** [comment]
Landed in https://github.com/libuv/libuv/commit/eb8509210df264d30644a93d83d5fbdf5d580231 with the commits squashed and the commit message reworded. Thanks!

**Pull request closed without merging**
