### PR TITLE
unix: remove support for FreeBSD < 10

### PR DESCRIPTION
**Pull request by saghul**
FreeBSD 9 is supported until the end of the year, but we are not going to release v2 before then, right? :-)

R= @libuv/collaborators

### CODE REVIEW

**Comment by thierry-FreeBSD** [comment]
Indeed, FreeBSD-9.3 won't be supported after 2016.

**Comment by saghul** [comment]
Thanks for confirming that @thierry-FreeBSD!

**Comment by bnoordhuis** [comment]
LGTM

**Comment by jbergstroem** [comment]
LGTM

**Comment by saghul** [comment]
Thanks for the reviews!

**Pull request merged**
