### PR TITLE
tcp, win: missing initialization of UV_READ req

### PR DESCRIPTION
**Pull request by vtjnash**
While writing the tests for #1498, I encountered uninitialized data in the `UV_SUCCEEDED_WITHOUT_IOCP` case for `uv_tcp_queue_read`. I tried to copy what the other queuing functions do, although my knowledge of what these macros do is weak. 

~~The `uv_tcp_open` also forgot to set the `READABLE` / `WRITABLE` flags (unlike the unix code), so that function didn't work for an existing open SOCKET.~~ This appears to have been addressed by #1447

### CODE REVIEW

**Comment by vtjnash** [comment]
Bump. Is there anything else to be done to get this merged?

**Comment by vtjnash** [comment]
Bumpity bump.

**Comment by bnoordhuis** [comment]
Ping @bzoz, you are probably more familiar with that code than I am.

**Comment by bzoz** [comment]
@vtjnash this does not compile on my box. Instead of `UV_REQ_INIT` macro there is `INLINE static void uv_req_init(uv_loop_t* loop, uv_req_t* req)`.

Isn't this intended for `v1.x`?

**Comment by vtjnash** [comment]
The macro is defined on master at https://github.com/libuv/libuv/blob/a00635af7a8115d88aa0c6fe15ac644a053e5c33/src/uv-common.h#L216-L229 I don't see that function anywhere. Do you have local changes?

**Comment by bzoz** [comment]
The function is here: https://github.com/vtjnash/libuv/blob/29572a0be4508d80c3434235bde76bc042358731/src/win/req-inl.h#L82, it is also referenced through `tcp.c`. It looks my repo is clean, I'll fire up CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/487/

**Comment by vtjnash** [comment]
Ah, OK, sorry: it looks like I cherry-picked this onto the wrong branch (an older master) when I was making the PR. Should be fixed now.

**Comment by bnoordhuis** [comment]
@vtjnash This targets master rather than v1.x.  Is that intentional?

**Comment by vtjnash** [comment]
I don't use v1.x, so I don't know how it might apply there.

**Comment by cjihrig** [comment]
> I don't use v1.x, so I don't know how it might apply there.

v1.x is the branch that all releases are currently made from. If you use any of our releases, then you're using v1.x. The master branch is for breaking API or ABI changes that will go into libuv 2.0.0.

**Comment by vtjnash** [comment]
> If you use any of our releases

I don't. I maintain a public fork with various bugfixes, and attempt to (slowly) get those merged here.

**Comment by vtjnash** [comment]
This was mostly addressed by #1447. (The `uv_connection_init` call does the work missing from initialization to initialize `req` that I was attempting to add here)

**Pull request closed without merging**
