### PR TITLE
spawn fail when file path contain "(" on XP and WIN10 

### PR DESCRIPTION
**Pull request by sxyizhiren**
spawn fail when file path contain "(" on XP and WIN10 .
such issue not appear on .exe file, but appear on .bat file.
I first report it at https://github.com/nodejs/io.js/pull/1869.

my resolve way is :
change each '(' in arg[0] to "^(".

### CODE REVIEW

**Comment by piscisaureus** [comment]
@sxyizhiren 
I think it would be better if you just added the character to the "search list" in https://github.com/libuv/libuv/blob/c619f37c3986b0ec5d13fb7f2437dff0db41c72b/src/win/process.c#L461.

**Comment by sxyizhiren** [comment]
hi @piscisaureus 
i think you mean that, if contain '(', then add quote '"' to the string. 
i have tested it, adding quote to the arg[0] couldn't resolve it.

**Comment by piscisaureus** [comment]
Spawning .bat files is kind-of unsupported right now - parameter passing is completely unreliable as soon as any special characters are involved. But I'm not objected to making it slightly better.

HOWEVER I'm pretty sure that this will break certain .exe files, because their argv[0] will become unreliable. So in order to land this patch I would want it to only apply to .bat and .cmd files.

**Comment by sxyizhiren** [comment]
@piscisaureus ok, got it. so , should we keep it , or i will try to find a way that "only apply to .bat and .cmd files"  ?

**Comment by bzoz** [comment]
[MSDN for CreateProcessW](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425.aspx) says you should spawn `cmd.exe` and pass the script as parameter - e.g. [the way Node does this](https://github.com/nodejs/node/blob/fda25665be353396518927ad42a2f617816591c6/lib/child_process.js#L442).

I say we close the PR, because of this and because its almost 2 years old.

**Comment by bnoordhuis** [comment]
Sounds good, I'll close.  Thanks anyway @sxyizhiren.

**Pull request closed without merging**
