### PR TITLE
Visual Studio 2017

### PR DESCRIPTION
**Pull request by ctaggart**
Any chance ya'll could support Visual Studio 2017 too? https://suave.io/ uses libuv and I want to upgrade its build to VS 2017, but need libuv working with it first. I was hoping `set GYP_MSVS_VERSION=2017` would work, but I guess not. As is right now with, this errors with:

https://ci.appveyor.com/project/ctaggart/libuv/build/job/y841gaeo6okfpl9l
```
set GYP_MSVS_VERSION=2015
vcbuild.bat release %ARCH% shared
['-Dtarget_arch=ia32', '-Duv_library=shared_library', '.\\uv.gyp', '-I', '.\\common.gypi', '--depth=.', '-Dhost_arch=x64']
Project files generated.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  fs-poll.c
  inet.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\corecrt.h(10): fatal error C1083: Cannot open include file: 'vcruntime.h': No such file or directory (compiling source file src\fs-poll.c) [C:\projects\libuv\libuv.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\corecrt.h(10): fatal error C1083: Cannot open include file: 'vcruntime.h': No such file or directory (compiling source file src\inet.c) [C:\projects\libuv\libuv.vcxproj]
  loop-watcher.c
  threadpool.c
```

### CODE REVIEW

**Comment by gibfahn** [comment]
Maybe cc/ @refack and @joaocgreis, who did the equivalent `node-gyp` update.

**Comment by refack** [comment]
Looking in...

**Comment by ctaggart** [comment]
Visual Studio 2017 loads and modifying the file locally. It simply changed the `PlatformToolset` from `v140` to `v141`. For the AppVeyor build, I just codes that change in `appveyor.ps1`. 

To build locally, I had to install:
* Standard Library Modules
* VC++ 2017 v141 toolset (x86,x64)
* Windows 10 SDK (10.0.10240.0)

image

image

You can actually create a script like I did for F# with [Add-VisualStudioComponents.ps1](https://github.com/Microsoft/visualfsharp/blob/master/scripts/Add-VisualStudioComponents.ps1) to add help develops install those dependencies. Would ya'll like one?

**Comment by ctaggart** [comment]
Okay, this works now. https://ci.appveyor.com/project/ctaggart/libuv/build/v1.10.2.build15

**Comment by refack** [comment]
We have a way to trick `GYP` into outputting VS2017 compatible `vcxproj` files by itself...

Also It you don't add `<WindowsTargetPlatformVersion>10.0.14393.0</WindowsTargetPlatformVersion>` VS will assume windows 8.1 SDK so wither add the settings to the `vcxproj` files, or the SDK to [Add-VisualStudioComponents.ps1](https://github.com/Microsoft/visualfsharp/blob/master/scripts/Add-VisualStudioComponents.ps1)

**Comment by ctaggart** [comment]
Thanks @refack, I've updated this pull request to make that change too.  This pull request adds two files:
* scripts/Add-VisualStudioPackages.ps1
* scripts/Update-ProjectFilesToVS2017.ps1

The `appveyor.yml` is updated to run on Visual Studio 2017 and it uses the `Update-ProjectFilesToVS2017.ps1`. 

The Add-VisualStudioPackages.ps1 is an easy way to both document and help developers install the necessary Visual Studio packages required to build libuv. Currently, they are:

- MS Build
- Visual C++ 2017 v141 toolset (x86,x64)
- Standard Library Modules
- Windows 10 SDK (10.0.14393.0)

**Comment by refack** [comment]
@ctaggart I like `Add-VisualStudioPackages.ps1`, maybe rename to "Setup-VisualStudio2017", and add a fallback if you can't find `vs_installershell.exe` you can ask the user if xe wants to DL the [BuildTools SKU](https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15#) which you can silently install.
Also if you land #1284 you won't need `Update-ProjectFilesToVS2017.ps1` and then the changes in appveyor.yml are minimal.

**Comment by refack** [comment]
Also vote for https://chromium-review.googlesource.com/c/456360/ then we get native VS2017 `GYP` support

**Comment by refack** [comment]
P.S. IMHO you should [squash ](http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) all these commits together, and force push

**Comment by ctaggart** [comment]
GitHub has a wonderful squash merge feature. I starred that googlesource issue. Not sure if that is a vote for it. Suave is still on libuv 1.9.1. I think this solution should work for it. I'm headed back to work on my projects. Please merge/amend/close this pull request as you see fit.

**Comment by saghul** [comment]
Can you please re-target this to v1.x? That's the current active branch, v1.x is the next major release branch. Thanks!

**Comment by ctaggart** [comment]
@saghul Sure.

**Pull request closed without merging**
