### PR TITLE
win: remove code that was there only to support Windows XP

### PR DESCRIPTION
**Pull request by piscisaureus**

### CODE REVIEW

**Comment by genio** [comment]
Wait. Wasn't XP support just recently fixed? I know it's not supported, but maybe it shouldn't be willfully broken if people are still using it.

**Comment by genio** [comment]
https://github.com/libuv/libuv/pull/1854 addressed that already. sorry

**Comment by bzoz** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/903/

**Comment by cjihrig** [comment]
Another CI (green on Windows): https://ci.nodejs.org/view/libuv/job/libuv-test-commit/907/

I think this is good to land.

**Pull request merged**
