### PR TITLE
ci: use macOS 12 for macOS and iOS builds

### PR DESCRIPTION
**Pull request by saghul**
macOS 11 is gone: https://github.com/actions/runner-images/pull/10198

### CODE REVIEW

**Review by cjihrig — APPROVED** [review]

**Comment by saghul** [comment]
Hum, this line is blowing up: https://github.com/libuv/libuv/blob/90648ea3e55125a5a819b32106da6462da310da6/test/test-udp-multicast-join.c#L163 with error `ENOEXEC`. Should we also check for that?

**Comment by saghul** [comment]
Ah right: https://github.com/libuv/libuv/issues/4263 I'll skip it in the test...

**Comment by saghul** [comment]
@cjihrig can you PTAL again? :-) Also, ping @bnoordhuis since you commented on the macOS >= 13 test failure issue.

**Review by cjihrig — APPROVED** [review]
Still LGTM

**Comment by saghul** [comment]
Doh there is one more failure 😞 

I think I'm going to split this into 2 PRs, so the CI can be happy while I look into adding the macOS 14 runner.

**Comment by bnoordhuis** [comment]
If I read the assert right, it's failing with EBUSY in uv_udp_set_source_membership() when trying to join 239.255.0.1.

@juanarbol observed in https://github.com/libuv/libuv/issues/4263#issuecomment-1940161873 that 239.255.255.250 is accepted but is not able to receive (and send?)

**Comment by saghul** [comment]
Yeah noticed that but it was late 😅 I'll investigate further!

**Comment by saghul** [comment]
UPdated to remove the macOS 14 change, will do that in a separate PR. Also addressed the sanitizer job using macOS 11.

**Pull request merged**
