### PR TITLE
fs: realpath: fix string size before converting

### PR DESCRIPTION
**Pull request by jhamhader**
fs__realpath_handle() removes the UNC prefixes \\?\ and \\?\UNC\
from paths returned by GetFinalPathNameByHandle, but doesn't
update the string length before sending it to fs__wide_to_utf8.
Fix that by decrement the correct size from the string length.

Fixes the issue raised by @mscdex in nodejs/node#3594.

### CODE REVIEW

**Comment by saghul** [comment]
Can you add a regression test for this?

**Comment by jhamhader** [comment]
Unfortunately no, as it depends on the content of the memory after the allocated buffer in `fs__realpath_handle()`.

**Comment by jhamhader** [comment]
Any chance to merge this?

**Comment by saghul** [comment]
Sorey Yuval, I hope to get back to some windows PRs this upcoming week.

**Comment by jhamhader** [comment]
@saghul - I think it could be great to have that for the 6.0.0 node release. I would appreciate if you will have the time to review and merge this.
Thanks!

**Comment by mscdex** [comment]
+1

**Comment by txdv** [comment]
@mscdex I think github created the reactions so you wouldn't have to write it out:

https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

> but other times you just want to :+1: someone else's comment. We're adding Reactions to conversations today to help people express their feelings more simply and effectively.

**Comment by mscdex** [comment]
> @mscdex I think github created the reactions so you wouldn't have to write it out:
> 
> https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments
> 
> but other times you just want to  someone else's comment. We're adding Reactions to conversations today to help people express their feelings more simply and effectively.

-1

**Comment by saghul** [comment]
LGTM, let's see if the CI is green: https://ci.nodejs.org/job/libuv+any-pr+multi/285/

**Comment by mscdex** [comment]
Looks like unrelated failures and a possible CI infrastructure-related issue on the win2012r2 node?

**Comment by saghul** [comment]
Yep, it's the usual Jenkins brainfart.

**Comment by saghul** [comment]
Landed in 5dc15cc, thanks! And sorry for the delay!

**Pull request closed without merging**
