### PR TITLE
[v2] Switch to c99?

### PR DESCRIPTION
**Pull request by saghul**
Looks like Microsoft got it together and starting with MSVC 2013 and continuing with 2015 c99 support has improved. 2015 implements most of the c99 standard library: https://msdn.microsoft.com/en-us/library/hh409293.aspx#BK_CRT

Some stuff is not supported yet, like VLAs, but other stuff is. Proposal: switch to the GNU C99 subset MSVC 2015 supports, going forward.

This PR was a quick experiment to see if smoke would come out.

@libuv/collaborators WDYT?

### CODE REVIEW

**Comment by saghul** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/90/

@misterdjules SmartOS is failing: https://ci.nodejs.org/job/libuv-test-commit-smartos/90/nodes=smartos14-32/console any idea why?

**Comment by misterdjules** [comment]
@saghul Looking.

**Comment by misterdjules** [comment]
I've been interrupted quickly before I could make any progress on this, but I'll have more time to dig in tomorrow if I can't get back to it tonight. I'll keep you posted.

**Comment by txdv** [comment]
I know this is just a general move towards C99, but are there any features that would make some situations immediately easier?

I'm a big fan of in loop variable declaration **for (int i = 0** ...

**Comment by saghul** [comment]
@txdv A quick list of things that become better with c99 (though I don't plan to go and modify all existing code, of course)

- `long long` is no longer an extension
- we could use `bool`
- mixed code and declarations (though I like to declare vars at the top, this can get in the way on functions with several ifdefs)
- designated initializers

Due to the change we also get rid of a few warnings, which is always a good thing.

**Comment by saghul** [comment]
@misterdjules No problem, thanks! Note that this PR is against master, not v1.x, so there is no real rush.

**Comment by bnoordhuis** [comment]
LGTM

**Comment by misterdjules** [comment]
@saghul I pushed [a commit](https://github.com/misterdjules/libuv-1/commit/cd90e1e7bd41e7d11f5d66cfa53cee47de05632f) on my own fork of your `c99` branch that I believe fixes the build issue on SmartOS.

It looks like in the current `c99` branch, tests are not built with the gnu99 mode when they're built with gyp, so the same changes to define `_XOPEN_SOURCE=600` would need to be made to the tests' build section in `uv.gyp`.

It might be the case for benchmarks too and other targets, I haven't done a thorough search.

I hope that helps!

**Comment by saghul** [comment]
@misterdjules Thanks! I'll take a look and incorporate your changes, then run anotehr CI.

**Comment by saghul** [comment]
@misterdjules 

I think the tests inherit the flags:

~~~~
  cc '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GNU_SOURCE' '-D_DARWIN_USE_64_BIT_INODE=1' '-DDEBUG' '-D_DEBUG' -I../include  -O0 -gdwarf-2 -fvisibility=hidden -arch x86_64 -Wall -Wextra -Wno-unused-parameter -Wall -Wendif-labels -W -Wno-unused-parameter -g --std=gnu99 -pedantic -fstrict-aliasing -Wno-strict-aliasing -MMD -MF /Users/saghul/src/libuv/out/Debug/.deps//Users/saghul/src/libuv/out/Debug/obj.target/run-tests/test/blackhole-server.o.d.raw   -c -o /Users/saghul/src/libuv/out/Debug/obj.target/run-tests/test/blackhole-server.o ../test/blackhole-server.c
  cc '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GNU_SOURCE' '-D_DARWIN_USE_64_BIT_INODE=1' '-DDEBUG' '-D_DEBUG' -I../include  -O0 -gdwarf-2 -fvisibility=hidden -arch x86_64 -Wall -Wextra -Wno-unused-parameter -Wall -Wendif-labels -W -Wno-unused-parameter -g --std=gnu99 -pedantic -fstrict-aliasing -Wno-strict-aliasing -MMD -MF /Users/saghul/src/libuv/out/Debug/.deps//Users/saghul/src/libuv/out/Debug/obj.target/run-tests/test/echo-server.o.d.raw   -c -o /Users/saghul/src/libuv/out/Debug/obj.target/run-tests/test/echo-server.o ../test/echo-server.c
  cc '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GNU_SOURCE' '-D_DARWIN_USE_64_BIT_INODE=1' '-DDEBUG' '-D_DEBUG' -I../include  -O0 -gdwarf-2 -fvisibility=hidden -arch x86_64 -Wall -Wextra -Wno-unused-parameter -Wall -Wendif-labels -W -Wno-unused-parameter -g --std=gnu99 -pedantic -fstrict-aliasing -Wno-strict-aliasing -MMD -MF /Users/saghul/src/libuv/out/Debug/.deps//Users/saghul/src/libuv/out/Debug/obj.target/run
~~~~

**Comment by saghul** [comment]
New CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/91/

**Comment by saghul** [comment]
SunOS works now! :tada:

**Comment by misterdjules** [comment]
@saghul 

> I think the tests inherit the flags

When building the tests as part of a `make -C out` command, yes, but when building the tests specifically, it seems it's not the case:

```
[root@0c933410-7c9b-4bea-96b6-2db35946bc95 ~/libuv]# make run-tests -C out/ V=1
make: Entering directory '/root/libuv/out'
  cc '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GNU_SOURCE' '-D__EXTENSIONS__' '-D_XOPEN_SOURCE=500' '-DDEBUG' '-D_DEBUG' -I../include  -pthreads -Wall -pthreads -fno-omit-frame-pointer -g -O0 -fwrapv  -MMD -MF /root/libuv/out/Debug/.deps//root/libuv/out/Debug/obj.target/run-tests/test/blackhole-server.o.d.raw   -c -o /root/libuv/out/Debug/obj.target/run-tests/test/blackhole-server.o ../test/blackhole-server.c
  cc '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GNU_SOURCE' '-D__EXTENSIONS__' '-D_XOPEN_SOURCE=500' '-DDEBUG' '-D_DEBUG' -I../include  -pthreads -Wall -pthreads -fno-omit-frame-pointer -g -O0 -fwrapv  -MMD -MF /root/libuv/out/Debug/.deps//root/libuv/out/Debug/obj.target/run-tests/test/echo-server.o.d.raw   -c -o /root/libuv/out/Debug/obj.target/run-tests/test/echo-server.o ../test/echo-server.c
...
```

**Comment by saghul** [comment]
@misterdjules Oh, TIL! I never did it that way, to be honest.

**Pull request merged**
