### PR TITLE
build: add CMake option LIBUV_BUILD_SHARED to enable/disable shared library

### LINKED ISSUE #3637: Add CMake configuration option to disable shared library build
I am using libuv in the project which targets multiple platforms including WebAssembly (in this case a large networking part of my project is disabled, but I still use libuv for multithreading and synchronization primitives). I include libuv using add_subdirectory and use static linking, but there are no way to disable shared library building and for WASM platform (which doesn't support shared libraries) I got annoying warnings:

```
CMake Warning (dev) at lib/libuv/CMakeLists.txt:391 (add_library):
  ADD_LIBRARY called with SHARED option but the target platform does not
  support dynamic linking.  Building a STATIC library instead.  This may lead
  to problems.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

Is it possible to add an option to disable shared library building (many other libraries have that)?

### PR DESCRIPTION
**Pull request by techtim**
Fix #3637

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Comment by clason** [comment]
bump?

**Comment by clason** [comment]
On a related note, would it be possible to build the static library as just `uv` (instead of `uv_a`) when `LIBUV_BUILD_SHARED=OFF`? This would allow applications like Neovim to statically link both LibUV and LUV (which currently is only possible with major contortions).

**Review by gengjiawen — CHANGES_REQUESTED** [review]
when turned off, default build will fail.

/workspace/libuv/test/blackhole-server.c:22:10: fatal error: uv.h: No such file or directory
   22 | #include "uv.h"
      |          ^~~~~~
compilation terminated.

**Comment by lewis6991** [comment]
Not from our experience.

We are successfully able to apply this PR via a patch. See https://github.com/neovim/neovim/pull/19632

**Comment by gengjiawen** [comment]
> Not from our experience.
> 
> We are successfully able to apply this PR via a patch. See [neovim/neovim#19632](https://github.com/neovim/neovim/pull/19632)

Looks related to `BUILD_TESTING` config.

**Comment by clason** [comment]
Bad bot. Bump?

**Comment by gengjiawen** [comment]
> when turned off, default build will fail.
> 
> /workspace/libuv/test/blackhole-server.c:22:10: fatal error: uv.h: No such file or directory 22 | #include "uv.h" | ^~~~~~ compilation terminated.

@clason

**Comment by clason** [comment]
Again, we build LibUV fine with with `LIBUV_BUILD_SHARED=OFF`, see https://github.com/neovim/neovim/blob/37a71d1f28e5d7fd13f0ede69b4d2558157a9e4b/cmake.deps/cmake/BuildLibuv.cmake#L9

So there's something else going on. Can you share a complete build invocation?

**Comment by gengjiawen** [comment]
> Again, we build LibUV fine with with `LIBUV_BUILD_SHARED=OFF`, see [neovim/neovim@`37a71d1`/cmake.deps/cmake/BuildLibuv.cmake#L9](https://github.com/neovim/neovim/blob/37a71d1f28e5d7fd13f0ede69b4d2558157a9e4b/cmake.deps/cmake/BuildLibuv.cmake#L9)
> 
> So there's something else going on. Can you share a complete build invocation?

Just set line 31 to OFF. And build

```
mkdir build
cd build
cmake -G Ninja ..
cmake --build .
```

console
```
gitpod /workspace/libuv/build (cmake-build-shared-option) $ cmake --build .
[26/408] Building C object CMakeFiles/uv_run_tests.dir/test/test-getsockname.c.o
FAILED: CMakeFiles/uv_run_tests.dir/test/test-getsockname.c.o 
/usr/bin/cc -DUSING_UV_SHARED=1 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112  -fvisibility=hidden -Wstrict-prototypes -Wextra -Wall -Wno-unused-parameter -fno-strict-aliasing -std=gnu90 -MD -MT CMakeFiles/uv_run_tests.dir/test/test-getsockname.c.o -MF CMakeFiles/uv_run_tests.dir/test/test-getsockname.c.o.d -o CMakeFiles/uv_run_tests.dir/test/test-getsockname.c.o -c /workspace/libuv/test/test-getsockname.c
/workspace/libuv/test/test-getsockname.c:22:10: fatal error: uv.h: No such file or directory
   22 | #include "uv.h"
      |          ^~~~~~
compilation terminated.
[43/408] Building C object CMakeFiles/uv_run_benchmarks_a.dir/test/benchmark-fs-stat.c.o
ninja: build stopped: subcommand failed.
```

**Comment by clason** [comment]
That looks like a test that fails, not the library itself? (Which is not as surprising that those would need to be adapted.)

**Comment by clason** [comment]
@gengjiawen Do I understand you correctly that it would be acceptable if `LIBUV_BUILD_SHARED` disabled the tests?

**Comment by vtjnash** [comment]
Merged in https://github.com/libuv/libuv/pull/3762

**Pull request closed without merging**
