### PR TITLE
doc: fix code highlighting

### PR DESCRIPTION
**Pull request by RaisinTen**
Fixes: https://github.com/libuv/libuv/issues/3033

### CODE REVIEW

**Review by santigimeno — APPROVED** [review]
RSLGTM

**Comment by RaisinTen** [comment]
Gentle reminder, in case you forgot to merge this. :)

**Comment by RaisinTen** [comment]
@santigimeno what should we do next? This keeps getting marked as stale.

**Comment by santigimeno** [comment]
@RaisinTen sorry for the delay. If you could rebase and squash the commits I'll merge it right away. Thanks!

**Comment by RaisinTen** [comment]
> @RaisinTen sorry for the delay. If you could rebase and squash the commits I'll merge it right away. Thanks!

@santigimeno thanks for mentioning. Done! :D

**Comment by santigimeno** [comment]
Landed in https://github.com/libuv/libuv/commit/c3d08b5d63267c70554da081ce9f35dfb81132e2. Thanks!

**Pull request closed without merging**
