### PR TITLE
common: fix use of snprintf on Windows

### PR DESCRIPTION
**Pull request by saghul**
Refs: https://github.com/libuv/libuv/pull/467

R=@bnoordhuis

### CODE REVIEW

**Comment by saghul** [comment]
CI: https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/134/

**Comment by bnoordhuis** [comment]
I could swear we used to have a `snprintf()` definition for win32...

I don't really like `_snprintf()` because it doesn't zero-terminate like `snprintf()` does when the buffer is too small.  But meh, LGTM, I guess.

**Comment by saghul** [comment]
> I could swear we used to have a snprintf() definition for win32...

That's on the test suite.

> I don't really like _snprintf() because it doesn't zero-terminate like snprintf() does when the buffer is too small. But meh, LGTM, I guess.

I guess we could add a `uv__snprintf`, I just followed what we do on inet.c this time around :-)

**Comment by mscdex** [comment]
FWIW, VS2015 has `snprintf()` finally.

**Comment by jasonwilliams200OK** [comment]
@saghul, why can't we use `_MSC_VER < 1900` condition here as well as we did in: https://github.com/libuv/libuv/pull/341, to keep libuv buildable with VS2015?

**Comment by saghul** [comment]
@jasonwilliams200OK Yes, I'd entertain a PR :-)

**Pull request merged**
