### PR TITLE
bsd: Allow IPv6 on NetBSD

### PR DESCRIPTION
**Pull request by krytarowski**
Do not exclude IPv6 functionality on NetBSD.

### CODE REVIEW

**Comment by santigimeno** [comment]
@qbit could you check if it works on `OpenBSD`?

**Comment by qbit** [comment]
Builds fine, but I get a lot of ipv6 errors in `make check.

**Comment by krytarowski** [comment]
Is this good enough? Or just enable ipv6 only for NetBSD?

**Comment by qbit** [comment]
Lets just do NetBSD for now - I will poke around and see if I can clean up the OpenBSD stuffs.

**Comment by krytarowski** [comment]
I never installed other BSD than NetBSD, so I will leave them to others. All ipv6 tests pass on my OS.

I'm going to rediff the patch and enable ipv6 on NetBSD only.

**Comment by krytarowski** [comment]
done!

**Comment by cjihrig** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/511/

**Comment by cjihrig** [comment]
@gibfahn FYI, on macOS, the CI job I just launched yielded `No space left on device`

**Comment by gibfahn** [comment]
@cjihrig sounds like https://github.com/nodejs/build/issues/899, unfortunately only the build infra group have access to the macOS machines at the moment AFAIK.

**Comment by cjihrig** [comment]
Ah OK. I thought that included you. Thanks anyway 😄

**Comment by krytarowski** [comment]
Apple is using NetBSD code.. however it does not define __NetBSD__.

**Comment by cjihrig** [comment]
@krytarowski Yea, I wasn't worried about the CI failure with regards to this PR. I was just trying to bring attention to it, since it will likely need to be cleaned up.

**Comment by cjihrig** [comment]
Landed in https://github.com/libuv/libuv/commit/001a4a11f624153a3f27a7efef9746eb03d519d7. Thanks!

**Pull request closed without merging**
