### PR TITLE
Feature: added uv_allocator_t with opaque user-pointer support.

### PR DESCRIPTION
**Pull request by psyirius**
Added a public type `uv_allocator_t` with an opaque ptr in addition to the allocator functions.

Breaking API/ABI:
- uv allocator functions
- uv_replace_allocator function

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Thanks for the pull request but I'm kind of meh on this if I'm honest.

The malloc/free wrappers were added as a nice-to-have for embedders that want to track libuv's memory metrics and it works well enough for that. Unless you have a really compelling reason, I'd rather leave well enough alone.

Furthermore, since it can't land in the v1.x branch and there are no plans for v2, you probably won't see this released anytime soon.

**Comment by vtjnash** [comment]
> The malloc/free wrappers were added as a nice-to-have for embedders that want to track libuv's memory metrics and it works well enough for that. Unless you have a really compelling reason, I'd rather leave well enough alone.

For that use case, `free` and `realloc` should probably have had an original_size argument too, though it may be painful to change all free calls to include that.

> there are no plans for v2

I make semi-frequent alpha-releases of v2, so people are welcome to use it already. There are a small set of bugfixes and other breaking improvements that cannot be included in v1 (for example, v2 already fixes the 2038 problem that looming on the horizon for v1 users).

**Comment by psyirius** [comment]
> Thanks for the pull request but I'm kind of meh on this if I'm honest.
> 
> The malloc/free wrappers were added as a nice-to-have for embedders that want to track libuv's memory metrics and it works well enough for that. Unless you have a really compelling reason, I'd rather leave well enough alone.
> 
> Furthermore, since it can't land in the v1.x branch and there are no plans for v2, you probably won't see this released anytime soon.

Thank you for your feedback on the PR.

This PR is made to add support for contextful allocators which is pretty common on when pairing with C++.
We have a Multi Context Script Runtime in development. which needs this feature in place in order to use the allocator of specific runtime instance.

image

**Comment by psyirius** [comment]
> > We have a Multi Context Script Runtime in development. which needs this feature in place in order to use the allocator of specific runtime instance.
> 
> Not sure I follow. As long as you diligently close libuv handles and loops, no memory is leaked. You don't have to care where memory was allocated from, right?

Btw, there is a memory leak tho. if i uncomment that idle part.

image

3 blocks haven't released!

**Comment by psyirius** [comment]
> > We have a Multi Context Script Runtime in development. which needs this feature in place in order to use the allocator of specific runtime instance.
> 
> Not sure I follow. As long as you diligently close libuv handles and loops, no memory is leaked. You don't have to care where memory was allocated from, right?

Basically the environment provides a cpp allocator which is specific to a cpp allocator object which is of a specific runtime object. The allocator will take care of metrics of the runtime.

the opaque ptr i added to the methods is to pass the allocator instance ptr.
thus the allocations will be contextful with the use of opaque ptr just like `handle->data`.

**Comment by bnoordhuis** [comment]
> uv_close_loop returns UV_EBUSY, not sure why!

That means there are still open handles or in-flight requests. With all due respect, it sounds like you're abusing the allocator to work around a logic bug in your program.

**Comment by psyirius** [comment]
BTW, the above snaps is not from the actual project.
That was just a memory metric test.
Also, i don't think adding a ptr member to the allocator abuses it.
Just adds a context to the allocator callback functions.
I think you don't understand the actual use case which i'm trying to state.

Also, to be honest, I don't care about this anymore.
Cuz, we home brewed a platform layer like we needed.

Thank you for you feedback tho!

**Pull request closed without merging**
