### PR TITLE
doc: add reference to uv_update_time from uv_timer_start

### PR DESCRIPTION
**Pull request by alexhultman**
I'm not sure this is correct. It probably isn't. I have no idea about this .rst thing. Hope this is a decent piece of text to start from at least.

### CODE REVIEW

**Comment by saghul** [comment]
Hey, thanks for the patch!  Left a comment about the reference syntax, otherwise it's ok.

**Comment by alexhultman** [comment]
Thanks, I didn't get that reference system. This PR lies in the top now so it should be mergable.

**Comment by saghul** [comment]
Landed in 8ebecf6, sorry for the delay! I see this is your first commit in libuv Alex, thank you and welcome aboard!

**Comment by alexhultman** [comment]
Thanks :+1:

**Pull request closed without merging**
