### PR TITLE
implement combine path func

### PR DESCRIPTION
**Pull request by recp**
Some languages already provide funcs for combining two paths 
for instance .NET's Path.Combine() or ObjC's [NSString stringByAppendingPathComponent] funcs

It would be nice to see this convenient func for C in libuv

Usage:
```C
char path[PATH_MAX]; 

uv_path_combine("/usr/local/Folder1",
                "SomeFolder or File",
                path);

fprintf(stderr, "path: '%s'\n", path);
/*
 path: '/usr/local/Folder1/SomeFolder'  
*/
```

### CODE REVIEW

**Comment by saghul** [comment]
I think this could be useful. I'd like to propose a different API though:

~~~~
int uv_path_join(char** fragments, char* buf, size_t* size)
~~~~

`fragments` is an array of strings ending in NULL, `buf` would be the output buffer and `size` the output buffer's size, as an in-out parameter.

Then one could do:

~~~~
char path[4096];
size_t len = sizeof(path);

int r = uv_path_join((char *[]){"/usr", "local", "bin", NULL}, path, &size);
...
~~~~

**Comment by recp** [comment]
good api name @saghul 

I'll update it as your proposal ASAP

should we change the parameter orders like traditional c apis; 
out parameters come first:
```C
int uv_path_join(char* buf, char** fragments, size_t* size)
```

**Comment by recp** [comment]
I've implemented @saghul's proposal

the returned size doesnt count NULL char, 
should it (len + 1)?

/cc @libuv/collaborators

**Comment by bnoordhuis** [comment]
I don't really see a pressing need to add this to libuv.  There are no platform differences to paper over, it's purely a convenience function.

**Comment by saghul** [comment]
@bnoordhuis I don't disagree :-) I'm +-0 here, no strong opinions either for or against.

**Comment by cjihrig** [comment]
If it doesn't fit with the theme of the project, and there isn't anywhere internally that we could use it, then I'd say it's probably just extra API area for bugs and maintenance.

**Comment by saghul** [comment]
Okidoki. Sorry @recp the crowd has spoken!

**Comment by recp** [comment]
ok, thanks for review

**Pull request closed without merging**
