### PR TITLE
[WIP] Initial support for Meson build

### PR DESCRIPTION
**Pull request by concatime**
Hi devs.
This is a work-in-progress PR to add Meson build system. For now, this PR is intended to centralize efforts into one place.
I can’t do all the work because I don’t have access to all theses systems nor that much free time. So all help is welcome!

Platform tried yet:
  - [ ] Android
  - [ ] Darwin
  - [x] DragonFly BSD
  - [x] FreeBSD
  - [ ] Haiku
  - [x] Linux
  - [ ] NetBSD
  - [x] OpenBSD (but lot of `zero-length-array` warnings!)
```
../libuv/include/uv/unix.h:160:12: warning: zero size arrays are an extension [-Wzero-length-array]
  char pad[sizeof(pthread_barrier_t) - sizeof(struct _uv_barrier*)];
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
  - [ ] SunOS
  - [x] Windows (10)

Further goals:
  - [ ] Add CI
  - [ ] Split into multiple tests
  - [ ] Add benchmarks ([`benchmark()`](https://mesonbuild.com/Reference-manual.html#benchmark))

Three remarks:
  - Meson supports neither AIX, nor OS390, nor OS400 nor QNX AFAIK ([Operating system names](https://mesonbuild.com/Reference-tables.html#operating-system-names))
  - libuv’s pkgconfig should be named “uv” (file `uv.pc`) and not “libuv” (file `libuv.pc`). `libuv.pc` should be used for `include/libuv` and `lib/liblibuv.so`.
  - Are `AdvAPI32` and `User32` libraries really required for Windows? I was able to build libuv on Windows 10 without them.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
This is for the other maintainers to decide (I'm not too involved anymore) but we dropped support for gyp (another build system) earlier this year because the overhead of maintaining and testing scripts for three build systems was quite substantial.

A good answer to the question of "why not autotools or cmake?" might help get this landed.

**Comment by concatime** [comment]
As of c71570ea, these build successfully witih Meson 0.56.0:
 - Alpine Linux 3.12: https://builds.sr.ht/~iemaghni/job/373173
 - FreeBSD 11: https://builds.sr.ht/~iemaghni/job/373162
 - FreeBSD 12: https://builds.sr.ht/~iemaghni/job/373167
 - OpenBSD 6.8: https://builds.sr.ht/~iemaghni/job/373168

**Comment by bzoz** [comment]
@concatime  those libs are needed ([advapi](https://github.com/libuv/libuv/commit/335e8a6d128646e5a19d39dfc677f5a5a555f7cc) and [user]( https://github.com/libuv/libuv/blob/9c6cec803aad3564376cc598d6f7dafdcc26c0f9/src/win/winapi.c#L132)).

I'm generally -1 on adding another build system. There is only a handful of devs working on the project, adding one more thing to support won't help with that.

**Comment by cjihrig** [comment]
I'm also -1 to supporting another build system.

**Comment by concatime** [comment]
As you wish devs. How about an unofficial build system? Like [xxHash with CMake](https://github.com/Cyan4973/xxHash/tree/dev/cmake_unofficial).

**Comment by cjihrig** [comment]
That could live outside of the libuv repository. For example, Node.js still builds libuv with gyp, and that is maintained entirely in the Node repo.

**Comment by concatime** [comment]
As you wish @cjihrig. I will still maintain a repo.

**Pull request closed without merging**
