### PR TITLE
issue #2201: another strategy to gather descriptors to delete

### PR DESCRIPTION
**Pull request by icegood**

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Can you explain what this change does and why? If it's about performance, please post before and after numbers.

**Comment by icegood** [comment]
> Can you explain what this change does and why? If it's about performance, please post before and after numbers.

Hello. I've added benchmark poll_2k_ping_pongs that exactly describes issue. I run it via old and new versions within both release (-O3 -DNDEBUG) and 'release-with-debuginfo' configurations (-O2 -g -DNDEBUG)

and obtained next numbers :

26300-29600 roundtrips for version 'before'
27000-33000 roundtrips for version 'after'.


Besides if you run callgrind for a given benchmark in 'old' version , you will see crucial part of code with 98% of 'instruction reads'. 

Furthermore, it is possible to continue investigation by changing UV_LINUX_MAX_EVENTS_TO_LISTEN and UV_LINUX_EVENT_REPEAT_POLL_COUNT but i hasn't done it yet. 
All changes are applied currently for linux only, have no way to check how it will work on other systems.

**Comment by icegood** [comment]
related commit:
https://github.com/libuv/libuv/commit/bbccafbe704090e294481d95f73862bc83f33026
why do someone want to reopen other fd from callback at all?

**Comment by saghul** [comment]
I think the scenario is you might close a tcp handle in a prepare handle and create it again in some other handle's read callback for example. Not an explicit action, but an accidental one.

**Comment by icegood** [comment]
> I think the scenario is you might close a tcp handle in a prepare handle and create it again in some other handle's read callback for example. Not an explicit action, but an accidental one.

Seems given usecase is not relevant anymore.  We just remove manually 'bad' events from epoll's obtained ones, while more robust way is just deregister file descriptor from event poll that was added later in
https://github.com/libuv/libuv/commit/780d8ad8e58c675dc60f5b73ea22a203760da2f2. I mean, when 'prepare' is called the list removed_events (in my commit) or 'enevts' in older commits is garanteed to be empty. The only case when it is nonempty is when handle is closed from another 'poll' callback since this list is always reinitialized inside uv__io_poll. And latter one is a really weird use case. Why do someone wants to close fd from poll that belong to another fd? Now i vote instead of adding optimization is to just remove that 'events' array. And do not support such use cases anymore.

**Pull request closed without merging**
