### PR TITLE
Fix assert failure and memory leak for SOCKS5 proxy sample in issue #1604. Again.

### PR DESCRIPTION
**Pull request by ssrlive**
Now I commit it from many times for issue #1604.
I think you @bnoordhuis can understand the changes.

### CODE REVIEW

**Comment by ssrlive** [comment]
Hi dude @bnoordhuis . Is here anything went wrong?

**Comment by bnoordhuis** [comment]
I don't have time to do a full review right now but here are a few things I noticed:

1. Still lots of seemingly unrelated changes.  If you want to see this land, please make the diff as minimal as possible.
2. Commit logs don't conform to the house style.  Take a look at `git log`.  It's important that they explain _what_ changed and _why_.
3. Reference counting and peppering `if (client_is_dead(client)) return;` statements all over the place doesn't look Obviously Correct, that needs more explanation.

**Comment by ssrlive** [comment]
I have test it for a long time. All of the clients can released correctly. Not memory leaks anymore.

**Comment by getingskill** [comment]
Can you tell me the sock5 can run on windows? I don't make it, and hope you can help me?

**Comment by getingskill** [comment]
Can you tell me how to run the sock5 on windows?  I can't make it.  On windows I only recevice the message includeing 05 and 00.

**Comment by ssrlive** [comment]
@getingskill  https://github.com/ssrlive/s5proxy

**Pull request closed without merging**
