### PR TITLE
unix: fix pipe permission race condition

### PR DESCRIPTION
**Pull request by khardix**
File system bound socket permissions can only be queried or changed by
the high-level stat(2)/chmod(2) syscalls. However, by reusing the socket
file name between calls, there is a possibility of time-of-check,
time-of-use race condition.

In order to safely change the permission, the current file name must
be queried for each syscall separately.

Relevant issue: libuv#2040

---

This is my first time contribution to this codebase, so please bear with me in case of any mishaps ☺.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
> In order to safely change the permission, the current file name must be queried for each syscall separately.

Maybe I misunderstand but this PR doesn't seem to remove the race condition, just shorten the race window.

**Comment by khardix** [comment]
@bnoordhuis Well,  you are not wrong…

The trouble is that the only supported way of changing the permissions on socket file (that I'm aware of) *has* to use the filename-based syscalls. In that case, some race window is probably inevitable (and I would be very happy to be proven wrong in this matter).

This PR should prevent some issues (i.e. "copying" unintended permissions if the filename association changed between `stat`/`chmod`), but as mentioned above, is not bulletproof.

I could add the Linux-specific workaround mentioned in the original issue (opening `/proc/self/fd/$fd`) and try to remove the window altogether at least there.

**Comment by bnoordhuis** [comment]
Right. Yes, that's why I suggested using the procfs but after thinking about it some more, I'm not 100% positive procfs would help here either. I don't believe the changes to the procfs entry are going to be reflected on the pipe.

The only race-free solution I can think of is this:

1. parent: `fork()`
2. child: `umask(0777)`
3. child: `bind(...)`
4. child: `_exit()`
5. parent: `waitpid()`
6. File path now exists with the right mode.

Saying that's less than elegant is understating it, though.

**Comment by khardix** [comment]
Well, AFAIK you cannot rebind an already bound socket, so the above would not work either :disappointed:.

The root problem is to get a reference to the pipe/socket that a) cannot be changed while held (which FS path can), and b) allow querying AND management of file attributes (which pretty much rules out any file descriptor kind I was able to find, *in this specific case*).

I'll admit that I cannot think of anything else to try…

**Comment by vtjnash** [comment]
>  but that doesn't help against fork() calls from third-party code, of course

Nothing should happen anyways across a fork to any handles. I think you're thinking of O_CLOEXEC? There's no race condition in your pseudo-code for leaking it to a spawned process.

Another possible way to avoid the race would be to use `lchmod` here, where implemented (or  setattrlist or fchmodat, although in all cases, this is only implemented on the BSD's including macOS and not on linux).

Note, there was additional discussion of this at the time on the mailing list: https://groups.google.com/d/msg/libuv/b2aRcD0sMEs/rteNwt2aAwAJ

Closing this since the relevant issue was closed.

**Comment by bnoordhuis** [comment]
> Nothing should happen anyways across a fork to any handles. I think you're thinking of O_CLOEXEC?

No, I'm specifically talking about fork() since libuv kindof-ish supports that through `uv_loop_fork()`.

Another thread forking at an inopportune time gets a copy of that file descriptor. Then again, that's true of plenty of places inside libuv.

> Closing this since the relevant issue was closed.

I'll reopen #2040 because I do feel this is a rather severe defect in libuv, even if there is no easy fix.

**Pull request closed without merging**
