### PR TITLE
Several fixes for DragonFlyBSD

### PR DESCRIPTION
**Pull request by mneumann**
* nonblocking/cloexec supported on DragonFly
* sendfile(2) supported on DragonFly
* Bug fix for uv_exepath()!

### CODE REVIEW

**Comment by jbergstroem** [comment]
@mneumann how's the state of the test suite on dragonfly?

**Comment by saghul** [comment]
LGTM if it works :-) Can you please adjust your commit logs as per CONTRIBUTING.md? Thanks!

**Comment by bnoordhuis** [comment]
LGTM

**Comment by saghul** [comment]
Thanks! Landed in 94ba71b9eb67b22bb100cff3cb8775787a7126d2, db8c812a3dadc6e9ec51a8e9d35bc173b7c30b2c and c8eebc93a9efcdcc2913723ccd86b35498cc271f

**Pull request closed without merging**
