### PR TITLE
doc: update supported fields for uv_rusage_t

### PR DESCRIPTION
**Pull request by iWuzHere**
As discussed in issue #342

#### "CI"
 CI

#### Preview

preview1
---
preview2

### CODE REVIEW

**Comment by saghul** [comment]
LGTM

**Comment by iWuzHere** [comment]
Should I "Ref:" and close the issue or just use "Fixes:" (and also close the issue)?

**Comment by cjihrig** [comment]
LGTM. Since we'll be closing #342 via this PR, I'd say `Fixes:`

**Comment by iWuzHere** [comment]
Landed https://github.com/libuv/libuv/commit/30d852f9e0070c7334a8a5eae7a7b1bc38ad9050
Ended up using `Fixes:`

**Pull request closed without merging**
