### PR TITLE
Suggestions for CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by cpsw**
I would like to suggest to include some additional information on Code Style. This is a new direction towards avoiding certain patterns of code that might increase the changes of adding runtime errors, in my opinion. At the same time, I would invite others to share other patterns like these ones with goal of creating a set of guidelines that we could share among open-source projects.

### CODE REVIEW

**Comment by cjihrig** [comment]
Thanks for opening this. I have some reservations though:

- The code blocks are not written in the style used throughout the project.
- The point about the dangling `else` is actively discouraged in this project for single statement `if`-`else`s.
- We generally only include parentheses when needed.
- A section on how to write good code could probably grow unbounded.

**Comment by saghul** [comment]
Ideally we'd have some tool to do this, clang-tidy, for instance. Past efforts, have however been unfruitful. The approach we generally follow is "look at the code around you".

Something that puzzled me when reading this PR is that the commit message doesn't follow the guidelines which are written in the very document this PR modifies.

**Comment by davisjam** [comment]
> A section on how to write good code could probably grow unbounded.

Agreed. I dislike the direction this PR is suggesting. I don't think an exhaustive list of good coding practices is really appropriate for a file like `CONTRIBUTING.md`.

Books like [Code Complete](https://www.amazon.com/Code-Complete-Practical-Handbook-Construction/dp/0735619670) have done a nice job of codifying (if you'll excuse the pun) good coding practices.

I also wonder whether these suggestions are really needed for developers who feel comfortable contributing to a project like libuv.

> The approach we generally follow is "look at the code around you".

Right.

**Comment by davisjam** [comment]
> Ideally we'd have some tool to do this.

+1. Introducing linting tools would be a more productive angle for this PR.

**Comment by bnoordhuis** [comment]
OP didn't follow up and I wouldn't rule out the possibility of this being a bot PR (rude!) since identical pull requests were filed to other popular repos.

**Pull request closed without merging**
