### PR TITLE
illumos: event ports to epoll

### PR DESCRIPTION
**Pull request by tjarlama**
Replacing event ports with epoll for SUNOS.

Issue: #3008

### CODE REVIEW

**Review by bnoordhuis — APPROVED** [review]
LGTM at a quick glance, thanks!

**Comment by vtjnash** [comment]
CI: https://ci.nodejs.org/job/libuv-test-commit/2170/

**Comment by vtjnash** [comment]
Linking looks to be broken on smartos due to missing symbols. I think some functions must still be missing that need to be moved or linked?

**Comment by tjarlama** [comment]
@vtjnash Missed adding epoll.c for SUNOS in Makefile. Fixed in latest commit

**Comment by vtjnash** [comment]
CI: https://ci.nodejs.org/job/libuv-test-commit/2175

**Pull request merged**
