### PR TITLE
win,build: reuse dev-console env

### PR DESCRIPTION
**Pull request by refack**
Fixes https://github.com/libuv/libuv/pull/1415

### CODE REVIEW

**Comment by saghul** [comment]
I thought of doing that, but I think the SDK shoukld be used even if vcbuild.bat is run with vs2017.

**Comment by refack** [comment]
> I thought of doing that, but I think the SDK shoukld be used even if vcbuild.bat is run with vs2017.

That's a problem because the SDK console is incompatible with VS2017 so:
Setting up an SDK console -> calling `vbcuild vs2017` (that skips `vcvarsall`) would not work.

**Comment by refack** [comment]
> even if vcbuild.bat is run with vs2017.

I think the best we can do is use the new `sdk` arg:
```
d:\code\libuv$ "d:\bin\dev\VS\Microsoft Visual Studio 2017 Community\VC\Auxiliary\Build\vcvarsall.bat" -?
Syntax:
    vcvarsall.bat [arch]
  or
    vcvarsall.bat [arch] [version]
  or
    vcvarsall.bat [arch] [platform_type] [version]
where :
    [arch]: x86 | amd64 | x86_amd64 | x86_arm | x86_arm64 | amd64_x86 | amd64_arm | amd64_arm64
    [platform_type]: {empty} | store | uwp
    [version] : full Windows 10 SDK number (e.g. 10.0.10240.0) or "8.1" to use the Windows 8.1 SDK.

The store parameter sets environment variables to support Universal Windows Platform application
development and is an alias for 'uwp'.

For example:
    vcvarsall.bat x86_amd64
    vcvarsall.bat x86_amd64 10.0.10240.0
    vcvarsall.bat x86_arm uwp 10.0.10240.0
    vcvarsall.bat x86_arm onecore 10.0.10240.0
    vcvarsall.bat x64 8.1
    vcvarsall.bat x64 store 8.1

Please make sure either Visual Studio or C++ Build SKU is installed.
```

**Comment by saghul** [comment]
> That's a problem because the SDK console is incompatible with VS2017 so:
> Setting up an SDK console -> calling vbcuild vs2017 (that skips vcvarsall) would not work.

Why is that? If I'm on an SDK prompt and we skip all processing for any vs version, as we did before, why would it fail?

**Comment by refack** [comment]
> Why is that? If I'm on an SDK prompt and we skip all processing for any vs version, as we did before, why would it fail?

Ahh that why it would work, but it will ignore the `vs2017` arg. In `node`'s `vcbuild.bat` we do allot of dancing around to make sure we respect the args

**Comment by saghul** [comment]
So, I've been thinking about this some more. I think that the environment where the script is run should take more precedence.

Imagine I'm on the VS 2015 console and run the command with vs2017, for whatever reason. I'd say we should run in the 2015 console, because that's where we are. Same goes for the SDK. I like my fix better. Also, you could have commented on my PR instead of opening a new one ;-)

@libuv/collaborators WDYT?


-Saúl

**Comment by bzoz** [comment]
I think I would like it "the node way" of arg taking precedence.

**Comment by saghul** [comment]
Note that this is _not_ Node :-)

**Comment by bzoz** [comment]
I know :). I'm perfectly fine with either way.

**Comment by refack** [comment]
> Also, you could have commented on my PR instead of opening a new one ;-)

I was sure you pinged me for a solution, I didn't even notice it was a PR 🤣

**Pull request closed without merging**
