### PR TITLE
windows: fix non-symlink reparse points

### LINKED ISSUE #995: lstat on Windows fails for "Macintosh HD" network share
This was originally reported as https://github.com/nodejs/node/issues/5160. The impact as described there is that nodejs on Windows is unable to load script files from a "Macintosh HD" network share. (Spaces in the share name are actually irrelevant, despite the issue title.)

From debugging I found that the call to `DeviceIoControl(..., FSCTL_GET_REPARSE_POINT, ...)` in `fs__readlink_handle()` results in `ERROR_NOT_A_REPARSE_POINT` specifically for the "Macintosh HD" share, but not for any normal network shares. It appears the file handle has `FILE_ATTRIBUTE_REPARSE_POINT` set on it, but does not actually have any reparse data set for it.

While it's a bit of a corner case, we know it is impacting several users. I think the fix to `fs__stat_handle` will be straightforward: check for `ERROR_NOT_A_REPARSE_POINT` and in that case treat the file as if `FILE_ATTRIBUTE_REPARSE_POINT` was not there.

I'll submit a PR shortly.

### PR DESCRIPTION
**Pull request by wadetb**
Fixes uv_fs_stat and uv_fs_lstat returning EINVAL when invoked on a non-symlink reparse point.

1. Only tries to read symlinks when invoked via lstat (do_lstat == 1).

Rationale is that only lstat can set S_IFLNK because when a file is tested by stat, symlinks are resolved by the OS and the returned file must be real. Note that broken symlinks fail at CreateFile.

FILE_ATTRIBUTE_REPARSE_POINT is used by filesystem drivers for purposes besides symlinks, and uv_fs_stat fails when invoked on these files because fs__readlink_handle returns ERROR_SYMLINK_NOT_SUPPORTED. By ignoring the attribute in uv_fs_stat, these files are now handled correctly.

2. Modifies the logic added to fs__stat_handle to fix #995 as follows:

A failed fs__readlink_handle on a file with a reparse point indicates that the file is not a symlink. The fix for #995 added code to fall through and behave as with a normal file in this case. However, this is not correct because lstat had opened the file with FILE_FLAG_OPEN_REPARSE_POINT, preventing the filesystem from acting based on the reparse point contents.

The fix makes fs__stat_handle fail back to the higher level fs__stat_impl, which sets do_lstat to 0 and re-opens the file without FILE_FLAG_OPEN_REPARSE_POINT, allowing normal filesystem processing to take place.

This is also a slightly cleaner solution as symlink fallback is only handled in one place (fs__stat_impl) instead of two (fs__stat_impl and fs__stat_handle).

Note that the error tested in the fix for #995, ERROR_NOT_A_REPARSE_POINT, is not actually returned by Windows in the case of a non-symlink reparse point. I attempted to reproduce the error by repeating the test steps in the issue but failed. However, the the fix logic is preserved out of caution.

3. Adds tests to fs-test.c for the above two changes.

Thorough testing requires some non-trivial setup - like an OSX computer on the LAN or a custom filesystem driver - so these tests are left commented out for manual invocation.

### CODE REVIEW

**Comment by wadetb** [comment]
@jasongin @saghul

**Comment by wadetb** [comment]
For background, the bugs fixed by this PR are preventing Visual Studio Code (via libuv, via Node.js, via Electron) from seeing files in folders backed by an internally developed HSM (hierarchical storage management) similar to Microsoft's GVFS.

**Comment by saghul** [comment]
@wadetb Thanks! I'll take a look as soon as I have some time. In the meantime, can you please target this at v1.x? Or is the targetting to master intentional?

**Comment by wadetb** [comment]
Leaving this closed after some attempts to change the base in-place, see #1522 for the v1.x version.

**Pull request closed without merging**
