### PR TITLE
unix,win: fix `uv_fs_poll_stop()` when active

### PR DESCRIPTION
**Pull request by addaleax**
Fix `uv_fs_poll_stop()` for active handles by not attempting to
mark the `uv_fs_poll_t` handle as closing when `uv_close()`
hasn’t been called on it.

Fixes: https://github.com/libuv/libuv/issues/2287
Refs: https://github.com/libuv/libuv/pull/1875

### CODE REVIEW

**Comment by sgallagher** [comment]
Note: this differs from `--koji --simple` in that it doesn't execute _any_ of the koji-style merge logic. It was considerably harder to conditionalize that, so I opted for it to be its own separate flag. If `--koji` is passed, it ends up being a proper superset of this functionality, so that simply takes precedence.

**Comment by sgallagher** [comment]
Deleted previous comment. Pasted into wrong github tab.

Patch seems good by inspection. I'm putting it into our testing environment in Fedora to see if it shakes anything out.

**Comment by remicollet** [comment]
I confirm this fix https://github.com/bwoebi/php-uv/issues/66

**Comment by santigimeno** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1381/

**Comment by bnoordhuis** [comment]
Thanks Anna, landed in 6c760b62.

**Pull request closed without merging**
