### PR TITLE
fix msvc warning

### PR DESCRIPTION
**Pull request by sidyhe**

### CODE REVIEW

**Comment by santigimeno** [comment]
Wasn't an issue in older windows versions initializing variables on declaration?

**Comment by refack** [comment]
> Wasn't an issue in older windows versions initializing variables on declaration?

Mentioned in https://github.com/libuv/libuv/pull/2066#issuecomment-439832953
IIUC it was fixed after MSVS 2008 which is 5 years past it's EOL.

**Comment by bnoordhuis** [comment]
> IIUC it was fixed after MSVS 2008 which is 5 years past it's EOL.

The background here is that we want libuv to be usable by python modules and python 2.7 is [forever wedded to msvs 2008](https://mail.python.org/pipermail/python-dev/2012-August/121412.html).

I don't think this particular change would break msvs 2008 but, you know, it's been a while since I last actively used it.

**Comment by refack** [comment]
> The background here is that we want libuv to be usable by python modules and python 2.7 is [forever wedded to msvs 2008](https://mail.python.org/pipermail/python-dev/2012-August/121412.html).

Ohh yeah, that's a PITA... but https://pythonclock.org/.
I'll give it a test, I have the [`Python Development Tools`](https://visualstudio.microsoft.com/vs/features/python/) installed.
(Maybe also add the CI - https://github.com/nodejs/build/issues/1581)

**Comment by refack** [comment]
Well, with this PR the lib builds on "Microsoft Visual C++ Compiler for Python 2.7" (a.k.a MSVS 2008)
x86 - 0 warnings - http://node.refack.com/uv/BuildLogx32.htm
x64 - the usual bunch of warnings - http://node.refack.com/uv/BuildLogx64.htm

The test suite not so much:
```
D:\code\4node\libuv\test>"D:\refael\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\vcbuild.exe" test.sln
Microsoft (R) Visual C++ Project Builder - Command Line Version 9.00.30729
Copyright (C) Microsoft Corporation. All rights reserved.

Build started: Project: run-tests, Configuration: Release|Win32
Compiling...
test-poll.c
run-tests.c
.\test-poll.c(140) : error C2065: 'ECONNRESET' : undeclared identifier
.\run-tests.c(146) : error C2143: syntax error : missing ';' before 'type'
.\run-tests.c(147) : error C2065: 'bytes' : undeclared identifier
Build log was saved at "file://d:\code\4node\libuv\test\Release\obj\run-tests\BuildLog.htm"
run-tests - 3 error(s), 0 warning(s)
```

After hacking out the syntax errors:
```
Build started: Project: run-tests, Configuration: Release|Win32
Linking...
libuv.lib(pipe.obj) : error LNK2001: unresolved external symbol __imp__SetEntriesInAclA@16
libuv.lib(pipe.obj) : error LNK2001: unresolved external symbol __imp__GetSecurityInfo@32
libuv.lib(pipe.obj) : error LNK2001: unresolved external symbol __imp__AllocateAndInitializeSid@44
libuv.lib(pipe.obj) : error LNK2001: unresolved external symbol __imp__SetSecurityInfo@28
libuv.lib(pipe.obj) : error LNK2001: unresolved external symbol __imp__FreeSid@4
libuv.lib(util.obj) : error LNK2001: unresolved external symbol __imp__OpenProcessToken@12
libuv.lib(util.obj) : error LNK2001: unresolved external symbol __imp__GetUserNameW@8
libuv.lib(util.obj) : error LNK2001: unresolved external symbol __imp__RegQueryValueExW@24
libuv.lib(util.obj) : error LNK2001: unresolved external symbol __imp__RegOpenKeyExW@20
libuv.lib(util.obj) : error LNK2001: unresolved external symbol __imp__RegCloseKey@4
libuv.lib(fs.obj) : error LNK2001: unresolved external symbol __imp__CryptReleaseContext@8
libuv.lib(fs.obj) : error LNK2001: unresolved external symbol __imp__CryptAcquireContextA@20
libuv.lib(fs.obj) : error LNK2001: unresolved external symbol __imp__CryptGenRandom@12
D:\code\4node\libuv\test\Release\\run-tests.exe : fatal error LNK1120: 13 unresolved externals
Build log was saved at "file://d:\code\4node\libuv\test\Release\obj\run-tests\BuildLog.htm"
run-tests - 14 error(s), 0 warning(s)
```

**Comment by vtjnash** [comment]
> Wasn't an issue in older windows versions initializing variables on declaration?

I think you could always do constexpr initialization (such as struct initialization with `= {0, NULL, 'c', 3}`), the pre-C99 standards disallowed mixing code (such as `= {a_var}`) with declarations.

**Comment by refack** [comment]
> I think you could always do constexpr initialization

👍 
FTR https://en.cppreference.com/w/c/language/array_initialization concurs:
```
comma-separated list of constant (until C99) expressions that are initializers for array elements
```

**Comment by bnoordhuis** [comment]
> This means we need to keep GYP support for VS2008 as well.

Not necessarily. pyuv for example has its own distutils-based build script, it doesn't use gyp, autotools or cmake at all.

**Comment by refack** [comment]
> Not necessarily.

And there's also semver semantics...
<sub>I'm planing to call the new version GYP3 mainly since [gyp3.org](https://gyp3.org) was free, while the owner of gyp.org wanted $11,000</sub>

**Comment by vtjnash** [comment]
> x64 - the usual bunch of warnings

Looking through a few of these, they are also potentially indicative of problems on posix platforms too (since many of those code-paths are on the API boundary, and are often related to #1501), but this particular warning is usually not enabled in gcc. We can, however, get a similar list from `make CFLAGS='-Wconversion'`

**Comment by cjihrig** [comment]
The warning in `src/win/fs-event.c` was already addressed in https://github.com/libuv/libuv/commit/c5593b51dc98715f7f32a919301b5801ebf1a8ce. I also split up the declarations and assignments in `src/win/tty.c`.

CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1171/
Landed in https://github.com/libuv/libuv/commit/f84c5e693b80cb0c62bcefba147e7a66e2b839c9.

Thanks!

**Pull request closed without merging**
