### PR TITLE
fs: undo uv__req_init when uv__malloc failed

### PR DESCRIPTION
**Pull request by yjhjstz**
see #541

### CODE REVIEW

**Comment by saghul** [comment]
LGTM :+1:

**Comment by skomski** [comment]
one missing: https://github.com/yjhjstz/libuv/blob/v1.x-req-uninit/src/unix/fs.c#L1070

**Comment by saghul** [comment]
Good catch!

**Comment by yjhjstz** [comment]
yes, update, thanks @skomski

**Comment by saghul** [comment]
Landed in 0199955, thanks!

**Comment by Parakleta** [comment]
The changes in the region 1000-1300 are not correct because they are not gated by the condition that `cb != NULL`.  Rather than spreading this logic so far through the file consider making an `ABORT(x)` macro which is called in lieu of `POST` when aborting and which contains the required logic to undo `INIT` and `return x;`.  This macro could then also be called from `PATH` and `PATH2`.

**Comment by bnoordhuis** [comment]
https://github.com/libuv/libuv/pull/567

**Pull request closed without merging**
