### PR TITLE
test: fix fs_fsstat on Android

### PR DESCRIPTION
**Pull request by baremetalfreak**
Fixes: https://github.com/libuv/libuv/issues/1051

### CODE REVIEW

**Comment by cjihrig** [comment]
LGTM with a comment, although I have no way of testing if this actually fixes the problem.

**Comment by saghul** [comment]
LGTM

**Comment by baremetalfreak** [comment]
Sorry, will fix.

Dne neděle 18. září 2016 Colin Ihrig <notifications@github.com> napsal(a):

**Comment by cjihrig** [comment]
Sorry, I left that comment yesterday but had forgotten to actually open my review, so it was sitting there "pending."

**Comment by swat-cat** [comment]
Thank you for your help. Issue could be closed.

**Comment by saghul** [comment]
I fixed the extra semicolon while adding the metadata.  Landed in ✨  fa81a1b ✨ 

Thanks a lot for taking this up Vit!  For posterity, this was tackled at Node Interactive "Code and Learn". ❤️

**Pull request closed without merging**
