### PR TITLE
Revert "threadpool: send signal only when queue is empty"

### PR DESCRIPTION
**Pull request by krrishnarraj**
This reverts commit 0f1bdb6b131fffc27baa570b9e8cbc985c4b46f4.

this commit introduced a bug in threadpool
signal always needs to be sent, otherwise idle threads
wont be able to receive new incoming job

### CODE REVIEW

**Comment by saghul** [comment]
Do you have a test case demonstrating the failure / regression?

**Comment by krrishnarraj** [comment]
Added a test case to check for imbalance in threadpool. Currently this case fails randomly
https://github.com/libuv/libuv/commit/0f1bdb6b131fffc27baa570b9e8cbc985c4b46f4 introduced the bug

*Tested only on linux

**Comment by saghul** [comment]
@krrishnarraj Thanks for writing the test! Now, I'm not 100% sure the test assumptions are correct. There cannot be "perferct" scheduling, it might even depend on the characteristics of the hardware, if the kernel pinned each thread to a CPU and so on.

@bnoordhuis WDYT?

**Comment by krrishnarraj** [comment]
Kernel might not pin each thread to a cpu, that's why we are not calculating total time taken.

Before even first job is queued, init_once() creates 4(or N) threads. So we need to make sure that 4 jobs with sufficient load(of 1 sec) gets assigned(which is in our control) to 4 different threads

**Comment by bnoordhuis** [comment]
@krrishnarraj Are you hitting a deadlock or is the problem that the work items are not evenly distributed across threads (in general, not just in the test)?

**Comment by saghul** [comment]
@bnoordhuis I think he means in general. I did some testing: https://gist.github.com/92cfbad1fa9596f95f90

Then checked the results by running:

~~~~
UV_THREADPOOL_SIZE=8 ./a.out > out.txt
cat out.txt | sort | uniq -c
~~~~

With the current code I don't get full threadpool usage (2 out of 4 and 3 out of 8, generally), whereas when I revert the patch (applying this PR), it's evenly balanced.

Sigh.

**Comment by krrishnarraj** [comment]
@saghul yep. I had a similar test-case to visualize it

@bnoordhuis its not a deadlock, rather threads are not signaled properly when new job has arrived. Since call to uv_cond_signal() was made conditional, idle threads wont receive the signal and non-idle threads end-up doing extra work

**Comment by krrishnarraj** [comment]
Even I am not 100% convinced with the test-case, seemed like this is the only way to expose the bug.
Need to check it on windows and other low-end systems

**Comment by chenttuuvv** [comment]
@saghul  @krrishnarraj you're right, this patch was cherrypicked from an concurent queue implementation that should have only one cousumer. On busy system, some threads may starve, but sending signal too often may hurt performance on the other hand. Those who care about performance, should add some pacing logic here, if threadpool is in high load. I have an in-house patch that do this work,and will upstream this patch soon.

**Comment by saghul** [comment]
> Even I am not 100% convinced with the test-case, seemed like this is the only way to expose the bug.
> Need to check it on windows and other low-end systems

The patch won't work on Windows, since `uv_thread_t` is not an `int`.

**Comment by bnoordhuis** [comment]
Had a quick look and it seems like an obvious bug in retrospect.  I think this patch should fix it:

```diff
diff --git a/src/threadpool.c b/src/threadpool.c
index dd0abd9..15d7199 100644
--- a/src/threadpool.c
+++ b/src/threadpool.c
@@ -44,6 +44,7 @@ static void uv__req_init(uv_loop_t* loop,
 static uv_once_t once = UV_ONCE_INIT;
 static uv_cond_t cond;
 static uv_mutex_t mutex;
+static unsigned int idle_threads;
 static unsigned int nthreads;
 static uv_thread_t* threads;
 static uv_thread_t default_threads[4];
@@ -69,8 +70,11 @@ static void worker(void* arg) {
   for (;;) {
     uv_mutex_lock(&mutex);
 
-    while (QUEUE_EMPTY(&wq))
+    while (QUEUE_EMPTY(&wq)) {
+      idle_threads += 1;
       uv_cond_wait(&cond, &mutex);
+      idle_threads -= 1;
+    }
 
     q = QUEUE_HEAD(&wq);
 
@@ -101,11 +105,9 @@ static void worker(void* arg) {
 
 
 static void post(QUEUE* q) {
-  int empty_queue;
   uv_mutex_lock(&mutex);
-  empty_queue = QUEUE_EMPTY(&wq);
   QUEUE_INSERT_TAIL(&wq, q);
-  if (empty_queue)
+  if (idle_threads > 0)
     uv_cond_signal(&cond);
   uv_mutex_unlock(&mutex);
 }
```

**Comment by saghul** [comment]
@bnoordhuis looks good, I'll give it a shot later today.

**Comment by saghul** [comment]
Just gave it a quick try and it does indeed solve the problem. Can you PR it? (I can do it for you if you're busy)

**Comment by bnoordhuis** [comment]
I'm about to head out but I'll file a PR later today.

**Comment by saghul** [comment]
Thanks a ton Ben!

**Comment by zhaozg** [comment]
waiting for accept the PR.

**Comment by bnoordhuis** [comment]
Fixed by da42780.

**Pull request closed without merging**
