### PR TITLE
test: make threadpool_cancel_single deterministic

### PR DESCRIPTION
**Pull request by bnoordhuis**
Saturate the thread pool before trying to post-and-cancel the work
request.  Before this commit we simply posted requests in a loop,
in the (sometimes idle) hope that one would get queued up instead
of being dispatched right away.

Refs: https://github.com/libuv/libuv/pull/1010
CI: https://ci.nodejs.org/job/libuv-test-commit/109/

R=@saghul

### CODE REVIEW

**Comment by saghul** [comment]
We already have something which other tests use to saturate the pool: https://github.com/libuv/libuv/blob/v1.x/test/test-threadpool-cancel.c#L69 maybe reuse that?

**Comment by bnoordhuis** [comment]
My follow-up plan is to replace saturate_threadpool() with something that mimics this PR because the current implementation is not very robust.  I can add it to this PR if you want.

**Comment by saghul** [comment]
@bnoordhuis since you're there... :-) let's do it on this one.

**Comment by bnoordhuis** [comment]
Updated, PTAL.  Note the rather nice +26 −83.

CI: https://ci.nodejs.org/job/libuv-test-commit/110/

**Comment by saghul** [comment]
Damn you Windows!

~~~~
not ok 275 - threadpool_cancel_single
# Output from process `threadpool_cancel_single`: (no output)
~~~~

I'll give it a go tonight on a native machine, see if I can reproduce it and see where it fails exactly.

**Comment by saghul** [comment]
LGTM. I'll investigate the Windows flaky thing more, the failure might be somewhere else.

> Note the rather nice +26 −83.

Excellent!

**Comment by bnoordhuis** [comment]
Did you get a chance to look at the Windows failure?  threadpool_cancel_single is flaky on Windows with and without this change so I guess it's not really a regression.

**Comment by saghul** [comment]
It's on my TODO list, but I haven't gotten to it yet. Feel free to land this one, it's correct on its own.

**Pull request merged**
