### PR TITLE
win: drop support for windows 8

### PR DESCRIPTION
**Pull request by bnoordhuis**
Fixes: https://github.com/libuv/libuv/issues/3889

<hr>

There's probably more that can be simplified now. Suggestions?

### CODE REVIEW

**Comment by bnoordhuis** [comment]
I don't get why GetFileInformationByName is undefined... is that not a thing on Windows Server 2019/2022?

**Review by saghul — APPROVED** [review]

**Comment by vtjnash** [comment]
GetFileInformationByName was added last year

**Comment by bnoordhuis** [comment]
Okay, so not safe to assume it's there, even on win10?

**Comment by vtjnash** [comment]
Right, officially it isn't even part of Windows 11 yet (https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getfileinformationbyname)

**Comment by huseyinacacak-janea** [comment]
The `GetFileInformationByName` function was introduced to libuv as part of [this PR](https://github.com/libuv/libuv/pull/4327). If I am not wrong, this API became available starting with [Windows 11, version 24H2](https://blogs.windows.com/windowsexperience/2024/10/01/how-to-get-new-experiences-for-windows-11/). Therefore, it’s not safe to assume that it will be present on all Windows 10 systems. Additionally, this API is available in Windows Server 2025 but not sure in Server 2019 and 2022.

**Review by saghul — APPROVED** [review]
At a quick glance I don't see anything else.

**Comment by Streamlet** [comment]
Why drop support Win8?
Is there an API that provided by Win10 and MUST be used?

**Comment by saghul** [comment]
Read here: https://github.com/libuv/libuv/issues/3889

**Comment by Streamlet** [comment]
> Read here: #3889

EOL is not a sufficient reason for a software to "abandon" a system. I mean, intentionally making the software fail to run or crash on that system.

I think you can reduce official efforts on Windows 8, for example, by cutting back on testing investment and only fixing major bugs.

But do not intentionally stop support or casually use new APIs from Windows 10 unless they bring significant benefits.

This way, compatibility with pre-Windows 10 systems can be maintained. Community developers will also fix bugs for Windows 8, and you can merge their PRs.

**Comment by Streamlet** [comment]
Moreover, I consider Chromium's abandonment of pre-Windows 10 systems to be unethical—similar to how Wintel alliance manufacturers refuse to provide drivers for pre-Windows 10. There are no essential new APIs in Windows 10 that must be relied upon (and if there were, the old APIs could be emulated). Chromium's abandonment of pre-Windows 10 indirectly leads to a series of software, such as Node, Electron, and VSCode, also abandoning pre-Windows 10. For example, while we can still use VSCode 1.79 on Windows 8.1, its Copilot plugin has started to malfunction due to changes in HTTP API parameters. The newer version of the Copilot plugin could support it, but it requires a newer version of VSCode, which in turn requires newer versions of Node and Electron, and thus Windows 10. These dependencies are unnecessarily heavy. Windows 10 is an unethical system, filled with telemetry and leaving users with no real control over it. Every Windows 10 machine could be considered a zombie computer. Many people have already awakened to this, and Supermium is an excellent project in this regard. Chromium is influenced by Google, and commercial companies have their own interests, which is understandable. However, I believe community-driven projects like Node (including libuv) and Electron could make some small efforts, similar to Supermium, to maintain compatibility with pre-Windows 10 and help improve this ecosystem.

**Comment by bnoordhuis** [comment]
Locked, deleted an off-topic comment, and hid the other. Save diatribes for your personal blog.

**Pull request merged**
