### PR TITLE
avoid a race condition in canceling the pipe_zero_readfile

### PR DESCRIPTION
**Pull request by vtjnash**
Unsurprisingly, synchronizing threads is hard. This was a mistake in 837c62c that I've been sitting on for too long (trying now to start back-porting fixes from our Julia fork into upstream here).

### CODE REVIEW

**Comment by vtjnash** [comment]
Refs: joyent/libuv#1377

**Comment by vtjnash** [comment]
bump.

**Comment by vtjnash** [comment]
bumpity bump bump.

**Comment by saghul** [comment]
LGTM. @bzoz mind taking another look please?

**Comment by bzoz** [comment]
LGTM!

CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/282/

**Comment by santigimeno** [comment]
New CI before merging: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/298/

@vtjnash would you mind squashing the commits and format the commit message following these [instructions](https://github.com/libuv/libuv/blob/master/CONTRIBUTING.md#commit)?. Thanks!

**Comment by vtjnash** [comment]
updated.

**Comment by santigimeno** [comment]
Landed in .https://github.com/libuv/libuv/commit/c42a4ca372b8476c78c026cab856694830735490 Thanks!

**Pull request closed without merging**
