### PR TITLE
Revert "unix,stream: clear read/write states on close/eof"

### PR DESCRIPTION
**Pull request by cjihrig**
This reverts commit 12be29f185261b8a7e6ada596fd805919cb2b133.

The commit in question was introducing failures in the Node.js
test suite.

Refs: https://github.com/libuv/libuv/issues/2943
Refs: https://github.com/libuv/libuv/pull/2967

### CODE REVIEW

**Review by santigimeno — APPROVED** [review]

**Review by bnoordhuis — APPROVED** [review]
You beat me to it by 30 seconds: bnoordhuis/libuv@a9d8cf1 :-)

**Comment by cjihrig** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/2018/
Node.js+libuv integration CI: https://ci.nodejs.org/view/libuv/job/libuv-in-node/160/

**Comment by cjihrig** [comment]
CI seems fine other than what appears to be infra related issues on Windows. I'm going to land this now.

**Comment by cjihrig** [comment]
Landed in https://github.com/libuv/libuv/commit/46f36e3df1a666620f6749427f15651cbc4b7001.

**Pull request closed without merging**
