### PR TITLE
build: workaround AppVeyor quirk

### PR DESCRIPTION
**Pull request by refack**

### CODE REVIEW

**Comment by cjihrig** [comment]
Shouldn't have any impact at all, but CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/315/

**Comment by refack** [comment]
Comment in http://help.appveyor.com/discussions/problems/7023-a-seemingly-noop-change-to-bat-file-causes-build-to-fail

**Comment by cjihrig** [comment]
Landed in https://github.com/libuv/libuv/commit/87ae1b490e4eea8544e6a03882151e789830cf4d. Thanks for getting this turned around quickly @refack.

**Comment by refack** [comment]
> Landed in 87ae1b4. Thanks for getting this turned around quickly @refack.

I actually feel bad it took that long 🤷‍♂️

**Pull request closed without merging**
