### PR TITLE
unix: unused-function uv__fs_preadv on BSD

### PR DESCRIPTION
**Pull request by ktrongnhan**
Jenkins build:  https://ci.nodejs.org/job/libuv-test-commit-freebsd/1412/nodes=freebsd11-x64/console

### CODE REVIEW

**Comment by cjihrig** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1489/

It looks like there are some failures to be addressed.

**Comment by ktrongnhan** [comment]
@cjihrig,
I have corrected the directive. Could we run it again?

**Comment by cjihrig** [comment]
Sure. CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1500/

**Comment by cjihrig** [comment]
Landed in https://github.com/libuv/libuv/commit/b144695014a33c871ad100c2b9545c10460f2458. Thanks!

**Pull request closed without merging**
