### PR TITLE
doc: add Imran Iqbal (iWuzHere) to maintainers

### PR DESCRIPTION
**Pull request by iWuzHere**
Adding myself to maintainers!

### CODE REVIEW

**Comment by saghul** [comment]
LGTM, welcome onboard!

**Comment by cjihrig** [comment]
LGTM 🎉

**Comment by iWuzHere** [comment]
Landed https://github.com/libuv/libuv/commit/deb7432c6e6f4856ade2308b50d7647db9c88c43

**Comment by cjihrig** [comment]
The commit is missing the PR metadata. You can amend it and force push quickly.

**Comment by iWuzHere** [comment]
Thanks for catch! Fixed it. Still new to this! :disappointed_relieved:

**Comment by cjihrig** [comment]
No problem at all :-)

**Pull request merged**
