### PR TITLE
fix sendfile usage in uv_fs_copyfile 

### PR DESCRIPTION
**Pull request by fdopen**
`sendfile` doesn't necessarily copy all data from source to destination. It's possible that the process receives a signal or similar things happen during the copying. In this case `sendfile` will return less than `statsbuf.st_size`, but not `-1`. And at least on linux it will also copy at most  0x7ffff000 bytes at each call.

Quote from `man 2 sendfile`:

> If  the transfer was successful, the number of bytes written to out_fd is returned.  Note that a successful call to sendfile() **may write fewer bytes than requested**; the caller should be prepared to retry the call if there were unsent bytes.

Things I didn't touch, because they are unrelated to the problem, but still looks dubious to me:
1) All calls to `uv_fs_req_cleanup` are unnecessary.
2) Passing `req->loop` as first parameter is misleading. `req->loop` shouldn't be touch inside a work thread, passing `NULL` instead of `req->loop` would be less confusing.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
cc @cjihrig - the `req->loop` usage indeed looks wrong.

**Comment by cjihrig** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/413/

Seemed mostly good.

**Comment by cjihrig** [comment]
@santigimeno do you want to land this as is? If you think we need to handle things differently on linux, you could submit a follow up PR.

**Comment by cjihrig** [comment]
Word on the street is that this fixes #1517.

**Comment by cjihrig** [comment]
All green CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/436/ 💚

**Comment by cjihrig** [comment]
Landed in https://github.com/libuv/libuv/commit/dff7ebe4f0bac1fdbcd6dec9eec72882597c78ca. Thanks!

**Comment by santigimeno** [comment]
Sorry for the late response.
I think adding a test in `test-fs-copyfile.c` copying a large file would be nice. If the test takes too long the `TEST_ENTRY_CUSTOM` macro with a expanded timeout could be used.

**Comment by santigimeno** [comment]
Oh, I see you already landed. I'll try to submit a PR with the test.

**Comment by cjihrig** [comment]
Sorry @santigimeno... we just missed each other on this one :-)

FWIW, there is a test for a larger file already, but it's not huge because of timeout issues. If you want to handle that, that would great.

**Pull request closed without merging**
