### PR TITLE
src: fix formatting issue in win/util.c

### PR DESCRIPTION
**Pull request by bl-ue**

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Review by RaisinTen — COMMENTED** [review]
Here is a list of `while`s that don't have a space before the `(`. Should we fix those in this PR itself?
```
src/unix/aix.c:617:  while(n > 0) {
src/unix/android-ifaddrs.c:210:    while(p_list)
src/unix/android-ifaddrs.c:235:    while(!l_done)
src/unix/android-ifaddrs.c:316:        while(l_cur->ifa_next)
src/unix/android-ifaddrs.c:428:    while(l_cur && l_num < p_numLinks)
src/unix/android-ifaddrs.c:707:    while(ifa)
src/win/fs.c:113:  } while(0)
src/win/req-inl.h:101:    } while(current != loop->pending_reqs_tail);
src/win/util.c:377:    } while( Process32Next(handle, &pe));
```

**Comment by bl-ue** [comment]
Indeed, it seems like there's no formatting guide or linter:
```c
src/win/util.c:    } while( Process32Next(handle, &pe));
src/win/req-inl.h:    } while(current != loop->pending_reqs_tail);
src/win/core.c:    if(IsDebuggerPresent())
src/win/fs.c:  } while(0)
src/win/process.c:    } else if(source[i - 1] == L'"') {
include/uv/tree.h:      if(__comp < 0) {                                                        \
src/unix/aix.c:  for(vmt = p, i = 0; i < rv; i++) {
src/unix/aix.c:  while(n > 0) {
src/unix/aix.c:  for(i = 0; i < PATH_MAX; i++) {
src/unix/aix.c:  if(bytes == 0)
src/unix/aix.c:  if(bytes > 0)
src/unix/aix.c:  if(loop->backend_fd >= 0)
src/unix/android-ifaddrs.c:    if(l_socket < 0)
src/unix/android-ifaddrs.c:    if(bind(l_socket, (struct sockaddr *)&l_addr, sizeof(l_addr)) < 0)
src/unix/android-ifaddrs.c:    if(getsockname(l_socket, (struct sockaddr *)&l_addr, &l_len) < 0)
src/unix/android-ifaddrs.c:    for(;;)
src/unix/android-ifaddrs.c:        if(l_result < 0)
src/unix/android-ifaddrs.c:            if(errno == EINTR)
src/unix/android-ifaddrs.c:        if(l_msg.msg_flags & MSG_TRUNC)
src/unix/android-ifaddrs.c:    for(;;)
src/unix/android-ifaddrs.c:        if(l_read == -2)
src/unix/android-ifaddrs.c:        if(l_read >= 0)
src/unix/android-ifaddrs.c:            for(l_hdr = (struct nlmsghdr *)l_buffer; NLMSG_OK(l_hdr, (unsigned int)l_read); l_hdr = (struct nlmsghdr *)NLMSG_NEXT(l_hdr, l_read))
src/unix/android-ifaddrs.c:                if((pid_t)l_hdr->nlmsg_pid != p_pid || (int)l_hdr->nlmsg_seq != p_socket)
src/unix/android-ifaddrs.c:                if(l_hdr->nlmsg_type == NLMSG_DONE)
src/unix/android-ifaddrs.c:                if(l_hdr->nlmsg_type == NLMSG_ERROR)
src/unix/android-ifaddrs.c:    while(p_list)
src/unix/android-ifaddrs.c:    if(netlink_send(p_socket, p_request) < 0)
src/unix/android-ifaddrs.c:    while(!l_done)
src/unix/android-ifaddrs.c:        if(!l_hdr)
src/unix/android-ifaddrs.c:        if(!l_list)
src/unix/android-ifaddrs.c:    if(!*p_resultList)
src/unix/android-ifaddrs.c:        while(l_cur->ifa_next)
src/unix/android-ifaddrs.c:    for(l_rta = IFLA_RTA(l_info); RTA_OK(l_rta, l_rtaSize); l_rta = RTA_NEXT(l_rta, l_rtaSize))
src/unix/android-ifaddrs.c:    for(l_rta = IFLA_RTA(l_info); RTA_OK(l_rta, l_rtaSize); l_rta = RTA_NEXT(l_rta, l_rtaSize))
src/unix/android-ifaddrs.c:                if(l_rta->rta_type == IFLA_ADDRESS)
src/unix/android-ifaddrs.c:    while(l_cur && l_num < p_numLinks)
src/unix/android-ifaddrs.c:        if(l_index == p_index)
src/unix/android-ifaddrs.c:    for(l_rta = IFA_RTA(l_info); RTA_OK(l_rta, l_rtaSize); l_rta = RTA_NEXT(l_rta, l_rtaSize))
src/unix/android-ifaddrs.c:        if(l_info->ifa_family == AF_PACKET)
src/unix/android-ifaddrs.c:                if((l_info->ifa_family == AF_INET || l_info->ifa_family == AF_INET6) && !l_addedNetmask)
src/unix/android-ifaddrs.c:    if(l_interface)
src/unix/android-ifaddrs.c:    for(l_rta = IFA_RTA(l_info); RTA_OK(l_rta, l_rtaSize); l_rta = RTA_NEXT(l_rta, l_rtaSize))
src/unix/android-ifaddrs.c:                if(l_info->ifa_family == AF_INET6)
src/unix/android-ifaddrs.c:                    if(IN6_IS_ADDR_LINKLOCAL((struct in6_addr *)l_rtaData) || IN6_IS_ADDR_MC_LINKLOCAL((struct in6_addr *)l_rtaData))
src/unix/android-ifaddrs.c:                if(l_rta->rta_type == IFA_ADDRESS)
src/unix/android-ifaddrs.c:                    if(l_entry->ifa_addr)
src/unix/android-ifaddrs.c:                else if(l_rta->rta_type == IFA_LOCAL)
src/unix/android-ifaddrs.c:                    if(l_entry->ifa_addr)
src/unix/android-ifaddrs.c:    if(l_entry->ifa_addr && (l_entry->ifa_addr->sa_family == AF_INET || l_entry->ifa_addr->sa_family == AF_INET6))
src/unix/android-ifaddrs.c:        for(i=0; i<(l_prefix/8); ++i)
src/unix/android-ifaddrs.c:        if(l_prefix % 8)
src/unix/android-ifaddrs.c:    for(; p_netlinkList; p_netlinkList = p_netlinkList->m_next)
src/unix/android-ifaddrs.c:        for(l_hdr = p_netlinkList->m_data; NLMSG_OK(l_hdr, l_nlsize); l_hdr = NLMSG_NEXT(l_hdr, l_nlsize))
src/unix/android-ifaddrs.c:            if((pid_t)l_hdr->nlmsg_pid != p_pid || (int)l_hdr->nlmsg_seq != p_socket)
src/unix/android-ifaddrs.c:            if(l_hdr->nlmsg_type == NLMSG_DONE)
src/unix/android-ifaddrs.c:            if(l_hdr->nlmsg_type == RTM_NEWLINK)
src/unix/android-ifaddrs.c:                if(interpretLink(l_hdr, p_resultList) == -1)
src/unix/android-ifaddrs.c:    for(; p_netlinkList; p_netlinkList = p_netlinkList->m_next)
src/unix/android-ifaddrs.c:        for(l_hdr = p_netlinkList->m_data; NLMSG_OK(l_hdr, l_nlsize); l_hdr = NLMSG_NEXT(l_hdr, l_nlsize))
src/unix/android-ifaddrs.c:            if((pid_t)l_hdr->nlmsg_pid != p_pid || (int)l_hdr->nlmsg_seq != p_socket)
src/unix/android-ifaddrs.c:            if(l_hdr->nlmsg_type == NLMSG_DONE)
src/unix/android-ifaddrs.c:            if(l_hdr->nlmsg_type == RTM_NEWADDR)
src/unix/android-ifaddrs.c:    if(!ifap)
src/unix/android-ifaddrs.c:    if(l_socket < 0)
src/unix/android-ifaddrs.c:    if(!l_linkResults)
src/unix/android-ifaddrs.c:    if(!l_addrResults)
src/unix/android-ifaddrs.c:    if(l_numLinks == -1 || interpretAddrs(l_socket, l_pid, l_addrResults, ifap, l_numLinks) == -1)
src/unix/android-ifaddrs.c:    while(ifa)
test/test-tty-duplicate-key.c:    if(!is_wsl &&
docs/code/idle-basic/main.c:void wait_for_a_while(uv_idle_t* handle) {
```

**Comment by vtjnash** [comment]
Sure, if you have that list, would you like to update this PR with those nits fixed? Something like `sed -i -e 's/\(for|if|while\)(/\1 (/'` (if I can type a regex correctly from memory)

**Comment by bl-ue** [comment]
Sure, I'll fix all the formattgin! :)

**Comment by vtjnash** [comment]
bump?

**Pull request closed without merging**
