### PR TITLE
change uv_pipe_connect signature

### PR DESCRIPTION
**Pull request by txdv**
# fixes 1063

### CODE REVIEW

**Comment by saghul** [comment]
Thanks! Are you going to incorporate the other changes discussed in #1063 ? Also, docs + tests please! :-)

**Comment by txdv** [comment]
Yes, I'm doing everything in small commits as usual.

**Comment by saghul** [comment]
No problemo.  Give a should when it's ready for review.

**Comment by cjihrig** [comment]
@txdv are you still planning to work on this?

**Comment by txdv** [comment]
afair on windows it returns some error code for some error immediately when on linux it returns on the callback or vice versa, this would just break stuff

**Pull request closed without merging**
