### PR TITLE
add uv_device_t as stream on windows and Linux to handle device IO

### PR DESCRIPTION
**Pull request by zhaozg**

### CODE REVIEW

**Comment by fivdi** [comment]
Will there be node bindings for calling the new functions like `uv_device_ioctl`?

**Comment by saghul** [comment]
> Will there be node bindings for calling the new functions like uv_device_ioctl?

That's up to Node, this is libuv.

**Comment by trevnorris** [comment]
Mind adding something to `docs/`? :)

**Comment by creationix** [comment]
Sorry for showing my ignorance, but is rs232 the kind of serial protocol used to talk to things like arduinos?

Also for what it's worth, chrome apps have had s serial API for some time that's used by various apps to talk to hardware devices. https://developer.chrome.com/apps/serial

**Comment by saghul** [comment]
@creationix Thanks for the link, I'll take a look. Hopefully now that 1.7 is out I can review this thorougly soon.

Currently this patch only exposes the minimum components for device communication: opening, reading, writing and a generic ioctl mechanism, applications would use platform specific ioctls to change parameters such as baud rate. Note that this can also be used to open devices such as /dev/tun.

**Comment by creationix** [comment]
Right, I see use in both a low-level system interface that require users to write platform specific code and a cross-platform high-level serial interface that is less capable, but works cross-platform for a specific use case.

I've gone down this road before with luvit and the problem with just exposing ioctl when pairing libuv with a scripting language is that the scripting language doesn't have access to system headers (macros and constants) to know which ioctls to use.

**Comment by creationix** [comment]
Maybe the burden of the cross-platform ioctl part should live between libuv and the scripting language (luvi in my case).  Libuv would provide the minimal bits to call ioctls on uv device streams and the C code using it would be responsible for the rest.  But the API exposed to the scripting language would look more like the chrome.serial API.

**Comment by saghul** [comment]
> Maybe the burden of the cross-platform ioctl part should live between libuv and the scripting language (luvi in my case). Libuv would provide the minimal bits to call ioctls on uv device streams and the C code using it would be responsible for the rest. But the API exposed to the scripting language would look more like the chrome.serial API.

This sounds like a good idea to me!

**Comment by creationix** [comment]
It would be really cool if there was a collection of libuv addons that handled this in a generic way independent of the vm being used.  Then node, pyuv and luvit can share the serial module that lives between libuv and the vm.

**Comment by zhaozg** [comment]
sorry for close this, because I need to keep step with v1.x, so I create a branch for device at https://github.com/zhaozg/libuv/tree/device

**Comment by dtex** [comment]
Now #484

**Pull request closed without merging**
