### PR TITLE
unix,win: share loop watchers implementation

### PR DESCRIPTION
**Pull request by saghul**
/cc @libuv/collaborators 

CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/85/

### CODE REVIEW

**Comment by txdv** [comment]
Can you run a jekins-test-run against master, so I can check compare the errors and figure out what errors are new?

**Comment by saghul** [comment]
@txdv https://ci.nodejs.org/view/libuv/job/libuv-test-commit/85/ that one runs on master + this patch. Is that what you were asking?

**Comment by txdv** [comment]
I want you to run one on master without this patch.

**Comment by saghul** [comment]
This patch didn't change anything, but here is a run anyway: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/86/

**Comment by bnoordhuis** [comment]
LGTM

**Pull request merged**
