### PR TITLE
add android build to CI

### PR DESCRIPTION
**Pull request by gengjiawen**
Fix https://github.com/libuv/libuv/issues/2855

### CODE REVIEW

**Comment by gengjiawen** [comment]
A little off the topic. Looks cmake is better than gn if we decide switch Node.js build system.

**Comment by cjihrig** [comment]
Do you intend to run the test suite, or just build libuv on Android?

**Comment by gengjiawen** [comment]
> Do you intend to run the test suite, or just build libuv on Android?

Maybe not for now. 

If we decide run the test, I am afraid we may have to add sample android project to repo to trigger android E2E test. Also run android emulator on CI system won't be easy, especially google not put time on it IMHO.

**Comment by cjihrig** [comment]
OK, that's fair enough. Building the project is better than what we currently offer 😄

**Comment by bnoordhuis** [comment]
Aside, the build-cross-qemu-armhf failure is this:
```
 not ok 216 - signal_multiple_loops
# exit code 139
# Output from process `signal_multiple_loops`:
# corrupted size vs. prev_size
```
Which indicates memory corruption (clobbering a malloc control block) but I have no idea whether it's legitimate or not. qemu's signal emulation code is notoriously tricky and, historically, buggy.

**Comment by gengjiawen** [comment]
> Aside, the build-cross-qemu-armhf failure is this:
> 
> ```
>  not ok 216 - signal_multiple_loops
> # exit code 139
> # Output from process `signal_multiple_loops`:
> # corrupted size vs. prev_size
> ```
> 
> Which indicates memory corruption (clobbering a malloc control block) but I have no idea whether it's legitimate or not. qemu's signal emulation code is notoriously tricky and, historically, buggy.

I open a pr yesterday in https://github.com/libuv/libuv/pull/2860.

**Comment by gengjiawen** [comment]
@cjihrig Can you merge this one too ?

**Comment by cjihrig** [comment]
Landed in https://github.com/libuv/libuv/commit/93c90191b6c3ffb5ccaf437f69d1107fb5ed287f. Thanks!

**Pull request closed without merging**
