### PR TITLE
WIP: Windows: remove LSP support

### PR DESCRIPTION
**Pull request by saghul**
I started to work on this a while ago but forgot about it, so I'm opening the PR so I don't forget again.

Current status: LSP support is removed.
What's left: Use WSASocket and pass the correct WSAPROTOCOL_INFO structure in order to select the correct AFD provider.

@libuv/collaborators @joaocgreis @joshgav please feel free to review the work so far.

> Showing with 97 additions and 404 deletions. 

Hell yeah!

### CODE REVIEW

**Comment by iWuzHere** [comment]
>Showing with 97 additions and 404 deletions.

**Comment by cjihrig** [comment]
@saghul do you want to keep this open?

**Comment by saghul** [comment]
Yes please, I hope to be back to it soon (I promise). But I wonder if we should re-target to v1.x.

**Comment by cjihrig** [comment]
> But I wonder if we should re-target to v1.x.

I'd say yes if you want it to ever be included in a release 😄

**Comment by vtjnash** [comment]
I'll reiterate my worry that this will reduce the reliability of libuv, although I'll admit it's been a couple (~3) years since I've worked with a client who needed this code (https://github.com/libuv/libuv/issues/972#issuecomment-329530936)

**Pull request closed without merging**
