### PR TITLE
win: fix unsavory rwlock fallback implementation

### PR DESCRIPTION
**Pull request by saghul**
Before this patch an uv_mutex_t (backed by a critical section) could be
released by a tread different from the thread that acquired it, which is
not allowed. This is fixed by using a semaphore instead.

Note that the affected code paths were used on Windows XP and Windows
Server 2003 only.

This is a back-port of commits 3eb6764, 1ad6ad7, 9a4fd26, 9823922
85adf43 and bd1777f from the v1.x branch.

Fixes: https://github.com/libuv/libuv/issues/515
Refs: https://github.com/libuv/libuv/pull/525

### CODE REVIEW

**Comment by saghul** [comment]
Windows XP "CI"
Imgur

Some tests fail (as thy were before) but the added one passes.

**Comment by saghul** [comment]
Newer Windows CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit-windows/73/

**Comment by saghul** [comment]
Notes: I had to backport https://github.com/libuv/libuv/pull/535 as well, to make the test pass. The test was also adapted because in 0.10 we returned -1 not real errors.

/cc @bnoordhuis @piscisaureus @rvagg

**Comment by saghul** [comment]
Windows 7 results:

~~~~
[%  96|+ 182|-   7|T   1|S   0]: thread_mutex
[%  96|+ 183|-   7|T   1|S   0]: thread_rwlock
[%  97|+ 184|-   7|T   1|S   0]: thread_rwlock_trylock
~~~~

As far as I'm concerned, we are good to go.

**Comment by bnoordhuis** [comment]
LGTM at a quick glance.

**Comment by piscisaureus** [comment]
LGTM

**Pull request merged**
