### PR TITLE
gitignore: ignore VSCode setting files

### PR DESCRIPTION
**Pull request by nk-yohn3301**
I'm developing in VSCode.
I want to ignore .vscode settings, What do you think?

### CODE REVIEW

**Comment by saghul** [comment]
@libuv/collaborators WDYT? I'm kinda -0.

**Comment by santigimeno** [comment]
Yeah, I'm not against it either.

**Comment by bnoordhuis** [comment]
It's opening the floodgates though.  We landed a similar PR in nodejs/node a while ago and within days we had a pile-up of PRs for other editors.  Accept one, gotta accept 'em all.

I'm personally of the opinion that people should configure it through their global .gitconfig.  That's what it's for.

**Comment by saghul** [comment]
Yeah, I saw that PR... let's not do that here.

**Comment by nk-yohn3301** [comment]
I am sorry the selfish PR.
Regret deeply.
Thank you for telling me.

**Comment by saghul** [comment]
@nk-yohn3301 no worries :-) It's just hard to please everyone...

**Comment by nk-yohn3301** [comment]
@saghul Thanks a lot.

**Pull request closed without merging**
