### PR TITLE
Disable clang C99 variable length array warning.

### PR DESCRIPTION
**Pull request by PeterJohnson**

### CODE REVIEW

**Comment by bnoordhuis** [comment]
For my curiosity, is it the `char cmsg_space[CMSG_SPACE(UV__CMSG_FD_SIZE)]` declaration it's complaining about?

That is _supposed_ to be a constant-time expression but isn't on macos, IIRC, for reasons I don't RC.

**Comment by PeterJohnson** [comment]
Yes, that's what it's complaining about, and yes, it appears to only be an issue on MacOS.

**Comment by cjihrig** [comment]
The CI failures are unrelated.

**Comment by cjihrig** [comment]
Landed in https://github.com/libuv/libuv/commit/ec69500bdd1be1e2abda7727b8560ea03739230a. Thanks!

**Pull request closed without merging**
