### PR TITLE
win,test: fix shared library build

### PR DESCRIPTION
**Pull request by saghul**
Ifdef out the tests that rely on internal symbols when making a shared build.

R=@piscisaureus

### CODE REVIEW

**Comment by saghul** [comment]
Hold, I think I got a thing wrong here.

**Comment by saghul** [comment]
Now it's ready for review. CI: https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/121/ (the CI doesn't do shared builds, but it serves as regression testing).

Also /cc @bnoordhuis maybe you can also help review :-)

**Comment by bnoordhuis** [comment]
LGTM, I suppose.

**Comment by saghul** [comment]
Thanks Ben! FTR, what the patch does is define USING_UV_SHARED when building the run-tests and run-benchmarks targets, iff libuv was built as a shared library. That define is already in use by us: https://github.com/libuv/libuv/blob/v1.x/include/uv.h#L35 and by projects using libuv as a shared library: https://github.com/nodejs/io.js/blob/master/src/node.h#L18

So I ifdef-ed out the tests that use internal symbols, using that define.

**Comment by saghul** [comment]
I tested this and works fine, so in it went! :-)

**Pull request merged**
