### PR TITLE
unix: fix -Wstrict-aliasing compiler warning

### PR DESCRIPTION
**Pull request by bnoordhuis**
Fixes: #2563
CI: https://ci.nodejs.org/job/libuv-test-commit/1655/

The second commit is an optimization that I'm happy to leave out.

### CODE REVIEW

**Comment by saghul** [comment]
I like the optimization :-)

**Comment by bnoordhuis** [comment]
Fix-up for z/os (no RTLD_DEFAULT). New CI: https://ci.nodejs.org/job/libuv-test-commit/1656/

**Comment by saghul** [comment]
Oh crap. Does this mean that the 1.34 release is bust on z/OS? Sorry about that! I guess we need a .1 release after this one lands then? cc @cjihrig

**Comment by bnoordhuis** [comment]
Don't worry, I think it was saved by the O_CLOEXEC guard (which also doesn't exist on z/os.)

**Pull request closed without merging**
