### PR TITLE
win: use GetQueuedCompletionStatusEx directly

### PR DESCRIPTION
**Pull request by saghul**
It was introduced in Vista, so we can assume it's always there now.

### CODE REVIEW

**Comment by saghul** [comment]
I think we could remove a couple of similar indirections... I'll take a look and send more PRs if we can remove similar code.

**Review by vtjnash — CHANGES_REQUESTED** [review]
It is absent from wine (hence why this function is named wine, not old)

**Comment by saghul** [comment]
Oh I thought you he name was odd indeed but hadn't made the connection.

Do we support that? It's not listed as a supported platform.

**Comment by saghul** [comment]
Looks like it was fixed in Wine 3.21? https://bugs.winehq.org/show_bug.cgi?id=43878

**Comment by bnoordhuis** [comment]
> Do we support that? It's not listed as a supported platform.

I test under Wine more frequently than under real Windows. Make of that what you will. :-)

I do believe this was fixed upstream. I'll try to test this PR later today.

**Review by bnoordhuis — APPROVED** [review]
Tested, works!

**Review by santigimeno — APPROVED** [review]

**Comment by bnoordhuis** [comment]
Yes, but... that doesn't really matter because we don't support Wine in the first place, right? Anyone can still have their Wine, it just needs to be new enough.

(I was working my way up to a Beaujolais joke but I don't want to cause any sour grapes.)

**Comment by saghul** [comment]
Yeah, I echo the sentiment with @bnoordhuis here. We do still uphold the Linux support promises we make in SUPPORTED_PLATFORMS. Wine is... different.

I'd be surprised if someone is using such an old distro while at the same time using an app with the latest libuv, that means they compiled it themselves or is part of a new application. They can install a more recent Wine.

**Comment by bnoordhuis** [comment]
@vtjnash Ping, your thoughts?

**Comment by vtjnash** [comment]
Wine is often a very useful debugging platform, since it can have better debuggers (particularly rr), compilers, and source code. That said, most of my development machines are supposed to be upgraded soon as 18.04 is close to end-of-life, and I often have wine built from source somewhere around. That said, the older wine that this would break does come as part of the linux in the SUPPORTED_PLATFORMS list. And by that argument, someone using such an old distro could also "just install" a more recent distro.

That said, it also looks like this PR would probably break ReactOS which appears to still declare GetQueuedCompletionStatusEx as a stub

And note that this reverts 153ea114fff672b9c621a5d2bb13cea667b4499e, just for the historical link (from prior to this API existing in wine at all)

**Comment by thynson** [comment]
Ubuntu 18.04 will be EOL soon. Probably it's time to merge this?

**Comment by saghul** [comment]
Hello, it's almost 2025! I see no obstacles for this PR to land now, are they? Ubuntu 18.04 has been EOL for over a year now. @vtjnash can you PTAL?

**Review by vtjnash — APPROVED** [review]

**Comment by bnoordhuis** [comment]
Reading this back after 2 years...

> (I was working my way up to a Beaujolais joke but I don't want to cause any sour grapes.)

...can we all agree that was a terrific pun?

**Comment by saghul** [comment]
10/10 banter :-P

**Pull request merged**
