### PR TITLE
doc: move cjihrig back to active maintainers

### PR DESCRIPTION
**Pull request by cjihrig**
If you will have me, of course.

### CODE REVIEW

**Review by santigimeno — APPROVED** [review]
Happy to have you back!

**Review by richardlau — APPROVED** [review]

**Review by saghul — APPROVED** [review]
Welcome back Colin!

**Review by bnoordhuis — APPROVED** [review]
Welcome back, of course :)

**Comment by cjihrig** [comment]
Thanks everyone!

**Pull request merged**
