### PR TITLE
fs: uv_fs_{open,read,close}_dir

### LINKED ISSUE #170: fs: uv_fs_{open,read,close}_dir (or whatever is necessary for a streaming fs.readdir() in node)
i'd like https://github.com/iojs/io.js/issues/583. seems like it requires https://github.com/joyent/libuv/pull/1574, but i don't see that as a PR int his repo.

you can close this if this is already in. can't really help with a PR in C++ land. just a feature request :)

### PR DESCRIPTION
**Pull request by misterdjules**
This is the same changes as joyent/libuv#1574.
This commit is just the start of getting them to work in libuv/libuv.

Failing tests will be fixed asap.

Fixes #170.

### CODE REVIEW

**Comment by misterdjules** [comment]
I should be able to fix the failing tests today or this week-end. I just wanted to have this PR up asap so I'm not blocking anyone from discussing it.

**Comment by misterdjules** [comment]
Also, it's likely that the implementation could use [the recent work from @piscisaureus](https://github.com/libuv/libuv/commit/0729ce8b3936a44987bc76641a8dc43723ba065a), but I haven't had time to look at it yet.

**Comment by misterdjules** [comment]
Copied verbatim from https://github.com/joyent/libuv/pull/1574#issuecomment-62498798:

There are still a few of things that are unclear or missing:

As @saghul mentioned: Regardless of the API accepting a single entry or an array of them, space for the name needs to be allocated, maybe have an extra function to help with that?. Do we want something similar to handles' allocation callback?

Regarding @piscisaureus's comment about GetFileAttributesW/FindFirstFileW being inherently racey, using only FindFirstFileW on an entry that is not a directory would return UV_ENOENT, which I find a bit counter-intuitive and inconsistent. @piscisaureus: before looking into the approach you recommended ("Open the directory, Use GetFileInformationByHandle to read the attributes. Bail out and close if it's not a directory, otherwise start enumerating entries (using a different call).", I'd like to make sure I understood it correctly. Do you mean that we could use CreateFile first, then GetFileInformationByHandle to check if it's a directory, and then use lower-level APIs (not FindFirstFile/FindNextFile) to iterate through all entries of the HANDLE returned by CreateFile? It seems to be quite more complicated than using FindFirstFile/FindNextFile, but it could be because I'm not familiar with these others lower-level APIs.

Regarding the following question: "What happens if we create 2 readdir requests for the same directory? On Unix we should be fine because we'd use readdir_r, but how about windows?", I've done some research to determine how to answer this question, but I'm not done yet.

Currently, all tests pass on all supported platforms. I've also done a lot of tests with directories containing more than 1 million entries, and the memory footprint stays constant and low.

Hopefully this is a step in the right direction!

**Comment by piscisaureus** [comment]
> Regarding @piscisaureus's comment about GetFileAttributesW/FindFirstFileW being inherently racey, using only FindFirstFileW on an entry that is not a directory would return UV_ENOENT, which I find a bit counter-intuitive and inconsistent. @piscisaureus: before looking into the approach you recommended ("Open the directory, Use GetFileInformationByHandle to read the attributes. Bail out and close if it's not a directory, otherwise start enumerating entries (using a different call).", I'd like to make sure I understood it correctly. Do you mean that we could use CreateFile first, then GetFileInformationByHandle to check if it's a directory, and then use lower-level APIs (not FindFirstFile/FindNextFile) to iterate through all entries of the HANDLE returned by CreateFile? It seems to be quite more complicated than using FindFirstFile/FindNextFile, but it could be because I'm not familiar with these others lower-level APIs.

The windows implementation has already changed significantly, it no longer uses Find*File. See https://github.com/libuv/libuv/commit/0729ce8b3936a44987bc76641a8dc43723ba065a.

> Regarding the following question: "What happens if we create 2 readdir requests for the same directory? On Unix we should be fine because we'd use readdir_r, but how about windows?", I've done some research to determine how to answer this question, but I'm not done yet.

It's not an issue on windows either.

**Comment by misterdjules** [comment]
Just a heads-up that I haven't had the time to work on this due to other priorities in joyent/node. It's in the higher priorities in my todo list, just not the top one. Today I don't know when I'll have time to work on it, so please feel free to move forward with this if you have more time than I do.

The things that need to be done are:
* Fix `fs_readdir_non_empty_dir` that fails sometimes due to what seems to be a race between cleanup up a request and calling the callback for this request.
* Maybe reuse [some of the changes that have been made to uv_fs_scandir for Windows](https://github.com/libuv/libuv/commit/0729ce8b3936a44987bc76641a8dc43723ba065a) to implement `uv_fs_readdir`.

Thanks!

**Comment by saghul** [comment]
@misterdjules I'm quite swamped right now, and given that this breaks the ABI we can only land it in master, so no rush.

**Comment by Fishrock123** [comment]
Will anyone have a chance to begin working on this again?

Iirc this is required for io.js to eventually have a streaming fs.readdir - https://github.com/nodejs/io.js/issues/583

**Comment by saghul** [comment]
@Fishrock123 I don't think I will, in the short term.

Yes, it is required for Node to have a (real) streaming fs.readdir. Now, as I mentioned here https://github.com/libuv/libuv/pull/175#issuecomment-75016655 this breaks the ABI so it will have to land in master and in libuv 2.0.

**Comment by misterdjules** [comment]
@whitlockjc The failing test that I mentioned in [one of my previous comments](https://github.com/libuv/libuv/pull/175#issuecomment-74916201) fails only on Linux.

**Comment by whitlockjc** [comment]
Thanks for the heads up.  I was wondering why I couldn't reproduce this on OS X.  ;)  Preparing VM now...

**Comment by whitlockjc** [comment]
I've got a quick status update for this.  I was unable to reproduce the failing tests.  I tested with OSX 10.10.3, Ubuntu 12.04 (32-bit) and Ubuntu 12.04 (64-bit).  Below is the process I followed and the Vagrantfile I used to help streamline the process.

**Vagrantfile**

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "ubuntu-32", primary: true do |ubuntu|
    config.vm.box = "hashicorp/precise32"
  end

  config.vm.define "ubuntu-64" do |ubuntu|
    config.vm.box = "hashicorp/precise64"
  end

  # VirtualBox configuration
  config.vm.provider "virtualbox" do |vbox|
    vbox.memory = 2048
  end

  # Disable the Vagrant share due to weird FS issues (Makes sense to dev/test on "native disk" in my opinion anyways)
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Update apt-get and install dependencies
  config.vm.provision "shell", inline: "apt-get -y update && apt-get -y install automake build-essential git libtool"
end
```

**Recipe**

This part is only required for the Ubuntu testing
```
# Start VM
vagrant up [ubuntu-32|ubuntu-64]

# SSH to VM
vagrant ssh [ubuntu-32|ubuntu-64]
```

These are the steps I ran on all OSes.

```
# Clone sources
git clone https://github.com/libuv/libuv.git

# Change directory
cd libuv

# Update .git/config per https://gist.github.com/piscisaureus/3342247

# Pull down PRs
git fetch

# Checkout PR 175
git checkout pr/175

# Build
./autogen.sh
./configure
make
make check

# Run loop of tests for at least one minute
(while true; do ./test/run-tests fs_readdir_non_empty_dir; done)
```

**Comment by whitlockjc** [comment]
Unless instructed otherwise, I will begin the work of taking @saghul's suggestion and updating @misterdjules' work to be against `master` instead of `v1.x`.

**Comment by misterdjules** [comment]
@whitlockjc Excellent, thank you :+1: I still haven't had the time to investigate the `fs_readdir_non_empty_dir` failure that I see on Linux. Anyway, it's probably better for me to wait for this to be rebased on top of master and then test it again and see if I can reproduce that problem.

**Comment by misterdjules** [comment]
Closing in favor of #416, as @whitlockjc is currently leading this effort. Thank you so much @whitlockjc :+1:

**Pull request closed without merging**
