### PR TITLE
build: Get AppVeyor to test on VS2017

### PR DESCRIPTION
**Pull request by refack**
Also some tweaks to script

Could also be used for official release when a `tag` is pushed to repo

### CODE REVIEW

**Comment by saghul** [comment]
@libuv/collaborators do we want / need this? what versions are we going to distribute binaries for then? (FWIW we said these are experimental so... 🤷‍♂️ )

**Comment by bnoordhuis** [comment]
@bzoz You might have an opinion on this.

**Comment by bzoz** [comment]
I have zero experience with AppVeyor, but if it works, then why not?

**Comment by cjihrig** [comment]
@refack this needs a rebase (or to be closed out).

**Comment by cjihrig** [comment]
Closing due to inactivity.

**Pull request closed without merging**
