### PR TITLE
win: don't use inline keyword in thread.c

### PR DESCRIPTION
**Pull request by bnoordhuis**
The reported bug is arguably a compiler bug - a non-static inline
function should be inlined inside the compilation unit but still
have external linkage - but the abundant use of 'inline' isn't
really necessary in the first place.  Remove it.

Fixes: https://github.com/libuv/libuv/issues/191

R=@piscisaureus

### CODE REVIEW

**Comment by bnoordhuis** [comment]
https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/64/

**Comment by saghul** [comment]
Any specific reason why `uv__once_inner` was marked as no-inline?

**Comment by bnoordhuis** [comment]
No idea, I can't find a reason for it.  Looks like @piscisaureus is the original author: f790b689.

**Comment by piscisaureus** [comment]
You're right; this `inline` can just go and so can many others (primarily in `fs.js`).
In the past I was a bit too zealous about inlining things.

**Comment by saghul** [comment]
Kewl! LGTM then Ben!

**Pull request merged**
