### PR TITLE
win,build: proper appveyor workaround

### PR DESCRIPTION
**Pull request by refack**
Ref: https://github.com/appveyor/ci/issues/1649

### CODE REVIEW

**Comment by refack** [comment]
https://ci.appveyor.com/project/refack/libuv/build/v1.13.1.build51
I noticed it doesn't run the test suite. I'm assuming you do that on Jenkins?

**Comment by cjihrig** [comment]
Correct.

**Comment by cjihrig** [comment]
Quick sanity CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/344/

**Comment by cjihrig** [comment]
Landed in https://github.com/libuv/libuv/commit/8807fd371db6ae81a57cf06af5c2a8c32a578019. Thanks.

**Pull request closed without merging**
