### PR TITLE
unix,win: add uv_thread_timedjoin()

### PR DESCRIPTION
**Pull request by res0nance**
Add a new timed thread join function

### CODE REVIEW

**Review by bnoordhuis — COMMENTED** [review]
Thanks for the pull request but I don't think we can merge this without macOS support (which indeed doesn't have anything like pthread_timedjoin_np to the best of my knowledge.)

A secondary issue is that pthread_timedjoin_np (on both linux and freebsd) use a real-time clock whereas WaitForSingleObject is monotonic.

**Comment by res0nance** [comment]
> Thanks for the pull request but I don't think we can merge this without macOS support (which indeed doesn't have anything like pthread_timedjoin_np to the best of my knowledge.)
> 
> A secondary issue is that pthread_timedjoin_np (on both linux and freebsd) use a real-time clock whereas WaitForSingleObject is monotonic.

It doesn't and I don't think there is any way to emulate it given the current implementation with pthreads. If this is not mergeable without MacOS support I'll close this. Thanks for taking a look

**Comment by vtjnash** [comment]
The macos name is spelled kqueue :)

**Comment by res0nance** [comment]
> The macos name is spelled kqueue :)

I'm not very familiar with kqueue, but upon reading. I don't see how this can be implemented even with kqueue

**Comment by vtjnash** [comment]
hm, I was thinking it would be handled like a process, but looking back, I can't see any claim that this would work
```
int kq = kqueue();
struct kevent_qos_s kev;
EV_SET64(&kev, EVFILT_PROC, NOTE_EXIT, pthread_self());
kevent64(kq, &change, 1, &change, 1, 0, &timeout);
close(kq);
```

**Pull request closed without merging**
