### PR TITLE
tty: fix build for SmartOS

### PR DESCRIPTION
**Pull request by misterdjules**
On Solaris derivatives, cfmakeraw is not available. Instead, set the
termios flags manually. The set of flags to use so that the behavior of
the terminal is similar to what it is after a call to cfmakeraw was
taken from
http://www.perkin.org.uk/posts/solaris-portability-cfmakeraw.html.

### CODE REVIEW

**Comment by saghul** [comment]
LGTM. @bnoordhuis another pair of eyes?

**Comment by bnoordhuis** [comment]
LGTM

**Comment by saghul** [comment]
Thanks Julien! Landed in 672b204

**Comment by misterdjules** [comment]
Thanks @saghul and @bnoordhuis!

**Pull request closed without merging**
