### PR TITLE
unix: fix linux freemem wrong value

### PR DESCRIPTION
**Pull request by AHgPuK**

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Can you motivate why you think MemAvailable is more correct than MemFree?

**Comment by AHgPuK** [comment]
> Can you motivate why you think MemAvailable is more correct than MemFree?

https://github.com/nodejs/node/issues/23892
https://stackoverflow.com/questions/51911849/node-js-os-freemem-do-not-work-correctly

In short, MemFree shows total memory minus apps minus cache minus buffers.
Cache and buffers are used by the system and not related to the real memory usage.
MemAvailable  is strict total memory minus apps

**Review by vtjnash — APPROVED** [review]
This sounds like the right change to me, per that description. The MemFree number is hopefully always near zero, since the kernel hopefully uses all unused memory to cache data whenever it can, while the MemFree number actually reflects how much memory pressure there is before hitting swap is necessary (though the kernel is likely to hit swap sooner than when MemAvailable reaches zero, to avoid evicting hot cache memory).

**Review by bnoordhuis — APPROVED** [review]
I'm okay with this change (in another project I deliberately picked `MemAvailable` for the reasons you outline) but I'd appreciate it if you amend the commit log to explain the reason.

(Commit logs should explain what and why, not just what.)

**Review by santigimeno — APPROVED** [review]

**Comment by bnoordhuis** [comment]
One regrettable consequence of this change is that the return value depends on whether procfs is mounted. Libuv falls back to the sysinfo() system call when `/proc/meminfo` is unavailable.

MemFree == sysinfo().freeram but there's no MemAvailable equivalent.

**Comment by vtjnash** [comment]
I think it is reasonable to assume that this value is only a lower bound on the free memory (subject to TOCTOU constraints as well), though agree the discrepancy is a bit annoying. Though users could parse /proc/meminfo manually if they were implementing `htop`-like tools and wanted that clarity.

**Comment by bnoordhuis** [comment]
Okay, no objections from my side then.

@AHgPuK Can you update the commit log? Thanks.

**Comment by Hypfer** [comment]
As mentioned in https://github.com/nodejs/node/issues/23892, please note that `MemAvailable` requires at least Kernel 3.14

This could cause some breakage

**Pull request merged**
