### PR TITLE
Check for NULL in uv_os_unsetenv for parameter name

### PR DESCRIPTION
**Pull request by misery**
* Fixes segfault of unit test on musl (AlpineLinux)
* Add a check for parameter like uv_os_setenv do

### CODE REVIEW

**Comment by cjihrig** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/319/

**Comment by santigimeno** [comment]
> This was in the original implementation, but was removed (see #1234 (comment)).

Again, that was me. Sorry about that. LGTM

**Comment by bnoordhuis** [comment]
Not to go all language lawyer but isn't this basically a bug in musl?  POSIX in its 2001 and 2008 incarnations is quite clear that NULL should return EINVAL.  Perhaps this is best reported to musl.

**Comment by misery** [comment]
I will ask musl team...

https://gist.github.com/misery/5b3804f7dd29ebfdcf5492671a57df4c

**Comment by bnoordhuis** [comment]
Don't forget to move the strlen() call to after the NULL check. :-)

**Comment by cjihrig** [comment]
@santigimeno Don't worry about it. You were in the right :-)

@bnoordhuis are you OK with this landing despite it not being a bug in libuv?

**Comment by misery** [comment]
musl team says: it's not a bug ;-)

http://pubs.opengroup.org/onlinepubs/009695399/functions/unsetenv.html

chatlog:
```
[23:45:58] <newbie|4> Hi there... musl segfaults here on "unsetenv(NULL)" ... looks like a bug for me.
[23:47:01] <newbie|4> this should fix it: https://gist.github.com/misery/5b3804f7dd29ebfdcf5492671a57df4c
[23:47:47] <newbie|4> found with: https://github.com/libuv/libuv/pull/1409
[23:49:25] <@dalias> it's a bug to pass null to the function
[23:49:39] <@dalias> judging from the git history, it looks like posix used to specify an error for passing a null arg to setenv
[23:49:49] <@dalias> (commit 649af9f73a84aa45742324d44384a873c8709915)
[23:50:54] <amonakov> neither posix nor linux-manpages say that unsetenv is supposed to accept null pointers
[23:50:57] <@dalias> any idea if unsetenv had the same historic behavior? it's not specified for either in current posix
[23:51:13] <@dalias> the commit i quoted claims posix said EINVAL on null arg
[23:51:25] <@dalias> so maybe it was in posix 2008 original and a TC removed it?
[23:51:40] iscaro [~iscaro@177.102.240.231] hat den Server verlassen: Quit: Leaving
[23:51:57] <@dalias> issue 6 had it
[23:52:06] <amonakov> setenv != unsetenv
[23:52:08] <@dalias> and issue 6 also had it for unsetenv
[23:52:10] <@dalias> http://pubs.opengroup.org/onlinepubs/009695399/functions/unsetenv.html
[23:52:11] <feepbot> unsetenv
[23:52:29] <@dalias> so that's a fairly good argument for accepting it and producing the error i guess
[23:53:00] <amonakov> btw my setenv overhaul totally fell through the cracks
[23:54:01] <@dalias> i know
[23:54:08] <@dalias> this actually just reminded me of that again
[23:54:29] <@dalias> are there other patches you're waiting for me to commit or review, or am i waiting for something new from you?
[23:55:29] <nsz> re unsetenv: http://austingroupbugs.net/view.php?id=185
[23:55:31] <feepbot> 0000185: setenv failure case - Austin Group Defect Tracker
[23:55:44] <nsz> it was changed because historical bsd behaviour is to crash on null
[23:55:54] <amonakov> it was a 3-patch patchset, I asked for a decision if 2/3+3/3 are wanted at all, because 1/3 needs to be rebased to be resubmitted
[23:55:55] <nsz> so it's better if libuv fixes their code
[23:57:16] <newbie|4> but POSIX is clear: The name argument is a null pointer, points to an empty string, or points to a string containing an '=' character.
[23:58:45] <@dalias> newbie|4, that's an obsolete version of posix. but i think it might make sense to try to accommodate application code conforming to that obsolete version, even if it is doing something stupid..
[23:58:55] <nsz> newbie|4: no
[23:59:10] <nsz> that's posix-2004, it was changed in posix-2008
[23:59:17] <nsz> and the link i posted explains why
[00:00:39] <nsz> dalias: it looks like to me that fflush(0) does not lock f when it accesses its members
[00:00:53] <newbie|4> ah, ok.... are you fine if I paste chatlog to github comment?
[00:01:11] <nsz> i'm fine
```

**Comment by santigimeno** [comment]
Landed in https://github.com/libuv/libuv/commit/ad1c828827043fd1048582cee60103a68c8d929a. Thanks!

**Pull request closed without merging**
