### PR TITLE
unix,stream: fix shutdown hang

### PR DESCRIPTION
**Pull request by vtjnash**
While normally, users will likely typically call uv_close in their
uv_shutdown callback, some callers (notable nodejs) do not. This can
result in libuv keeping the loop active, even though there are no
outstanding reqs left to handle.

This bug was added in 80f2f826bf90b84e659321c0b7fd8af419acb85e, where
the premise of that commit was simply incorrect, as demonstrated by the
added test. (@bnoordhuis)

Refs: https://github.com/libuv/libuv/issues/3202#issuecomment-874961223
CI: https://ci.nodejs.org/job/libuv-test-commit/2178/ + https://ci.nodejs.org/job/libuv-test-commit-windows-cmake/371/
CI+node: ~~https://ci.nodejs.org/view/libuv/job/libuv-in-node/186/~~ https://ci.nodejs.org/view/libuv/job/libuv-in-node/187/

### CODE REVIEW

**Comment by vtjnash** [comment]
bump

**Comment by vtjnash** [comment]
bump

**Review by santigimeno — COMMENTED** [review]
Can you elaborate a bit more why it's ok to stop the handle even if the handle may have pending writes? I've read the comment in #3202 but it's still not clear to me

**Comment by vtjnash** [comment]
"stopping a handle" in libuv means roughly "to stop reading a handle". There is therefore never a time that a pending write means you can't stop reading a handle–it just isn't how libuv defines this.

**Comment by santigimeno** [comment]
I was thinking more on the case mentioned originally where ther

**Comment by vtjnash** [comment]
The case mentioned in the original commit cannot happen, since there is never a case where a pending write needs to force the loop to continue reading from the handle. The bit here does not control whether the loop exits, it controls whether it is waiting for reads from the handle, but those reads will never happen, since the user stopped the handle. Which is fortunate, because otherwise there would be a massive bug there–note the wording there ("force libuv to *continue* reading from the handle if there are incomplete writes")–and things would have needed a major redesign.

**Review by santigimeno — APPROVED** [review]
Ok. I think I understand now. Even though there are pending pending writes, those are `uv_req_t` which would keep the loop alive even though the handle is stopped. Thanks for the explanation.

**Comment by gluxon** [comment]
Thanks a lot for this fix! My team was seeing this multiple times a week when running `prettier` and `webpack` on CI.

We were debugging this quite thoroughly through `llnode` and `strace` before realizing the latest Node.js 16.x version contained the fix already, and then narrowed it back to this change.

---

Posting some debugging we did in case it helps others find this PR.

`strace` showed a hang on `epoll_wait` that was eventually killed 10 minutes later by CI.

```
11:27:45 getpid()                       = 16831
11:27:45 epoll_wait(13, [{EPOLLIN, {u32=16, u64=16}}], 1024, -1) = 1
11:27:45 read(16, "\1\0\0\0\0\0\0\0", 1024) = 8
11:27:45 epoll_wait(13, 0x7ffc8bec4fe0, 1024, -1) = -1 EINTR (Interrupted system call)
11:47:39 --- SIGABRT {si_signo=SIGABRT, si_code=SI_USER, si_pid=736, si_uid=1000} ---
11:47:39 +++ killed by SIGABRT (core dumped) +++
```

Debugging core dumps in `llnode` showed the following thread stacktrace dumps:

```
(llnode) bt all
* thread #1, name = 'node', stop reason = signal SIGABRT
  * frame #0: 0x00007fcc850c7a47 libc.so.6`epoll_wait + 87
    frame #1: 0x0000000001348150 node`uv__io_poll(loop=0x0000000002c9aac0, timeout=-1) at linux-core.c:309
    frame #2: 0x0000000001335e4f node`uv_run(loop=0x0000000002c9aac0, mode=UV_RUN_DEFAULT) at core.c:381
    frame #3: 0x0000000000a4b665 node`node::NodeMainInstance::Run() + 581
    frame #4: 0x00000000009da5a8 node`node::Start(int, char**) + 664
    frame #5: 0x00007fcc84fc7bf7 libc.so.6`__libc_start_main + 231
    frame #6: 0x0000000000979215 node`_start + 41
  thread #2, stop reason = signal 0
    frame #0: 0x00007fcc853a4ad3 libpthread.so.0`__pthread_cond_wait + 579
    frame #1: 0x00000000013445b9 node`uv_cond_wait(cond=<unavailable>, mutex=<unavailable>) at thread.c:782
    frame #2: 0x0000000000a75f14 node`node::(anonymous namespace)::PlatformWorkerThread(void*) + 196
    frame #3: 0x00007fcc8539e6db libpthread.so.0`start_thread + 219
    frame #4: 0x00007fcc850c771f libc.so.6`clone + 63
  thread #3, stop reason = signal 0
    frame #0: 0x00007fcc853a4ad3 libpthread.so.0`__pthread_cond_wait + 579
    frame #1: 0x00000000013445b9 node`uv_cond_wait(cond=<unavailable>, mutex=<unavailable>) at thread.c:782
    frame #2: 0x0000000000a75f14 node`node::(anonymous namespace)::PlatformWorkerThread(void*) + 196
    frame #3: 0x00007fcc8539e6db libpthread.so.0`start_thread + 219
    frame #4: 0x00007fcc850c771f libc.so.6`clone + 63
  thread #4, stop reason = signal 0
    frame #0: 0x00007fcc853a4ad3 libpthread.so.0`__pthread_cond_wait + 579
    frame #1: 0x00000000013445b9 node`uv_cond_wait(cond=<unavailable>, mutex=<unavailable>) at thread.c:782
    frame #2: 0x0000000000a75f14 node`node::(anonymous namespace)::PlatformWorkerThread(void*) + 196
    frame #3: 0x00007fcc8539e6db libpthread.so.0`start_thread + 219
    frame #4: 0x00007fcc850c771f libc.so.6`clone + 63
  thread #5, stop reason = signal 0
    frame #0: 0x00007fcc853a4ad3 libpthread.so.0`__pthread_cond_wait + 579
    frame #1: 0x00000000013445b9 node`uv_cond_wait(cond=<unavailable>, mutex=<unavailable>) at thread.c:782
    frame #2: 0x00000000013309ee node`worker(arg=<unavailable>) at threadpool.c:76
    frame #3: 0x00007fcc8539e6db libpthread.so.0`start_thread + 219
    frame #4: 0x00007fcc850c771f libc.so.6`clone + 63
  thread #6, stop reason = signal 0
    frame #0: 0x00007fcc853a4ad3 libpthread.so.0`__pthread_cond_wait + 579
    frame #1: 0x00000000013445b9 node`uv_cond_wait(cond=<unavailable>, mutex=<unavailable>) at thread.c:782
    frame #2: 0x0000000000a75f14 node`node::(anonymous namespace)::PlatformWorkerThread(void*) + 196
    frame #3: 0x00007fcc8539e6db libpthread.so.0`start_thread + 219
    frame #4: 0x00007fcc850c771f libc.so.6`clone + 63
  thread #7, stop reason = signal 0
    frame #0: 0x00007fcc853a77c6 libpthread.so.0`do_futex_wait.constprop.1 + 54
    frame #1: 0x00007fcc853a78b8 libpthread.so.0`__new_sem_wait_slow.constprop.0 + 152
    frame #2: 0x0000000001344392 node`uv_sem_wait at thread.c:626
    frame #3: 0x0000000001344380 node`uv_sem_wait(sem=0x0000000002c93be0) at thread.c:682
    frame #4: 0x0000000000b00d25 node`node::inspector::(anonymous namespace)::StartIoThreadMain(void*) + 53
    frame #5: 0x00007fcc8539e6db libpthread.so.0`start_thread + 219
    frame #6: 0x00007fcc850c771f libc.so.6`clone + 63
  thread #8, stop reason = signal 0
    frame #0: 0x00007fcc853a4ad3 libpthread.so.0`__pthread_cond_wait + 579
    frame #1: 0x00000000013445b9 node`uv_cond_wait(cond=<unavailable>, mutex=<unavailable>) at thread.c:782
    frame #2: 0x00000000013309ee node`worker(arg=<unavailable>) at threadpool.c:76
    frame #3: 0x00007fcc8539e6db libpthread.so.0`start_thread + 219
    frame #4: 0x00007fcc850c771f libc.so.6`clone + 63
  thread #9, stop reason = signal 0
    frame #0: 0x00007fcc850c7a47 libc.so.6`epoll_wait + 87
    frame #1: 0x0000000001348150 node`uv__io_poll(loop=0x0000000003172888, timeout=-1) at linux-core.c:309
    frame #2: 0x0000000001335e4f node`uv_run(loop=0x0000000003172888, mode=UV_RUN_DEFAULT) at core.c:381
    frame #3: 0x0000000000a7a178 node`node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start()::'lambda'(void*)::_FUN(void*) + 120
    frame #4: 0x00007fcc8539e6db libpthread.so.0`start_thread + 219
    frame #5: 0x00007fcc850c771f libc.so.6`clone + 63
  thread #10, stop reason = signal 0
    frame #0: 0x00007fcc853a4ad3 libpthread.so.0`__pthread_cond_wait + 579
    frame #1: 0x00000000013445b9 node`uv_cond_wait(cond=<unavailable>, mutex=<unavailable>) at thread.c:782
    frame #2: 0x00000000013309ee node`worker(arg=<unavailable>) at threadpool.c:76
    frame #3: 0x00007fcc8539e6db libpthread.so.0`start_thread + 219
    frame #4: 0x00007fcc850c771f libc.so.6`clone + 63
  thread #11, stop reason = signal 0
    frame #0: 0x00007fcc853a4ad3 libpthread.so.0`__pthread_cond_wait + 579
    frame #1: 0x00000000013445b9 node`uv_cond_wait(cond=<unavailable>, mutex=<unavailable>) at thread.c:782
    frame #2: 0x00000000013309ee node`worker(arg=<unavailable>) at threadpool.c:76
    frame #3: 0x00007fcc8539e6db libpthread.so.0`start_thread + 219
    frame #4: 0x00007fcc850c771f libc.so.6`clone + 63
(llnode)
```

**Pull request merged**
