### PR TITLE
Update CI to macOS 14 (and 13)

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by bnoordhuis** [comment]
It's that same EBUSY error from https://github.com/libuv/libuv/pull/4455#issuecomment-2232462998 again.

I don't have good suggestions on how to fix it, just how to squelch it:
```diff
diff --git a/test/test-udp-multicast-join.c b/test/test-udp-multicast-join.c
index 7e8fbe39..c4326114 100644
--- a/test/test-udp-multicast-join.c
+++ b/test/test-udp-multicast-join.c
@@ -36,6 +36,7 @@ static uv_udp_t client;
 static uv_udp_send_t req;
 static uv_udp_send_t req_ss;
 
+static int darwin_ebusy_errors;
 static int cl_recv_cb_called;
 
 static int sv_send_cb_called;
@@ -128,6 +129,13 @@ static void cl_recv_cb(uv_udp_t* handle,
 
 #if !defined(__OpenBSD__) && !defined(__NetBSD__)
     r = uv_udp_set_source_membership(&server, MULTICAST_ADDR, NULL, source_addr, UV_JOIN_GROUP);
+#if defined(__APPLE__)
+    if (r == UV_EBUSY) {
+      uv_close((uv_handle_t*) &server, close_cb);
+      darwin_ebusy_errors++;
+      return;
+    }
+#endif
     ASSERT_OK(r);
 #endif
 
@@ -175,6 +183,9 @@ TEST_IMPL(udp_multicast_join) {
   /* run the loop till all events are processed */
   uv_run(uv_default_loop(), UV_RUN_DEFAULT);
 
+  if (darwin_ebusy_errors > 0)
+    RETURN_SKIP("Unexplained macOS IP_ADD_SOURCE_MEMBERSHIP EBUSY bug");
+
   ASSERT_EQ(2, cl_recv_cb_called);
   ASSERT_EQ(2, sv_send_cb_called);
   ASSERT_EQ(2, close_cb_called);
```

**Comment by saghul** [comment]
Thanks Ben!

**Comment by vtjnash** [comment]
udp_multicast_join seems to still be failing?

Also this one, but it seems unrelated as fs_event has been unreliable in the past too (and errno 24 is EMFILE):
```
not ok 51 - fs_event_error_reporting
# exit code 6
# Output from process `fs_event_error_reporting`:
# Assertion failed in /Users/runner/work/libuv/libuv/test/test-fs-event.c on line 1124: `uv_fs_event_start(event, fs_event_error_report_cb, "watch_dir", 0) == 0` (-24 == 0)
```

**Comment by saghul** [comment]
I'm on vacation now, hope to pick this up next week 😅

**Comment by saghul** [comment]
I'll pick this back up this week, now that GH has announced the sunset of macos 12...

**Comment by saghul** [comment]
Alright, this one is ready for review, finally!

**Review by bnoordhuis — APPROVED** [review]

**Pull request merged**
