### PR TITLE
win,build: fix compilation on ancient Windows systems

### PR DESCRIPTION
**Pull request by saghul**
Fixes build on Windows XP with Visual Studio 2008.

R=@orangemocha, @piscisaureus

### CODE REVIEW

**Comment by saghul** [comment]
Please, don't ask.

**Comment by saghul** [comment]
LoL, it seems to fail only on 32bit systems: https://ci.appveyor.com/project/saghul/pyuv/build/1.0.43 Using Windows SDK 7.

**Comment by orangemocha** [comment]
LGTM, but do you really need to support *compiling* on such systems?

**Comment by saghul** [comment]
@orangemocha sadly, yes. Python 2.7 was compiled with Visual Studio 2008 and you have to compile your modules using that. It looks like it also fails with MSVC 2012 (see #881) , which is more recent.

**Pull request merged**
