### PR TITLE
unix: uv_get_free_memory return allocable memory

### PR DESCRIPTION
**Pull request by zhangzifa**
uv_get_free_memory returns the `allocable` memory.

### CODE REVIEW

**Comment by zhangzifa** [comment]
```uv_get_free_memory``` returns the `free` memory.

However, the `allocable` memory more reasonable to the user.

This link can be refered:
http://blog.scoutapp.com/articles/2010/10/06/determining-free-memory-on-linux

image

An alternative is to provide another API for detailed memory information.

`total, used, free, shared, buffers, cached`.

**Comment by llafuente** [comment]
Hi @zhangzifa,
I think this will be rejected as it is. Opening a process and parsing output it's not reliable.

It's a better approach to use directly the syscalls (and faster)
Take a look at what meminfo does.
http://lxr.free-electrons.com/source/fs/proc/meminfo.c

seems like two syscalls (I did just a fast look)
* `si_meminfo`
* `si_swapinfo` (maybe not necessary)

**Comment by zhangzifa** [comment]
Thanks @llafuente. 
In fact, I pay more attention to `free` or `allocable` memory should be provided. Could you help comment this?

Yes, it is no double a better approach to use syscalls.

If you have a look at uv/src/unix/linux-core.c, `uv_cpu_info` has the same approach `Opening a process and parsing output`. :-)

**Comment by yjhjstz** [comment]
> si_meminfo
si_swapinfo (maybe not necessary)

above two, only can be used in kernel space,
in user space, do you mean `sysinfo `?

**Comment by saghul** [comment]
Hi @zhangzifa! What @llafuente said is basically correct. There are two things at play here:

* Parsing /proc/foo should only be used as a last resort option
* This changes the behavior of the API, which we cannot do in v1.x
* If we change this on Linux, we need the same change on other platforms, the API has to be consistent

**Comment by zhangzifa** [comment]
@yjhjstz It's a pity that `sysinfo` does not provide `cache` memory.

**Comment by zhangzifa** [comment]
@saghul Thanks for your clarifications.
Maybe this API update, or new API can be added in v2.x.
Or do you think it's necessary to add a new API to 1.x?

**Comment by saghul** [comment]
> Maybe this API update, or new API can be added in v2.x.

Yeah, I'd discuss it for v2.

> Or do you think it's necessary to add a new API to 1.x?

I wouldn't add it to v1.x.

**Comment by zhangzifa** [comment]
Ok, got it. Thanks.

**Comment by saghul** [comment]
Since this PR was targetted at v1.x, I'm going to close it. Please reopen it targetting master once you have it ready for discussion, thanks!

**Pull request closed without merging**
