### PR TITLE
doc: add vtjnash to maintainers

### PR DESCRIPTION
**Pull request by vtjnash**
Hi there, libuv! I was invited to add my name here. I'm looking forward to our future collaboration :)

### CODE REVIEW

**Comment by cjihrig** [comment]
@refack are you able to get @vtjnash access to the libuv CI?

**Comment by bnoordhuis** [comment]
And welcome of course!

**Comment by refack** [comment]
Welcome @vtjnash you should be able to start jobs from https://ci.nodejs.org/view/libuv/job/libuv-test-commit/
Let me know if there's anything else you need access too.

**Comment by cjihrig** [comment]
@vtjnash feel free to land this anytime.

**Comment by vtjnash** [comment]
Landed in 4b7f3686270f95b6ef67e7e5e0a6c95cce338448

**Pull request closed without merging**
