### PR TITLE
[WIP] !win: uv_uptime to actuality return a double

### PR DESCRIPTION
**Pull request by refack**
Ref: https://github.com/libuv/libuv/issues/1294
Ref: 556fe1a6598bbd1bee4a98

/cc @bnoordhuis 
Please comment on pros/cons/my stupidity
Also hoping for a good CI, as it's a bit of a shot in the dark

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Since no one actually complained about this I'm inclined to leave well enough alone.

**Comment by refack** [comment]
Hey, I'm complaining...
But Ok.

**Comment by refack** [comment]
Maybe just round down on Windows to eliminate the disparity?

**Comment by saghul** [comment]
I defer to @bnoordhuis here.

**Comment by cjihrig** [comment]
@bnoordhuis do you want to close this one?

**Comment by bnoordhuis** [comment]
Yes, I'll close it.

**Pull request closed without merging**
