### PR TITLE
core: move all include files except uv.h to uv/

### LINKED ISSUE #1161: what's about installing headers with prefix
Since there are many headers files, what's about using a prefix suc as 'uv'.

for example in C source file,

#include <uv/uv.h>

which is also applicable for all others
#include <uv/tree.h>
#include <uv/uv-win.h>
#include <uv/uv-unix.h>
#include <uv/uv-threadpool.h>

### PR DESCRIPTION
**Pull request by saghul**
Fixes #1161

### CODE REVIEW

**Comment by saghul** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/348/

**Comment by saghul** [comment]
🆘  Hey @joaocgreis / @jbergstroem I need some help. This will require some adjustment on the Windows CI, since it's looking for uv-version.h, which this commit renames.

**Comment by joaocgreis** [comment]
Sorry for the delay. CI adapted to work with both files.
- This PR, before the CI change: https://ci.nodejs.org/job/libuv-test-commit-windows/438/
- `v1.x` after: https://ci.nodejs.org/job/libuv-test-commit-windows/439/
- This PR after: https://ci.nodejs.org/job/libuv-test-commit-windows/440/

**Comment by saghul** [comment]
@joaocgreis Sorry, I missed this! Thanks!

**Pull request merged**
