### PR TITLE
tcp: add uv_tcp_timeout

### PR DESCRIPTION
**Pull request by theanarkh**
refs: https://github.com/libuv/libuv/issues/3651

### CODE REVIEW

**Comment by theanarkh** [comment]
Hi ! Does anyone help review this ? Thanks !

**Comment by vtjnash** [comment]
I would potentially argue that most `setsockopt` calls should be dealt with by the user calling into the C library directly

**Comment by theanarkh** [comment]
Do you mean we should call this in caller(such as Node.js) instead of Libuv?

**Comment by bnoordhuis** [comment]
A more fundamental issue: TCP_USER_TIMEOUT doesn't do anything for non-blocking sockets, it won't wake up epoll_wait(). There's not much point in adding it to libuv.

**Pull request closed without merging**
