### PR TITLE
zos: avoid -fstrict-aliasing compile option

### PR DESCRIPTION
**Pull request by jBarz**
This is not supported by the z/OS compler.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
I'd be okay with removing the flag altogether.  Libuv is not aliasing-safe if you consider aliasing to be nominal rather than structural and it's not as if it makes much of a difference in the quality of the generated code, at least for libuv.  That would also close out #1230, I think.

**Comment by jBarz** [comment]
I will make that change and use your reasoning in the commit message.

**Comment by bnoordhuis** [comment]
Ping @jBarz.

**Comment by jBarz** [comment]
Done. 
The flag is removed altogether.

**Comment by jBarz** [comment]
oops, done.

**Comment by bnoordhuis** [comment]
There's still a `-Wno-strict-aliasing` in common.gypi and I see now there is a `-Wstrict-aliasing` in uv.gyp.

**Comment by jBarz** [comment]
Doh! Had to rebase my PR. Done.

**Comment by bnoordhuis** [comment]
Some unrelated flakes but otherwise green.  Landed in 9991bb7c6, thanks John!

**Pull request closed without merging**
