### PR TITLE
Fixed compatibility issue with Windows 7 (updated)

### PR DESCRIPTION
**Pull request by XVilka**
This is a rebased, updated, and cleaned up version of https://github.com/libuv/libuv/pull/3285

cc @kampeador @vtjnash 

I was porting changes to 1.44.1 and decided to send an updated PR here as well.

### CODE REVIEW

**Comment by XVilka** [comment]
Ping? @libuv

**Comment by walidbagh** [comment]
bump

**Comment by amurzeau** [comment]
The previous PR was found too big to be merged, maybe an simpler alternative that just call `GetComputerName` if GetHostname is not available would be good enough ? This would make the diff much smaller.

**Comment by vtjnash** [comment]
I am really on the fence about this. On one hand, this is a well-executed PR. On the other hand, Win 7 is long past EOL, so is increasingly vulnerable anytime it is on a network for someone to get their computed hacked, turned into an evil spam bot, and their bitcoins stolen. So I cannot really think of a good reason someone would want this.

**Comment by gresolio** [comment]
A lot of software depends on libuv, and community is interested in fixing this issue.
So why not provide an opportunity for the community to help resolve it?

"their computed hacked, turned into an evil spam bot, and their bitcoins stolen. So I cannot really think of a good reason someone would want this":
Fixing the issue and discussing the potential risk of using Win 7 are two different topics, completely independent of each other. Things (including software) are relevant as long as they are useful and people are interested in them.

My comment about understanding of the inability to solve the issue: https://github.com/libuv/libuv/issues/3260#issuecomment-1008421571

**Comment by vtjnash** [comment]
Nope, that is not how open source works. From your profile, it does not look like you are involved at all. Get involved with more projects if you want support for old, insecure, proprietary, deprecated operating systems.

Or if you want updates forever, use linux.

I have decided we should drop Windows 8.1 support, in order to use new security features, so restoring support for an OS last released over 11 years ago is not necessary.

**Comment by gresolio** [comment]
@vtjnash, getting personal is also not the best example of how open source works. You know nothing about my actual involvement.

"**I** have decided **we** should drop" - is the answer, thank you, looks like further discussion is pointless.

The distorted concept of software security is used as an excuse over and over again.

**Comment by bnoordhuis** [comment]
> looks like further discussion is pointless

It was already pointless back in 2020/2021 but still plenty of people insisted on beating that dead horse over and over again. Anyone's patience is going to run thin after that.

**Comment by zbyna** [comment]
Yes, mozilla for example still support “dead horse” 🙂 . Please do not hide your decision with so called “security issues” . Microsoft pushes its new unwanted children by any possible means.  Just take your  responsibility and cut the support  definitely if you mean it but without excuses please.

**Comment by bnoordhuis** [comment]
Okay, I'm getting fed up with this. @zbyna I killed your comment. Next time it's a lifetime ban from the org.

**Comment by vtjnash** [comment]
Just as a reminder, you are always welcome to maintain your own fork of libuv that includes patches to support old versions of Windows. This is quite common for distros and other software dependency channels. It just won't get an official blessing from here for releases, but it does not need one to exist.

**Comment by zbyna** [comment]
@bnordhuis Hold your horses  member, with great power comes great responsibility! In my comment there was not any  inappropriated, violent or nasty word!  If something offend you that was not my intention at all.  I am sorry for that.

**Comment by gresolio** [comment]
bnoordhuis commented Jan 23, 2023 https://github.com/libuv/libuv/pull/3891#issuecomment-1400174092
Time moves on. We've decided to drop support for Windows 8.1 so the odds of us reconsidering Windows 7? Slim.
If Windows 7 support is important to you, carry this patch in your local fork.

@bnoordhuis
I agree and fully respect your position on the end of support for legacy systems.
Go ahead, make Tier 1 >= Win 10, and drop Win7, Win8.1, it's totally fine.

But why refuse fixes that are still relevant to the community? (if patches are simple and unobtrusive).
What the difference for such contributions to other non-mainstream contributions? (e.g. GNU/Hurd or BSD*, or MinGW related).

There are already many forks. Fragmentation and incompatibility are big issues in open-source.
I'm not asking to reconsider official support of obsolete things.
I'm asking for including [simple alternative patch](https://github.com/libuv/libuv/pull/3891) that improves the situation on a still relevant issue to the community.

**Comment by bnoordhuis** [comment]
Things might have been different if you'd sent that patch two or three years ago but at this point it's basically like this: we maintainers have heard your requests, we've given them due consideration, and the answer is "no."

At this point the discussion is closed. That's why I locked the conversation and that's why I'll lock this one as well.

**Pull request closed without merging**
