### PR TITLE
win: consider a broken pipe a normal EOF

### PR DESCRIPTION
**Pull request by mmomtchev**
Normally an `ERROR_BROKEN_PIPE` is translated to an `EOF` but the translation happens after the decision to set the errno - thus the broken pipe appears as a very weird `EOF` exception in Node

#3043 
<https://github.com/nodejs/node/issues/35997>

### CODE REVIEW

**Comment by bughit** [comment]
@bnoordhuis What is the point of forcing PRs do be bumped?

**Comment by bnoordhuis** [comment]
@bughit You're asking the wrong person. I've scaled back my libuv involvement.

**Review by santigimeno — APPROVED** [review]
It seems reasonable to me, but would love input from the windows experts. /cc @libuv/windows

**Comment by santigimeno** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/2106/

**Comment by bzoz** [comment]
@mmomtchev could you add a test for this?

**Comment by mmomtchev** [comment]
@bzoz I removed a workaround for this special case on Win32 from another test
There are quite lots of tests that do not pass when run manually - but do when run through `ctest` - I don't know if this is a problem on my end?

**Comment by bzoz** [comment]
@mmomtchev the test runner is sensitive to the working directory. Make sure to run the test from the main folder - call   `build/uv_run_tests_a`, not `uv_run_tests_a`.

CI-in-node: https://ci.nodejs.org/view/libuv/job/libuv-in-node/172/
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/2115/

**Comment by bzoz** [comment]
Resumed builds, errors looked unrelated https://ci.nodejs.org/view/libuv/job/libuv-in-node/173/ and https://ci.nodejs.org/view/libuv/job/libuv-test-commit/2116/

**Comment by santigimeno** [comment]
@bzoz, trying to move this forward. Does this PR lgty? Thanks!

**Comment by bughit** [comment]
evidently a reaction is not activity

**Comment by DanKaplanSES** [comment]
Can this be merged? I spent hours troubleshooting this problem.

**Comment by bnoordhuis** [comment]
Needs feedback from @libuv/windows.

**Comment by bughit** [comment]
> Needs feedback from @libuv/windows.

That was requested on Dec 29, 2020.

**Comment by vtjnash** [comment]
CI: https://ci.nodejs.org/job/libuv-test-commit/2225/

**Pull request merged**
