### PR TITLE
Adding alias for libuv

### PR DESCRIPTION
**Pull request by anthonyalayo**
Adding support for issue https://github.com/libuv/libuv/issues/4282

### CODE REVIEW

**Comment by anthonyalayo** [comment]
Any thoughts @bnoordhuis ?

**Review by bnoordhuis — APPROVED** [review]
LGTM, but I'd like at least one other maintainer to take a look as well.

**Comment by anthonyalayo** [comment]
Sounds good. @vtjnash @santigimeno would one of you be able to review this? Thanks a lot

**Review by vtjnash — APPROVED** [review]
I have only the slightest idea what cmake does and how it works, so if this works for someone else, it sounds good to me

**Comment by anthonyalayo** [comment]
I noticed I _just_ missed the latest version cut. @bnoordhuis any idea when the next version cut will come up?

**Comment by bnoordhuis** [comment]
We don't have a regular release cadence but releases usually have a few months between them.

**Pull request merged**
