### PR TITLE
win: security descriptor to be accessible by any user

### PR DESCRIPTION
**Pull request by ssrlive**
Allows user-privileged processes to access named pipes created by system-privileged processes.

### CODE REVIEW

**Comment by ssrlive** [comment]
anybody review it?

**Comment by vtjnash** [comment]
Can you provide more context on the intent and how it differs from past provisions (uv_chmod) and across platforms?

**Comment by ssrlive** [comment]
I write a Windows service with libuv, the main logic like this:

https://github.com/nikhilm/uvbook/blob/master/code/pipe-echo-server/main.c

the service run in system account  privileges.

then I write a client like this:

```javascript
var net = require('net');
var domain = require('domain');

var remoteProxyIp = process.argv[2];
if (remoteProxyIp == undefined) {
    remoteProxyIp = "123.45.67.89";
}

var addr = '\\\\?\\pipe\\echo.sock';

var d = domain.create();
d.on('error', function(err) {
    console.error(err);
});

d.run(function() {
    var client = net.createConnection({ path: addr }, function() {
        console.log("Connected");
        client.on('data', function(data) {
            console.log("Recieved: " + data);
        });
        client.on('error', function(){
            console.log(arguments);
        });

        client.on('end', function() { 
            console.log('Disconnecting server...');
        });

        const cleanup = () => {
            client.removeAllListeners();
            process.exit();
        };
        client.once('close', cleanup);
        client.once('error', cleanup);

        client.write(`{"action":"configureRouting","parameters":{"proxyIp":"${remoteProxyIp}","isAutoConnect":false}}`);

    }.bind(this));

    function timeoutQuit(arg) {
        // client.destroy();
        process.exit();
    }

    process.on('SIGINT', function() {
        console.log("Caught interrupt signal");
        client.write('{"action":"resetRouting","parameters":{}}');
        setTimeout(timeoutQuit, 2000, 'JustExit');
    });
});

```

this client can not connect to the server (system service). 

After apply my PR, the client can connect the server.

**Comment by bzoz** [comment]
Did you try using [`uv_pipe_chmod`](http://docs.libuv.org/en/v1.x/pipe.html#c.uv_pipe_chmod)? It was to address such use cases, like in https://github.com/nodejs/node/issues/19154

**Comment by ssrlive** [comment]
OK. You are right. After add 
```
    uv_pipe_chmod(pipe, UV_WRITABLE | UV_READABLE);
```
the client can connect server.
Thanks.

**Pull request closed without merging**
