### PR TITLE
win,tty: allow utf-16 surrogate pairs to pass through

### PR DESCRIPTION
**Pull request by musm**
Reading things again from the linked original PR in https://github.com/libuv/libuv/pull/2910:

Quoting @DHowett  from https://github.com/libuv/libuv/pull/2910#issuecomment-656877625

> I do, however, think the best course of action is to simply let surrogate pairs through. 

Thus I just removed the Windows 10 restriction from the PR https://github.com/libuv/libuv/pull/2910

closes https://github.com/libuv/libuv/issues/2909

### CODE REVIEW

**Comment by vtjnash** [comment]
CI: https://ci.nodejs.org/job/libuv-test-commit/2029/

**Comment by DHowett** [comment]
Yeah, this has my support. If ConEmu wants to support surrogate pairs by scanning the contents of the buffer _on Windows 7_, they should be empowered to. There's a vanishingly small chance that they _will_, but it will become possible. :smile:

**Comment by musm** [comment]
CI: all green. Can we merge this now?

**Review by bnoordhuis — APPROVED** [review]
LGTM, thanks Mustafa. Apropos the first two commits - no attribution needed, feel free to squash.

**Comment by musm** [comment]
Done

**Comment by musm** [comment]
@bnoordhuis  I squashed the commits, but didn't remove you attribution, is that OK, or would you like me to remove it before merging? Let me know, hoping to get this merged ASAP 😄

**Comment by bnoordhuis** [comment]
Merged in aa4fcc49, cheers! I changed the authorship to you, Mustafa. It's hardly recognizable as my patch anymore and besides, I'd end up being both author and reviewer. :-)

**Comment by musm** [comment]
Many thanks, glad I can finally use emoji's in my code on Windows 😄

**Comment by nu8** [comment]
https://github.com/nodejs/node/issues/34883

**Pull request closed without merging**
