### PR TITLE
macos: work around posix_spawn() cwd bug

### PR DESCRIPTION
**Pull request by bnoordhuis**
~~Trying CI for a suspected posix_spawn() bug.~~ - edit: confirmed

<hr>

macOS 10.15 has a bug where configuring the working directory with
posix_spawn_file_actions_addchdir_np() makes posix_spawn() fail
with ENOENT even though the executable is spawned successfully.

### CODE REVIEW

**Comment by vtjnash** [comment]
We reimplement this part of `posix_spawn` because of multiple other bugs related to bad handling of relative paths. Could we add an additional check to https://github.com/libuv/libuv/blob/d777af2fb92505e2a0ae73e789e1c139221b3f23/src/unix/process.c#L732 to fix this?

**Comment by bnoordhuis** [comment]
I'm not sure what additional check you mean?

**Comment by bnoordhuis** [comment]
Ping @vtjnash

**Comment by vtjnash** [comment]
This was apparently known, but I though we had worked around it already. Otherwise, there was a more complete version of your patch at https://github.com/libuv/libuv/pull/3257#issuecomment-891374523, but might have gotten lost in the mess of other bugs with posix_spawn we hit.

**Comment by vtjnash** [comment]
And to be precise, I think we do not call the broken function (`posix_spawnp`) in the case where you claim macOS is broken, so this is potentially a bug in our fix for this issue, rather than an underlying bug

**Comment by bnoordhuis** [comment]
> posix_spawnp

Is that a typo? The bug is in posix_spawn (sans p) + posix_spawn_file_actions_addchdir_np. The test case exercises exactly that code path.

**Comment by deepak1556** [comment]
@bnoordhuis when I reported the bug I was only able to repro with `posix_spawnp` https://gist.github.com/deepak1556/39d8feb1e572306223fc8203d3eb1a99 is extracted from the bug I filed with feedback assistant.

**Comment by bnoordhuis** [comment]
@deepak1556 Oh, interesting. Rust's libstd indeed calls posix_spawnp() but libuv calls posix_spawn() and seems to trigger the same bug.

(It definitely triggers _a_ bug as the test case demonstrates. And only on 10.15, 10.14 is unaffected.)

**Comment by deepak1556** [comment]
> libuv calls posix_spawn() and seems to trigger the same bug.

Maybe I might have misunderstood the code path, it looks like libuv also triggers `posix_spawnp` for relative paths https://github.com/libuv/libuv/blob/v1.x/src/unix/process.c#L674-L685 ?

**Comment by bnoordhuis** [comment]
No, it's me that misunderstood the relevant logic - it indeed ends up calling posix_spawnp() 🤦

In my defense, src/unix/process.c has turned into a real twisty maze of if statements, all alike.

**Pull request closed without merging**
