### PR TITLE
unix: spawn should protect its input fds

### PR DESCRIPTION
**Pull request by sam-github**
spawn allows copying descriptor numbers during exec, but it wasn't
protecting them. Under some conditions, such as swapping stdout and
stderr, it would do this:

 dup 2 -> 1
 dup 1 -> 2

With end result that both 1 and 2 would be stderr, rather than being
swapped.

With this change, the above sequence gets rewritten to:

 dup 1 -> 3
 dup 2 -> 1
 dup 3 -> 2

This fix can be verified against io.js. Using fd-dup.js:

```
var cp = require('child_process');
var fs = require('fs');

if (process.env.CHILD) {
  console.log('STDOUT');
  console.error('STDERR');
  return;
}

var options = {
  stdio: [0, 2, 1],
  env: { CHILD: true },
};
var c = cp.spawn(process.execPath, [__filename], options);
```

Without this patch both fd 1 and 2 in child end up in parent's stderr:

```
% ./iojs fd-dup.js 1>_1.txt 2>_2.txt; more _*.txt|cat
::::::::::::::
_1.txt
::::::::::::::
::::::::::::::
_2.txt
::::::::::::::
STDOUT
STDERR
```

(Above assumes an io.js that has libuv bug #224 fixed, otherwise it will output nothing, because fd 2 will be closed).

After this patch, they are swapped, as intended:
```
% ./iojs fd-dup.js 1>_1.txt 2>_2.txt; more _*.txt|cat
::::::::::::::
_1.txt
::::::::::::::
STDERR
::::::::::::::
_2.txt
::::::::::::::
STDOUT
```

/to @indutny, this fixes https://github.com/joyent/libuv/issues/1084

### CODE REVIEW

**Comment by saghul** [comment]
I'm not sure it works in all Unices, but how about using this to get duplicated fds beyond stdio_count?

~~~~
new_fd = fcntl (use_fd, F_DUPFD, stdio_count);
~~~~

It's simpler, assuming it works in all platforms we need it.

**Comment by saghul** [comment]
Also, a test! :-)

**Comment by sam-github** [comment]
F_DUPFD fcntl: I wasn't aware of that fcntl. It looks perfect. I see it on Linux and OS X's man pages, but no idea how wide-spread it is. I could do an #ifdef F_DUPFD... but then I would be maintaining two copies of the same code.

I considered changing the dup2() to be something like:

```
int dupAbove(int fd, int above) {
  int copy;
  while((copy = dup(fd)) < above && copy != -1)
    ;
  return copy;
}
```

Basically, repeatedly calling dup() until the result is > use_fd. That loop would *normally* never run more than once, so have zero-overhead in the normal case. It might be the best "portable" alternative to F_DUPFD.

What to do, rewrite to the "portable" F_DUPFD, or just use F_DUPFD, and see if builds fail anywhere?

As for tests, I'm sorry, but I can find no tests for spawn-with-stdio at all, anywhere in uv, that I can use as a base to add this case to. Did I fail to find the right code?

Writing spawn() tests from scratch seems like it would take days (that I won't have in the next weeks).

Can you point me to a test I can use as a base? Or do you have any ideas how to write the test?

**Comment by saghul** [comment]
AFAIS, F_DUPFD is part of POSIX (http://pubs.opengroup.org/onlinepubs/009695399/functions/fcntl.html) so we should be fine going that road. If any of the supported platforms doesn't have it (which I doubt) we can reconsider.

As for tests, spawn_stdout uses a spawn_helper2 process which just prints something. You could use it as a base and make it print to both stdout and stderr, which are redirected to 2 files, then synchronously read and compare the content.

**Comment by sam-github** [comment]
OK, @saghul I'll rewrite to use F_DUPFD, and take a shot at a test.

**Comment by saghul** [comment]
@sam-github will you have time to work on this? If possible it would be nice to include it on the next release. The test can probably be written similar to #224.

I can try to finish it if you're short on time.

**Comment by saghul** [comment]
#309 landed, closing!

**Pull request closed without merging**
