### PR TITLE
build: fix build warn on cygwin.

### PR DESCRIPTION
**Pull request by YumingMa**
Signed-off-by: MaYuming <maym@appexnetworks.com>

### CODE REVIEW

**Comment by YumingMa** [comment]
Could you help me start a CI test for this patch.  I have no permission.

**Comment by saghul** [comment]
We have no cygwin CI, but here is a run nonetheless: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1586/

**Comment by YumingMa** [comment]
@saghul It seems that the fails didn’t caused by this PR.

**Comment by YumingMa** [comment]
What should I do to merge it？

**Comment by saghul** [comment]
Sorry for the delay! Landed in 0ff717e3, thanks!

**Pull request closed without merging**
