### PR TITLE
Add ASSERT buf->base != NULL

### PR DESCRIPTION
**Pull request by nagayev**
buf->base can't be NULL

### CODE REVIEW

**Comment by saghul** [comment]
I believe we have instances of this in many tests. I'd say it's all or nothing... also, being tests I'm not sure it's worth it.

**Comment by nagayev2002** [comment]
@cjihrig
No, because I think it's trivial fix and it isn't necessary

**Comment by nagayev2002** [comment]
@cjihrig plz merge

**Comment by cjihrig** [comment]
See https://github.com/libuv/libuv/pull/2177#issuecomment-460554963. I don't want to disregard @saghul's comment.

**Comment by nagayev2002** [comment]
@cjihrig Ok, I will check tests

**Comment by cjihrig** [comment]
Ping @nagayev. Are you planning to address Saúl's comment? If not, lets close this out.

**Comment by nagayev** [comment]
@saghul 
Do you think this codechange isn't neccessary?

**Comment by saghul** [comment]
@nagayev Not really, to be honest.

**Comment by nagayev** [comment]
@cjihrig
So what is your decision?

**Comment by cjihrig** [comment]
Since @saghul isn't on board and the commit doesn't really add much to the test, I'm not going to push for this. Thanks for the PR though.

**Pull request closed without merging**
