### PR TITLE
cmake, Windows: Fix uv_test using shared libuv on Windows

### PR DESCRIPTION
**Pull request by ptlomholt**
Fixes a linker error when building tests via cmake on Windows by adding the proper USING_UV_SHARED=1 preprocessor define when linking to the shared libuv library.

### CODE REVIEW

**Comment by refack** [comment]
> Perhaps we can set up a cmake-on-windows test job? Should I file an issue over at nodejs/build?

I'll set that up.

**Comment by refack** [comment]
https://ci.nodejs.org/job/libuv-test-commit-windows-cmake/7/

I'll add to `libuv-test-commit` when this PR lands.

**Comment by cjihrig** [comment]
Landed in https://github.com/libuv/libuv/commit/c4a77f5bc74621e16a355615d9deddbcaa848ec3. Thanks!

Ping @refack re: https://github.com/libuv/libuv/pull/2187#issuecomment-463660334

**Comment by refack** [comment]
One last sanity https://ci.nodejs.org/job/libuv-test-commit-windows-cmake/9/

**Pull request closed without merging**
