### PR TITLE
Update uv.gyp: Bug fix for android build.

### PR DESCRIPTION
**Pull request by adis300**
Bug fix for android build.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
What exactly does it fix?  Users of libuv should not include anything from src/.

**Comment by bnoordhuis** [comment]
Can you post the output of `make V=1`?  Note that `src/` is already added to the include_dirs a few lines up.

**Comment by adis300** [comment]
@bnoordhuis   x86_64-linux-android-gcc '-DBUILDING_FUSI_SHARED=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DDEBUG=1' -I../../../src/include -I../../../libuv/include  -g -O0 -fPIC -std=c99 -Wall  -MMD -MF out/Debug/.deps/out/Debug/obj.target/libuv/../../libuv/src/fs-poll.o.d.raw  -D__ANDROID_API__=24 -c -o out/Debug/obj.target/libuv/../../libuv/src/fs-poll.o ../../../libuv/src/fs-poll.c
  x86_64-linux-android-gcc '-DBUILDING_FUSI_SHARED=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DDEBUG=1' -I../../../src/include -I../../../libuv/include  -g -O0 -fPIC -std=c99 -Wall  -MMD -MF out/Debug/.deps/out/Debug/obj.target/libuv/../../libuv/src/inet.o.d.raw  -D__ANDROID_API__=24 -c -o out/Debug/obj.target/libuv/../../libuv/src/inet.o ../../../libuv/src/inet.c  x86_64-linux-android-gcc '-DBUILDING_FUSI_SHARED=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DDEBUG=1' -I../../../src/include -I../../../libuv/include  -g -O0 -fPIC -std=c99 -Wall  -MMD -MF out/Debug/.deps/out/Debug/obj.target/libuv/../../libuv/src/threadpool.o.d.raw  -D__ANDROID_API__=24 -c -o out/Debug/obj.target/libuv/../../libuv/src/threadpool.o ../../../libuv/src/threadpool.c
In file included from ../../../libuv/src/threadpool.c:25:0:
../../../libuv/src/unix/internal.h:25:23: fatal error: uv-common.h: No such file or directory
 #include "uv-common.h"
                       ^

**Comment by bnoordhuis** [comment]
That's not a stock build, is it?  That `-DBUILDING_FUSI_SHARED=1` isn't coming from any of libuv's build files.

**Comment by adis300** [comment]
@bnoordhuis We use libuv as a dependency. It builds libuv first.

**Comment by bnoordhuis** [comment]
It still sounds like you have something strange in your build file, or perhaps you're hitting a gyp bug.  Note for example how `-I../../../src/include` is not a libuv include directory

**Comment by cjihrig** [comment]
It seems like this should not land. If I'm mistaken, we can revisit this.

**Pull request closed without merging**
