### PR TITLE
linux: check epoll_wait timeout and rerun if under

### PR DESCRIPTION
**Pull request by rvagg**
I've been poking at the persistent io.js failure of test/parallel/test-vm-timeout.js and tracked it back to `epoll_wait()`. We have regular failures on Ubuntu 10.04 which runs on 2.6.32. I think we also have failures on 12.04 too but much less common.

The test-vm-timeout code test that the timeouts for `vm.runInThisContext()` work correctly. The timeouts use the `node::Watchdog` object to do the timeouts. It in turn creates a new thread, adds a `uv_timer` to it, and does a `uv_run(loop_, UV_RUN_DEFAULT)` in the thread.

The failure comes in the form of the timer never being called. libuv does its loop, checks the timer, then uses `epoll_wait()` to make up the required time. There is a false assumption built in here that `epoll_wait()` will come back _at least_ `timeout` ms later; so if it comes back after a shorter amount of time the loop ends prematurely without triggering the timer at all, then `Watchdog` never gets its cue to end.

On these older kernels, it seems that the `epoll_wait()` timeout resolution is such that the call may return up to 10 ms (!!) before the required timeout (in my not-very-scientific tests--you can see this by printing out the newly calculated `timeout` value in my code and running test-vm-timeout, it seems to range from 1 to 10 on Ubuntu 10.04).

The solution I've proposed here, which fixes the io.js bug, wraps the `epoll_wait()` call in a timer, and reruns the call if we come up short.

I really have no idea if this is the optimal solution to this. How costly are the timer calls and is this a problem? Could there be a way to feature-test this up-front so we only have to use the timer on systems that need it? Or, alternatively, perhaps it's OK to compromise on the timeout value and return early so it's just the loop that needs to be fixed?

I haven't added tests or comments. I can spruce this up a bit if you want to go with this but my guess is that smarter minds will come up with a better solution.

/R=@bnoordhuis

### CODE REVIEW

**Comment by rvagg** [comment]
Updated so that we only use the hrtimer if we have a >0 timeout in the first place. My guess is that if we are using epoll_wait with a timeout then we can likely afford to waste a cycle or two on the hrtimer, and if epoll reports that there's something ready then we've only done the one call to hrtimer anyway.

**Comment by saghul** [comment]
@rvagg IMHO the approach here is wrong. libuv could return early fom polling, but the timer will be run on the next iteration. The problem is that the Watchdog only runs one loop iteration: https://github.com/iojs/io.js/blob/v1.x/src/node_watchdog.cc#L69

Let me cook a quick patch.

**Comment by saghul** [comment]
@rvagg can you test this patch? https://github.com/saghul/io.js/commit/70030ec8329b7c19a07dacb3e44ff8b4cb77d6f1 (compiles, but I haven't tested it).

Also, /cc @bnoordhuis

**Comment by bnoordhuis** [comment]
@saghul https://jenkins-iojs.nodesource.com/view/iojs/job/iojs+any-pr+multi/119/ - that's your patch.

**Comment by saghul** [comment]
FreeBSD is red, but the failures don't look related whatsoever. Success?

**Comment by bnoordhuis** [comment]
The freebsd bots have never been blue so far.  So yes, success!  Can you open a PR?  R=me.

**Comment by rvagg** [comment]
awesome, thanks @saghul!

**Pull request closed without merging**
