### PR TITLE
[v2] merge v1.x

### PR DESCRIPTION
**Pull request by saghul**
I regularly merge v1.x these days since we started making changes in master. This merge is a bit more complex though, and I also took the chance to adjust as necessary.

R= @libuv/collaborators 

The CI seems down, I'll start a build when it's back up.

### CODE REVIEW

**Comment by cjihrig** [comment]
LGTM pending CI.

**Comment by saghul** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/94/

**Comment by saghul** [comment]
A couple of typos / merge whoes on Windows. Fixed those. CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/95/

**Comment by saghul** [comment]
I screwed up the merge when adding a fixup, so here we go again: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/96/

**Comment by bnoordhuis** [comment]
LGTM

**Pull request merged**
