### PR TITLE
win: fixing build for older MSVC compilers

### PR DESCRIPTION
**Pull request by mikefero**

### CODE REVIEW

**Comment by mikefero** [comment]
I understand that with libuv v2.0.0 you will be dropping support from these older compilers but if you are interested I have a [patch](https://github.com/mikefero/libuv/commit/4649a47a2947b40546a5239f368f525f5b9ef9e7) for AppVeyor that uses the new CMake build system for Visual Studio 2010 - 2017 (32 and 64-bit) which I can create a separate PR for. Here are the results from AppVeyor build: 
https://ci.appveyor.com/project/mikefero/libuv/build/v1.18.0.build5

**Comment by piscisaureus** [comment]
I'm okay with this, although typically we don't use the `BOOL` type unless we're interacting with a Win32 API that has it in it's signature. Other places we just use `int`, `0`, and `1`.

**Comment by mikefero** [comment]
@piscisaureus Agreed. I saw mixed usage of FALSE so I wasn't sure which route would be best; apologies. I have updated this PR to remove the usage of BOOL for the non Win32 API calls.

**Comment by santigimeno** [comment]
Landed in https://github.com/libuv/libuv/commit/1d878b01f7efb8e8f451980f54c462e1ad628bc1. Thanks!

**Pull request closed without merging**
