### PR TITLE
Merge v1.x into master

### PR DESCRIPTION
**Pull request by saghul**
It's been a while, keep them in sync so we don't loose track.

CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/202/

### CODE REVIEW

**Comment by imran-iq** [comment]
OSX failure looks legit

**Comment by saghul** [comment]
Can't reproduce that locally, I do get this one though :-(

```
not ok 219 - kill
# exit code 134
# Output from process `kill`:
# exit_cb
# Assertion failed in ../test/test-spawn.c on line 93: no_term_signal || term_signal == 15
```

**Comment by santigimeno** [comment]
Can't reproduce the `OS X` failure locally. It passes for me in Debian Jessie 64bits, FreeBSD 11 and OS X

**Comment by imran-iq** [comment]
Re-ran the CI for OSX

https://ci.nodejs.org/job/libuv-test-commit-osx/198/

Came out green.

**Comment by saghul** [comment]
Kewl, I'll land later then.

**Pull request merged**
