### PR TITLE
Fix core dump caused when read() returns non-positive value

### PR DESCRIPTION
**Pull request by rgagnon24**

### CODE REVIEW

**Comment by txdv** [comment]
Obviously your patch will work for this specific case, I just wonder how to reproduce this in a simple C test case.

**Comment by rgagnon24** [comment]
Yes... since the core-dump files I have don't really say WHY the FD was at EOF state, it would be tough to make a test case, but....

If the system compiled is windows, the 0/EOF return value would be passed back to the calling routine anyhow.... so this patch really just ensures that a 0/EOF return from read() returns to the caller in the same manner whether on Windows or Linux.

**Comment by txdv** [comment]
https://github.com/rgagnon24/libuv/blob/3dee8f81d23e52fe974608edbabfc30dbc504e62/src/unix/async.c#L109-L123

n is set = 0, if we break, we leave it at 0, so there is a possibility that n just is 0.

Can you check up what the values of r or errno are in the loop when you hit the assert? Or before hitting the assert...

**Comment by rgagnon24** [comment]
Note... this is actually related to issue #1171 where there is the output from the core/gdb check...

Copying some results here:
```
(gdb) bt
#0  0x00007f27f80075f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f27f8008ce8 in __GI_abort () at abort.c:90
#2  0x00007f27f8000566 in __assert_fail_base (
    fmt=0x7f27f8150ce8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x11d1c11 "n == sizeof(val)", 
    file=file@entry=0x11d1bf5 "../deps/uv/src/unix/async.c", line=line@entry=136, 
    function=function@entry=0x11d1c33 <__PRETTY_FUNCTION__.9544> "uv__async_io") at assert.c:92
#3  0x00007f27f8000612 in __GI___assert_fail (assertion=assertion@entry=0x11d1c11 "n == sizeof(val)", 
    file=file@entry=0x11d1bf5 "../deps/uv/src/unix/async.c", line=line@entry=136, 
    function=function@entry=0x11d1c33 <__PRETTY_FUNCTION__.9544> "uv__async_io") at assert.c:101
#4  0x0000000000ece71e in uv__async_io (loop=0x18a0e00 <default_loop_struct>, 
    w=0x18a0fc8 <default_loop_struct+456>, events=<optimized out>) at ../deps/uv/src/unix/async.c:136
#5  0x0000000000edd8e8 in uv__io_poll (loop=loop@entry=0x18a0e00 <default_loop_struct>, timeout=0)
    at ../deps/uv/src/unix/linux-core.c:380
#6  0x0000000000ecefb9 in uv_run (loop=0x18a0e00 <default_loop_struct>, mode=UV_RUN_ONCE)
    at ../deps/uv/src/unix/core.c:354
#7  0x0000000000d73e50 in StartNodeInstance (arg=<synthetic pointer>, this=<optimized out>)
    at ../src/node.cc:4230
#8  node::Start (argc=4, argv=0x305ebc0) at ../src/node.cc:4307
#9  0x00007f27f7ff3b15 in __libc_start_main (main=0x727ea0 <main(int, char**)>, argc=4, 
    ubp_av=0x7ffc8259bdf8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7ffc8259bde8) at libc-start.c:274
#10 0x0000000000728109 in _start ()
(gdb) frame 4
#4  0x0000000000ece71e in uv__async_io (loop=0x18a0e00 <default_loop_struct>, 
    w=0x18a0fc8 <default_loop_struct+456>, events=<optimized out>) at ../deps/uv/src/unix/async.c:136
136         assert(n == sizeof(val));
(gdb) info locals
val = <optimized out>
wa = 0x18a0fc0 <default_loop_struct+448>
buf = "\340\\7\003\000\000\000\000\000\353\026\005\227\237\266\203\260\261\n\003\000\000\000\000\060]8\003\000\000\000\000p\b\006\003\000\000\000\000`Q\n\003\000\000\000\000\060\263\a\003\000\000\000\000\004\000\000\000\000\000\000\000\220\205Y\202\374\177\000\000F\n\211\000\000\000\000\000\000\217\n\003\000\000\000\000\321\n\331Ó+\000\000\220\205Y\202\374\177\000\000\324f\212\000\000\000\000\000\200\206Y\202\374\177\000\000\260\261\n\003", '\000' <repeats 12 times>, "`Q\n\003\000\000\000\000\200\206Y\202\374\177\000\000Y\216\332\000\000\000\000\000\020\000\000\000\000\000\000\000\002", '\000' <repeats 23 times>, "p\b\006\003\000\000\000\000\370"...
n = 0
r = <optimized out>
__PRETTY_FUNCTION__ = "uv__async_io"
```

so unfortunately, r is not readable, but from the man page for read() you can see a return value of 0 is for EOF.

**Comment by rgagnon24** [comment]
> n is set = 0, if we break, we leave it at 0, so there is a possibility that n just is 0.

From the logic in the code, the only way n can remain as 0 is if read() returned 0 into r

**Comment by saghul** [comment]
Quick question: if you sidestep the issue like this, do async handles continue to work correctly?  That is, after the fd reported EOF, will it report data later on?  If the answer is no, we'll need to do more to recover from the situation.

**Comment by rgagnon24** [comment]
Good question, @saghul.  However the crash is random so I don't know what exactly causes it.    I don't know the inner workings of libuv well enough to know how your proposed situation would be handled.

The solution I proposed would simply cause the n==0 situation to be able to return in the same way it would had the system been compiled on non-linux machines.

That #ifdef block was added to remedy byte-alignment issues, but I wonder if the case of n being 0 when the block executed was just overlooked 4 years ago when the code was added?

**Comment by saghul** [comment]
That's the problem, that in theory that case is impossible, AFAIS. So it's very hard to verify the fix. According to the man page: http://man7.org/linux/man-pages/man2/eventfd.2.html read(2) can never return 0 on us because that eventfd is not a semaphore and is set to non-blocking.

**Comment by rgagnon24** [comment]
Interesting... would this mean that the fd being read is not an eventfd then?

**Comment by rgagnon24** [comment]
In reviewing it again, I guess r==-1 would be the other case allowing n to remain as 0.  I was not thinking about the possible <0 return value happening.

**Comment by bnoordhuis** [comment]
> Interesting... would this mean that the fd being read is not an eventfd then?

My working hypothesis for some time now is that something else closes/replaces libuv's eventfd, possibly a bug in the host application (other reports: #78, #401, there are more.)

Although in the case of https://github.com/abbr/deasync/issues/34, it's almost certainly caused by that module calling `uv_run()` recursively, something that isn't supported and will result in erratic behavior.

If you can get the assert to trigger reliably, `/proc/<pid>/fdinfo/<fd>` should tell you what kind of file descriptor it is.

**Comment by rgagnon24** [comment]
@bnoordhuis, I actually think now that it is a real eventfd.  It's just that errno EAGAIN is probably happening.  I wish the core dump file had errno in it but if it does, I don't know what command displays it.

Here's my new hypothesis...  EAGAIN happens.  This causes read to have -1 returned into r on first attempt through the for() when n is still 0.

EAGAIN can happen according to the man page when the resource is temporarily unavailable.  Why it would be unavailable I don't know.... maybe there's something new in the kernel that does that.  The server I am running on happens to be a virtual machine, so that could be playing a role, but doesn't seem likely.

The case of EAGAIN happening on first read() when n=0 will currently assert(), so adding the patch I had will cause it to skip that assert, and drop down to the remaining line as Windows would do anyhow.

**Comment by rgagnon24** [comment]
Also, the problem with checking /proc/pid/fdinfo... is that it is gone when the program asserts.

**Comment by saghul** [comment]
I think @rgagnon24 might be onto something.  If the eventfd has a spurious wakeup and we try to read from it `n` will be 0 and we'll assert because we break on `EAGAIN`.

How about something like this?

```
diff --git a/src/unix/async.c b/src/unix/async.c
index 393cdeb..884853e 100644
--- a/src/unix/async.c
+++ b/src/unix/async.c
@@ -119,8 +119,11 @@ static void uv__async_io(uv_loop_t* loop, uv__io_t* w, unsigned int events) {
     if (r != -1)
       break;
 
-    if (errno == EAGAIN || errno == EWOULDBLOCK)
+    if (errno == EAGAIN || errno == EWOULDBLOCK) {
+      if (n == 0)
+        return
       break;
+    }
 
     if (errno == EINTR)
       continue;
```

So, we skip all processing if the first read results in a `EAGAIN` error.

**Comment by txdv** [comment]
The optimized out is such a bummer ... I looked at the linux code though https://github.com/torvalds/linux/blob/5924bbecd0267d87c24110cbe2041b5075173a25/fs/eventfd.c#L224-L261

looks like it returns EAGAIN, it is the only path that returns a cnt = 0. So basically read was called, the eventfd is empty though (nobody sent an event) and since this is async, it just returns EAGAIN with n = 0...

Although i'm not sure why it would be empty if uv__async__io is being called...

**Comment by bnoordhuis** [comment]
Either it's a kernel bug or something else consumed the data first.  Occam's razor suggests it's the second one, or a google search for "eventfd EAGAIN" would turn up more bug reports.

We could remove the assert without ill effect but that would be "fixing" things without understanding the real cause.

**Comment by rgagnon24** [comment]
@saghul, I wonder if your solution of just `return` and avoiding the call to `wa->cb(loop, wa, n);` is advisable?

Even though the eventfd is apparently empty.... is it a good thing or a bad thing to skip the call to `wa->cb()` in that case?

@bnoordhuis, I agree it is probably not a kernel bug as well.  A google search for the assert message from libuv does come up in a few instances when used with different 3rd party packages, like socket.io, deasync, etc.  Whether each of those, or one of those is the cause of the issue isn't really known.

I also found this on stackoverflow: http://stackoverflow.com/questions/39275356/node-crashes-on-multiple-requests-at-same-time, but again.... what the root cause is remains a mystery, and I agree that it feels better to fix something when you know you are directly affecting the cause (like patching a tire without removing all the glass shards from the road you drive on)

I also wondered if some race condition might be going on.

**Comment by txdv** [comment]
@bnoordhuis under what circumstances is ->wd == -1?

**Comment by bnoordhuis** [comment]
@txdv You mean `wa->wfd`?  When using an eventfd instead of a pipe; it's the write end of the pipe otherwise.

**Comment by saghul** [comment]
Ping everyone.  I'd like to find a way forward here.  @bnoordhuis WDYT?  So far we know this happens every once in a while, but nobody has been able to reliably reproduce it, so I'm willing to compromise a bit here, in the spirit of providing software shich doesn't crash :-)

**Comment by bnoordhuis** [comment]
I'd worry that removing the assert turns a hard abort into a silent data corruption bug.  Making changes without understanding the root cause has a 50/50 chance of making things worse.

**Comment by bnoordhuis** [comment]
What other platforms do is irrelevant because they don't use the same mechanism as Linux.

**Comment by rgagnon24** [comment]
Why is there the `#ifdef` right there then?

**Comment by bnoordhuis** [comment]
I'm not following.  None of the code in src/unix/async.c runs on Windows.

**Comment by rgagnon24** [comment]
OK.  Duh.. Brain-Fart.  However the purpose of that block is purely for byte-alignment.  If there is nothing to align, then why not just pass it right by?

Leaving in the assert() code for non-zero is a good idea, but when it's zero, there is nothing to memcpy() anyhow.

**Comment by bnoordhuis** [comment]
Right, but the thing is that `uv__async_io()` should not be called when there is nothing to read from the eventfd.  The fact that `n == 0` sometimes indicates there is a bug somewhere.

That said, ultimately libuv doesn't care about the number of bytes read, the pipe/eventfd is really just a signalling mechanism.  Let me see if I can rework the logic in a way that would avoid this issue altogether.

**Comment by bnoordhuis** [comment]
See #1248.  On second thought this PR is okay too (but not a cleanup like #1248 is) because `n` is effectively unused, no real reason to assert on it.

**Comment by bnoordhuis** [comment]
Fixed in 5fc8aec, to be shipped in the next v1.x release.

**Pull request closed without merging**
