### PR TITLE
Fix arm test

### PR DESCRIPTION
**Pull request by santigimeno**
Fix flaky `test-tcp-writealot` and `fs_event_watch_dir` tests on arm.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
LGTM.  Duplicating code in `#if/#else` branches is kind of so-so but turning the timeout into a `#define` probably isn't worth it for a single line of code.

**Comment by santigimeno** [comment]
That was my initial intention but I was lazy. Let's do it right. PR updated

**Comment by bnoordhuis** [comment]
LGTM

**Comment by saghul** [comment]
LGTM. CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/122/

Hopefully those pesky Pi 1s pass the tests now!

**Comment by cjihrig** [comment]
LGTM, but it looks like there was still a timeout: https://ci.nodejs.org/job/libuv-test-commit-linux/136/nodes=pi1-raspbian-wheezy/console.

**Comment by santigimeno** [comment]
I had already tried yesterday and it did pass... I'll increase the timeout a little

**Comment by santigimeno** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/123/ with a timeout of 100ms

**Comment by cjihrig** [comment]
Jenkins failed this time around. Trying again: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/125/

**Comment by santigimeno** [comment]
They're green now with the new timeout. I'll merge later today if noone objects

**Comment by santigimeno** [comment]
Landed in https://github.com/libuv/libuv/commit/6d7d57a983c6054bca2730586f96d809bc64d867 and https://github.com/libuv/libuv/commit/29138058a5a51c6e9e187d1109494d29a948d529.

**Pull request closed without merging**
