### PR TITLE
Generate links to manpages from documentation

### PR DESCRIPTION
**Pull request by saghul**
R=@bnoordhuis (was it you who asked for this once?)

I may have missed some referencesd to system / library calls, but this should be the bulk of it.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
> (was it you who asked for this once?)

I don't think so but LGTM.  There are a  few other places that could be linkified (manned up?), like references to inet_ntop() and inet_pton() in pipe.rst and isatty() in misc.rst.

**Comment by saghul** [comment]
@bnoordhuis thanks :-) I didn't find anything relevant in pipe.rst, but I did on misc. Can you PTAL?

**Comment by bnoordhuis** [comment]
My bad, the bits I was thinking of were in misc.rst, not pipe.rst, and you got them.  LGTM!

**Comment by saghul** [comment]
Landed! Thanks Ben!

**Pull request merged**
