### PR TITLE
win: backport hrtime overflow fix from 1.x

### PR DESCRIPTION
**Pull request by jpcima**
This fix, backported from the branch `1.x`, prevents overflows from occurring in `uv_hrtime`.

The overflow issue has given me often reoccurring timing problems, which occurred under a virtualized Windows XP SP3 setting, but they were not observable in Windows 7.

### CODE REVIEW

**Comment by cjihrig** [comment]
The last 0.10 release was nearly 3 years ago. I don't foresee us making another release.

**Comment by jpcima** [comment]
Hi @cjihrig. Even then, Is there not the tinyest possibility of having this fix merged ?

The bug is at fault for a timing issue in a MIDI player program.
https://github.com/jpcima/midiplay/blob/dfbd5926f7432f147c8327d26e4497244f4a4a5b/sources/player/clock.cc#L37-L42
While I know XP is at this point a retro-computing relic and not supported, I would love for my software to have this support, which is only available in 0.x series.

**Comment by cjihrig** [comment]
I'll leave this open and see if any of the other maintainers are interested, but I'm personally -1.

As a side note - since you're using such an old version of libuv anyway, why not just float the patch yourself locally?

**Comment by saghul** [comment]
I'm -0. That said, as a retro-stuff enthusiast this hits me in a soft spot :-P So how about we merge it and allow those who still need / want to use this version to just get the tip of the branch?

FWIW recently a PR fixing support on macOS 10.7 was made, which, while not as old as XP, is an unsupported platform...

**Comment by cjihrig** [comment]
> So how about we merge it and allow those who still need / want to use this version to just get the tip of the branch?

I'm fine with that, since it doesn't involve me doing any work 😄 ... playing devil's advocate though - will it be our policy moving forward that the 0.10 branch (or any end-of-life branch) continues to receive these types of patches as long as people keep sending them?

> FWIW recently a PR fixing support on macOS 10.7 was made, which, while not as old as XP, is an unsupported platform...

My issue is less about Windows XP, and more about the 0.10 line being end of life.

**Comment by saghul** [comment]
> playing devil's advocate though - will it be our policy moving forward that the 0.10 branch (or any end-of-life branch) continues to receive these types of patches as long as people keep sending them?

I agree it's a slippery slope. One possibility would be to create a libuv-0.10 repo and add as collaborators those who are interedted in keeping it alive. WDYT?
 
> My issue is less about Windows XP, and more about the 0.10 line being end of life.

Sure, but in this case they are both somewhat intertwined, since v1.x dropped support for XP along it's lifetime, so those wanting XP support might find themselves stuck with either 0.10 or some random 1.XY.

**Comment by cjihrig** [comment]
> One possibility would be to create a libuv-0.10 repo and add as collaborators those who are interedted in keeping it alive. WDYT?

I don't feel strongly one way or another. I don't really have a good grasp on how many people want/need it either. Again, if it doesn't involve any work for me, it's hard to put up too much of a fight 😄

**Pull request closed without merging**
