### PR TITLE
QUEUE- and Unix-backend-related improvements, bugfixes, and tests

### PR DESCRIPTION
**Pull request by ahippo**
There are 10 commits in this pull request (as of now).
They are related but somewhat different in purpose and impact.
Some of them break the ABI (by changing struct layouts and sizes), most do not.
So it may be worth splitting the pull request into several smaller ones.
But it would be good to hear some feedback first.

All these changes are compile-tested on Linux only, so they can break builds for other OSes (but shouldn't).

Impact/severity of the changes.

sha | title | type | ABI impact | misc
--- | ------- | ---- | ---------- | ----
511fed6 | QUEUE: more type-checking, move queue.h to include/ | improvement | no | makes QUEUE public
3f90ba8 | QUEUE: convert macros to inline functions where possible | improvement | no |
7edc205 | QUEUE: introduce QUEUE_FOREACH_SAFE() and QUEUE_REMOVE_SAFE() | improvement | no | needed for subsequent patches
5392692 | QUEUE: poison prev/next pointers in QUEUE_REMOVE() and QUEUE_ADD() | improvement | no | crashes tests and libuv unless the following 2 patches are applied
1d0afd0 | unix: allow calling uv_fs_event_stop() from fs_event callback | bugfix | no |
21fb51b | unix: allow calling uv_close() from uv_{prepare,idle,check,async}_t callback | bugfix | **breaks ABI** |
caf20f9 | test: test that it's safe to call uv_close() from callbacks | test | no | for future regressions
2a0ec7e | test: test that uv_close() doesn't corrupt internal QUEUE | test | no | for changesets 1d0afd0 and 21fb51b, crashes/fails without these two changesets applied
cb5d8d7 | unix: use QUEUE for closing_handles | improvement | **breaks ABI** | |
a42e641 | unix: use QUEUE_FOREACH_SAFE() in process.c | improvement | no | |

### CODE REVIEW

**Comment by saghul** [comment]
Wow, a lot to look into, thanks! I'm about to leave on vacation, so hopefully @bnoordhuis has some time to look into this.

A quick note though: we promised a stable ABI throughout libuv v1.x so the ABI breaking changes would not be acceptable.

**Comment by ahippo** [comment]
> Wow, a lot to look into, thanks! I'm about to leave on vacation, so hopefully @bnoordhuis has some time to look into this.

Oh, ok.:)

> A quick note though: we promised a stable ABI throughout libuv v1.x so the ABI breaking changes would not be acceptable.

Can we merge ABI breaking things into master then?
Also, I consider an issue, fixed in 21fb51b, as quite serious.
Maybe you have some ideas on how to address it in an ABI-compatible manner?
(I followed the way Win-backend solves the issue)

**Comment by saghul** [comment]
> Can we merge ABI breaking things into master then?

Yep, that's ok.

> Also, I consider an issue, fixed in 21fb51b, as quite serious.

Can you demonstrate it in a test case? IIRC while we're "safe" because the close callback is called always on the next loop iteration, so nobody will ever hold a pointer to freed memory, for instance.

> Maybe you have some ideas on how to address it in an ABI-compatible manner?
> (I followed the way Win-backend solves the issue)

We also have some extra fields for avoiding ABI breakage, so feel free to get creative there and we can discuss the approach!

**Comment by ahippo** [comment]
>> Can we merge ABI breaking things into master then?

> Yep, that's ok.

Cool, I'll split the pull request in two parts then: for master and for v1.x.
(after we figure out what to do with 21fb51b)

>> Also, I consider an issue, fixed in 21fb51b, as quite serious.

> Can you demonstrate it in a test case? IIRC while we're "safe" because the close callback is called always on the next loop iteration, so nobody will ever hold a pointer to freed memory, for instance.

You're right that most likely we don't access already freed memory and thus are not susceptible to segfaults.
However, we still use an element not longer being in a queue for iterating over the queue, which can lead to strange consequences.
I came up with a test-case, which is implemented in 2a0ec7e "test that uv_close() ...": calling uv_close() on the current handle and on the next one from the handle's callback leads to a spurious callback invocation of an already stopped/closed next handle.
It's not that serious as accessing freed memory, of course, but is still quite undesirable.
And there could be other cases, that I can't see now.

Another point is that we can't merge queue poisoning patch (5392692), which should help in detecting libuv misuse bugs early, before fixing this QUEUE_REMOVE()-within-QUEUE_FOREACH() issue.

>> Maybe you have some ideas on how to address it in an ABI-compatible manner?
>> (I followed the way Win-backend solves the issue)

> We also have some extra fields for avoiding ABI breakage, so feel free to get creative there and we can discuss the approach!

Thank you for the hint!
I don't see "reserved[4]" in uv_loop_t and I'm not creative enough, so I came up with the following.
I need one additional pointer per queue -- I can try to dynamically allocate it and store it as a first element of the queue.
It's not the best thing to do as it complicates internal queue handling a bit, but should maintain the stable ABI.

**Comment by ahippo** [comment]
> I need one additional pointer per queue -- I can try to dynamically allocate it and store it as a first element of the queue.
> It's not the best thing to do as it complicates internal queue handling a bit, but should maintain the stable ABI.

So, I did this in 384235458e717f16ecfed8edc2a8d5c72b871339.
It should keep the ABI stable.
If the approach is fine, I'll go ahead and create two separate pull requests: for master and for v1.x, with some commits rearranged.
If you like the approach, should I redo 1d0afd0c07a4530b383d9d92152217ded63e2bb3 using it for consistency?

**Comment by ahippo** [comment]
A similar poisoning idea and queue_foreach issue was reported in
https://github.com/joyent/libuv/issues/646

**Comment by ahippo** [comment]
As this pull request conflicts with changes in v1.x, I've created a follow-up pull request #577 with those conflicts resolved.
So, I'm closing this pull request as it's now obsolete.

**Pull request closed without merging**
