### PR TITLE
Simplify code contribution with Gitpod

### PR DESCRIPTION
**Pull request by JesterOrNot**
image

Hello 😃 
This PR adds support an online IDE based on VSCode, it will build and test the entire project on open

Try it!
[Open in Gitpod](https://gitpod.io/#https://github.com/JesterOrNot/libuv)

### CODE REVIEW

**Comment by cjihrig** [comment]
I have similar feelings to https://github.com/kyleconroy/sqlc/pull/375#issuecomment-594823717.

**Comment by saghul** [comment]
-1. Online IDEs come and go, but libuv is eternal.

**Comment by JesterOrNot** [comment]
Fair enough. Thanks for the feedback! For what it's worth, this isn't just about one particular online IDE, but about a new idea called "dev-environment-as-code": i.e. fully-automating a project's development setup, to the point of being able to launch dev environments that are ready-to-code in just a few seconds, on any device. To me, this is a much better contribution experience than "please read the docs and fiddle with your OS for a few hours and then come back if you're still motivated".

**Comment by saghul** [comment]
libuv just requires cmake and make for compilation, that's hardly "fiddling with your OS for a few hours".

**Pull request closed without merging**
