### PR TITLE
build: CMake updates for tests/benchmarks and Windows install

### PR DESCRIPTION
**Pull request by mikefero**
__Tests/Benchmarks__
* made `BUILD_TESTING` and `BUILD_BENCHMARKING` on by default
* simplified common sources and test sources using GLOBs
* fixed a compilation issue with shared library tests

__Install__
* Added install mechanism for Windows
  * This will include PDB files (if present)

### CODE REVIEW

**Comment by mikefero** [comment]
This is a conversation continuation from here: https://github.com/libuv/libuv/pull/1850#issuecomment-395450653

**Comment by bnoordhuis** [comment]
> simplified common sources and test sources using GLOBs

Can you undo this change?  I followed what we do with other supported build systems, which is being explicit about what is compiled in.  Having a build file with significantly different logic from the other two makes it harder to keep them in sync.

> fixed a compilation issue with shared library tests

Can you go in more detail?  What was the issue?

**Comment by mikefero** [comment]
> Having a build file with significantly different logic from the other two makes it harder to keep them in sync.

Completely agree and tbh I wasn't thinking about that at the time; consider it reverted.

> Can you go in more detail? What was the issue?

`test/test-spawn.c` referenced the following functions
* make_program_args
* quote_cmd_arg
* make_program_env

Since these functions were part of the shared library the `USING_UV_SHARED=1` was necessary in order for the `uv_run_tests.exe` to link properly in Windows.

**Comment by bnoordhuis** [comment]
> test/test-spawn.c referenced the following functions

Ah, looks like someone snuck in some boundary violations.  Those functions aren't supposed to be exported.

I'd say a better way to fix that is to move the offending functions into a separate file and link that file into both the shared library and the executable.  We already do that with src/win/snprintf.c.

Can you make that change and also update uv.gyp and test/test.gyp?  Thanks.

**Comment by mikefero** [comment]
So I investigated this requested change further and quickly went down a rabbit hole. **uv__malloc** and **uv__free** internal functions are being used in **make_program_args** and **make_program_env**; separating out the offending functions won't be possible due to the use of these internal functions and are required for **uv_spawn** in `src/win/process.c`. Digging deeper it looks like this requirement (`USING_UV_SHARED=1`) was intentional and introduced 3 years ago in PR #444.

If you like I could perform the separation and create a `ifdef` called `UV_TESTING` that is only defined for the testing binaries and in place of **uv__malloc**/**uv__free** call **malloc**/**free** instead. `src/win/error.c` will also need to be included in the _uv_test_sources_ list in CMake as **make_program_env** also references references **uv_fatal_error**,

Thoughts?

**Comment by erw7** [comment]
I noticed this after creating #2085 for neovim. When this is merged I would like to fix #2085.

Could you apply https://github.com/mikefero/libuv/compare/cmake_updates...erw7:cmake_updates to this PR for MinGW?

**Comment by saghul** [comment]
@erw7 or @slurps-mad-rips do any of you think this is still relevant?

**Comment by slurps-mad-rips** [comment]
@saghul some of it, for sure. It needs some massaging as my next PR is to place the test sources more out of the way so readers can see what goes into libuv itself before the tests are involved.

**Pull request closed without merging**
