### PR TITLE
unix,win: simplify calculating polling timeout

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
@libuv/collaborators anyone?

**Comment by txdv** [comment]
This makes the implementation of uv_loop_handle almost equivalent, except that two fields are called differently: closing_handles and endgame_handles. In https://github.com/libuv/libuv/pull/1067 I noticed that too, but I didn't want to do it in that PR, because endgame_handles occures in a lot of places.

**Comment by saghul** [comment]
One thing at a time, Andrius.

**Comment by saghul** [comment]
We merge v1.x into master every so often, so yeah.

**Pull request merged**
