### PR TITLE
Do not convert \r to \r\n on Windows

### LINKED ISSUE #471: EOL conversion code causes incorrect behaviour of \r (carriage return) on Windows
The code at https://github.com/libuv/libuv/blob/v1.x/src/win/tty.c#L1883-L1900 outputs `\r\n` whenever a `\r` (CR) or `\n` (LF) is seen in the character stream. This is OK for LF, which effectively includes an implicit CR on \*nix systems. However, on *all* supported OS (including Windows), CR returns to the start of the line *without* a corresponding line feed, and libuv is breaking this. (Refs theintern/intern#454.)

I have a patch ready for this issue, just looking to see if I can get tests in place before submitting a PR. I may not succeed but I will at least send the patch.

### PR DESCRIPTION
**Pull request by csnover**
\r is a single carriage return without line feed on all platforms,
including Windows.

Fixes #471.

Sorry, I really would have liked to write tests to verify the logic change is correct but my C-fu is not strong enough to get tests into this thing since the function is static. I also wasn’t able to get a working Windows compilation environment in a reasonable period of time, so I’m leaning on CI to verify that I didn’t make any huge mistakes.

### CODE REVIEW

**Comment by piscisaureus** [comment]
LGTM

**Comment by saghul** [comment]
@csnover can you please adjust the commit log to the guidelines in CONTRIBUTING.md? Thanks!

**Comment by saghul** [comment]
Landed in 7cd0cd8 with a reworded commit message. Thanks!

**Pull request closed without merging**
