### PR TITLE
doc: update supported windows/msvs baseline

### PR DESCRIPTION
**Pull request by bnoordhuis**
Update the baseline from XP SP1 + MSVC 2008 to 8.1 + MSVS 2015.

Conversation starter.  I picked what MS itself supports.

Tangential: how does everyone feel about bumping OS X to 10.10?

### CODE REVIEW

**Comment by saghul** [comment]
-1. I still want people to use pyuv on Python 2, which is MSVC 2008.  Yes, I hate it too.

We already did this for v2 (including removing over 1k lines in the process!) but I'd like to keep it this way for v1.x.

**Comment by saghul** [comment]
> Tangential: how does everyone feel about bumping OS X to 10.10?

Can we delete some code in the process? :-)

**Comment by saghul** [comment]
For completeness, this is what happened a while ago for v2: https://github.com/libuv/libuv/commit/9d2c77e9f660ee8afb532a43e26b734e8cf95929 and https://github.com/libuv/libuv/commit/9329327a2acc963c6d2e5fc5faa8e8ec6d238703

**Comment by bnoordhuis** [comment]
MSVC 2008 it is then.  What about the XP => 8.1 bump?

**Comment by saghul** [comment]
> MSVC 2008 it is then. What about the XP => 8.1 bump?

That's even a bigger bump that what we have on master right now. AFAICT, we don't need anything from > Vista < 10,so Vista sounds like a good baseline, but I'm happy to bump it to at least 7. (I hate 8, but 10 is OK :-P)

Now, if we do this, we would be breaking backwards compatibilityin v1.x, wouldn't we?

**Comment by bnoordhuis** [comment]
I would prefer (but am not adamant) to stay on a version that is fully supported by its vendor.  Windows 7 is in its extended support phase, which means it only gets security fixes.

As to Vista: while we currently claim Windows XP is a tier 1 platform, in practice we don't test it, and neither would we test Vista.

> Now, if we do this, we would be breaking backwards compatibility in v1.x, wouldn't we?

So far I've only heard a single person claim that backwards compatibility (in a semver sense) is tied to platform support.

My take is that expecting your users to be on a supported version of their platform of choice is eminently reasonable.

**Comment by saghul** [comment]
Sounds reasonable. Dropping XP support, however, open the door for deleting a bunch of stuff. I'm not sure we want to backport that from master, do we?

**Comment by saghul** [comment]
Agreed.

**Comment by bnoordhuis** [comment]
Updated, PTAL.

**Pull request closed without merging**
