### PR TITLE
Bump vswhere helper 2

### PR DESCRIPTION
**Pull request by refack**
Fixes: https://github.com/libuv/libuv/issues/1476

### CODE REVIEW

**Comment by saghul** [comment]
Is this PR targeted at master intentionally?

**Comment by refack** [comment]
Quoting my comment on #1476:
> Fixed https://github.com/node4good/msvs-com-helper/issues/2 in https://github.com/node4good/msvs-com-helper/commit/e36955738fc341f8f8eea944f780368e74bb9ca3
> I'll open a PR to bump it's version here.
> FYI since it's a parameter rename I consider it `semver-major` but since it's an undocumented feature for `libuv` I think it can be backported as `semver-patch` with a line in the release notes.

So it's you call.

**Comment by saghul** [comment]
Please retarget it for v1.x

**Comment by refack** [comment]
@saghul, Done.

**Comment by saghul** [comment]
You can go ahead and merge it yourself now :-)

**Comment by bnoordhuis** [comment]
Ping @refack.

**Comment by refack** [comment]
Ack.

Quick sanity CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit-windows/578/

**Pull request merged**
