### PR TITLE
unix: fix ttl, multicast ttl and loop options on IPv6

### LINKED ISSUE #93: uv_udp_set_multicast_loop doesn't do anything on IPv6
While I was experimenting with multicast I found that the `uv_udp_set_multicast_loop` function wasn't failing but wasn't working either. After looking through the UDP source code, I found that `uv_udp_set_multicast_loop`, `uv_udp_set_multicast_ttl`, and `uv_udp_set_ttl` all set their respective IPv4 socket options, but have no logic to set their respective IPv6 socket options.

I believe the reason why this hasn't caused an error is that dual-stack is enabled by default and it's setting the options for the IPv4 packets but not for IPv6 packets.

The simpliest solution would be to make these three functions IP specific but then that would retract from the unification of IPv4 and IPv6.

Another solution be to drop `uv_udp_set_multicast_loop` and provide the option as a flag on bind, but then there is still the issue with the two ttl functions.

Overall I believe this problem should be handled with caution.

__Edit:__
I tried setting UV_UDP_IPV6ONLY and found that setsockopt still doesn't fail when setting IPv4 socket options on an IPv6 socket.

### PR DESCRIPTION
**Pull request by saghul**
Fixes #93

R=@bnoordhuis

/cc @MetaDark this should fix the issue you opened in #93 

PS: I'll do a follow-up commit for Windows.

### CODE REVIEW

**Comment by saghul** [comment]
Fun fact: no fix is required on Windows, since it was already correct there.

**Comment by saghul** [comment]
Tests pass: https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+containers/5/

**Comment by bnoordhuis** [comment]
LGTM although the test would be better if it wasn't a copy/paste job of the IPv4 test.

**Comment by saghul** [comment]
I thought that would suffice since we just need to test some valid and
invalid values. If you have any suggestions I can improve the tests.

**Comment by bnoordhuis** [comment]
I think you can move the bulk of the code into a shared function, e.g.

```c
static int do_test(const struct sockaddr* addr) {
  // ...
}

TEST_IMPL(udp_options) {
  struct sockaddr_in4 addr;
  ASSERT(0 == uv_ip4_addr("127.0.0.1", TEST_PORT, &addr));
  return do_test((const struct sockaddr*) &addr);
}

TEST_IMPL(udp_options6) {
  struct sockaddr_in6 addr;
  ASSERT(0 == uv_ip6_addr("::", TEST_PORT, &addr));
  return do_test((const struct sockaddr*) &addr);
}
```

**Comment by saghul** [comment]
@bnoordhuis you're right, fixed that now. Can you PTAL?

**Comment by bnoordhuis** [comment]
LGTM

**Comment by saghul** [comment]
Thanks Ben, landed in 2daee9f

**Pull request closed without merging**
