### PR TITLE
test: use RETURN_SKIP in spawn_setuid_setgid test

### PR DESCRIPTION
**Pull request by santigimeno**

### CODE REVIEW

**Comment by saghul** [comment]
LGTM

**Comment by cjihrig** [comment]
LGTM

**Comment by iWuzHere** [comment]
LGTM

**Comment by iWuzHere** [comment]
https://github.com/libuv/libuv/commit/897738b160cd5950503a96c9fd5b1e9aab92b0ff landed!

**Comment by saghul** [comment]
@iWuzHere @santigimeno now has commit superpowers ;-)

**Comment by santigimeno** [comment]
It's ok :)

**Pull request closed without merging**
