### PR TITLE
test: switch from old-style ASSERT macro to new-style ASSERT_EQ,... macros #2974

### PR DESCRIPTION
**Pull request by Pleuvens**
Using new-style macros makes it easier to debug test failures

### CODE REVIEW

**Comment by bnoordhuis** [comment]
LGTM at a quick skim but...

1. `ASSERT_EQ(0, ...)` can be replaced with `ASSERT_OK(...)`

2. Prefer `ASSERT_EQ(42, foo())` over `ASSERT_EQ(foo(), 42)` because the latter obscures the expected result when foo() is a long expression

Neither are real deal breakers though.

**Comment by Pleuvens** [comment]
Thank you for the feedback, I'll update that

**Comment by bnoordhuis** [comment]
@Pleuvens is this ready for review? I don't want it to bitrot. :-)

**Comment by Pleuvens** [comment]
Yes it is, sorry I should have updated

**Review by bnoordhuis — APPROVED** [review]
This is great, thanks!

**Comment by vtjnash** [comment]
This is really great and such a huge change! I see some warnings in the test builder (not many for such a big change!), particularly on 32-bit or Windows. Would you be willing to look into those? Just for a random example:
```
/home/runner/work/libuv/libuv/test/test-udp-create-socket-early.c: In function ‘run_test_udp_create_early_bad_bind’:
/home/runner/work/libuv/libuv/test/task.h:112:26: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  112 |   volatile type eval_a = (type) (a);                         \
      |                          ^
/home/runner/work/libuv/libuv/test/task.h:200:25: note: in expansion of macro ‘ASSERT_BASE’
  200 | #define ASSERT_NE(a, b) ASSERT_BASE(a, !=, b, int64_t, PRId64)
      |                         ^~~~~~~~~~~
/home/runner/work/libuv/libuv/test/test-udp-create-socket-early.c:92:3: note: in expansion of macro ‘ASSERT_NE’
   92 |   ASSERT_NE(fd, INVALID_FD);
      |   ^~~~~~~~~
/home/runner/work/libuv/libuv/test/task.h:113:26: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  113 |   volatile type eval_b = (type) (b);                         \
      |                          ^
/home/runner/work/libuv/libuv/test/task.h:200:25: note: in expansion of macro ‘ASSERT_BASE’
  200 | #define ASSERT_NE(a, b) ASSERT_BASE(a, !=, b, int64_t, PRId64)
      |                         ^~~~~~~~~~~
/home/runner/work/libuv/libuv/test/test-udp-create-socket-early.c:92:3: note: in expansion of macro ‘ASSERT_NE’
   92 |   ASSERT_NE(fd, INVALID_FD);
      |   ^~~~~~~~~
```

**Comment by Pleuvens** [comment]
Thank you for the feedback, I will. Should we create another issue or do I just need to create a new PR ?

**Comment by bnoordhuis** [comment]
A follow-up PR is fine.

**Comment by Pleuvens** [comment]
Hey, I hope you're all fine. Here is the follow-up PR: https://github.com/libuv/libuv/pull/4163

**Pull request merged**
