### PR TITLE
z/OS fixes on master

### PR DESCRIPTION
**Pull request by jBarz**
* Set langlvl to extended c99.
* fix udp ipv6 test cases.

### CODE REVIEW

**Comment by cjihrig** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/835/

**Comment by richardlau** [comment]
LGTM. Should the gyp changes go in `common.gypi`?

**Comment by jBarz** [comment]
Thanks @richardlau . 
I have consolidated all the common z/OS configurations into `common.gypi`.
@cjihrig : Can we haven one more CI run :-)?

**Comment by santigimeno** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/836/

**Comment by santigimeno** [comment]
Landed in https://github.com/libuv/libuv/commit/8149ac7d7abcfc3fadf289946f9aeb137efe199e and https://github.com/libuv/libuv/commit/d5870c71eace1ef5cad8a09599af3ab5f6ef72df. Thanks!

**Pull request closed without merging**
