### PR TITLE
macos: fix source not being followed when cloning (with fcopyfile)

### PR DESCRIPTION
**Pull request by lewis6991**
Alternative to #3941 

Use `fcopyfile()` instead of `copyfile()`

Fixes: #3940

### CODE REVIEW

**Review by bnoordhuis — APPROVED** [review]
Seems like a better approach to me.

**Comment by lewis6991** [comment]
I need to put this back into draft. Need to check a few things.

**Comment by lewis6991** [comment]
I've had another go at #3941 to use `clonefile()`, that might be a better route now.

**Comment by lewis6991** [comment]
Closing in favour of #3941

**Pull request closed without merging**
