### PR TITLE
doc: add trevnorris to maintainers

### PR DESCRIPTION
**Pull request by trevnorris**

### CODE REVIEW

**Review by santigimeno — APPROVED** [review]

**Review by richardlau — APPROVED** [review]

**Comment by vtjnash** [comment]
I would suggest @trevnorris should push this directly (rather than using Github squash) to preserve his signing tag of this commit. (and to push his signing key tag at the same time also)

**Comment by trevnorris** [comment]
@vtjnash Do you mean to do the steps of `gpg --export`, `git hash-object` then `git tag` using the hash, then pushing the tag? I'm happy to do it, but doesn't look like anyone else has.

**Comment by vtjnash** [comment]
Something like that, see the section about "Storing a maintainer key in Git" later in this file. For reference, you can see when I added a new one recently here: https://github.com/libuv/libuv/pull/3514#discussion_r820246186

**Comment by trevnorris** [comment]
Ah, I misinterpreted pushing the tag to libuv, not to my fork. Got it.

**Comment by trevnorris** [comment]
Think I did that correctly.

**Comment by vtjnash** [comment]
The commit looks good. I believe you still need to push the tag for pubkey-trevnorris to libuv

**Comment by trevnorris** [comment]
@vtjnash I pushed the tag to my fork at trevnorris/libuv. You want me to push the tag to libuv/libuv? I'm just making double sure since I don't see any other `pubkey-` tags in the libuv/libuv repo.

**Comment by bnoordhuis** [comment]
@trevnorris they're there, try e.g. `git show pubkey-bnoordhuis`

**Comment by bnoordhuis** [comment]
Yep, I'm seeing it after `git fetch --tags`.

**Pull request merged**
