### PR TITLE
doc: add santigimeno to maintainers

### PR DESCRIPTION
**Pull request by santigimeno**
Adding myself :)

### CODE REVIEW

**Comment by saghul** [comment]
LGTM, welcome onboard!

**Comment by iWuzHere** [comment]
LGTM!

**Comment by cjihrig** [comment]
LGTM

**Comment by bnoordhuis** [comment]
LGTM and welcome aboard.  You don't have a GPG key set up yet?

**Comment by santigimeno** [comment]
@bnoordhuis I don't have one. Should I?

**Comment by bnoordhuis** [comment]
Only if you'll be doing releases.

**Comment by santigimeno** [comment]
Finally I got me a GPG key. PR updated

**Comment by saghul** [comment]
Still LGTM :-)

**Comment by saghul** [comment]
(make sure you push the key object to the repo after this lands)

**Comment by santigimeno** [comment]
Landed on https://github.com/libuv/libuv/commit/ee111770068fecb7e3d151cb59c851cddc9bea72. Thanks everyone! :)

**Pull request merged**
