### PR TITLE
unix,win: merge timers implementation

### PR DESCRIPTION
**Pull request by bnoordhuis**
Merge src/unix/timer.c and src/win/timer.c into src/timer.c.  This
changes the Windows implementation from a binary tree to a binary
heap for generally better performance.

~~https://ci.nodejs.org/view/libuv/job/libuv-test-commit/922/ (infrastructure issue on macos buildbot)~~
~~https://ci.nodejs.org/view/libuv/job/libuv-test-commit/923/~~
~~https://ci.nodejs.org/view/libuv/job/libuv-test-commit/924/~~
https://ci.nodejs.org/view/libuv/job/libuv-test-commit/930/

### CODE REVIEW

**Comment by cjihrig** [comment]
Since this has already been done on master (https://github.com/libuv/libuv/commit/912d42b7285fc29869472106d1c736f34ac91521), do you anticipate any issues merging v1.x into master?

**Comment by bnoordhuis** [comment]
Oh, I'd forgotten about that.  There will be minor conflicts but nothing that's intractable.

**Comment by bzoz** [comment]
CI-in-node: https://ci.nodejs.org/view/libuv/job/libuv-in-node/34/

**Comment by cjihrig** [comment]
The CI failures are expected. Once https://github.com/nodejs/node/pull/21466 lands in Node, the results should be better.

**Comment by bnoordhuis** [comment]
Landed in 07955ed3...e4087ded.

**Pull request closed without merging**
