### PR TITLE
Simplify uv_cond_t and uv_rwlock_t

### PR DESCRIPTION
**Pull request by saghul**
After removing their fallbacks we can simplify their structure.

R= @libuv/collaborators 
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit-windows/122/

### CODE REVIEW

**Comment by bnoordhuis** [comment]
LGTM

**Comment by indutny** [comment]
This is a major change, right?

**Comment by saghul** [comment]
@indutny sure thing, but this master :-)

**Comment by indutny** [comment]
Yeah, just my 5 cents :)

**Pull request merged**
