### PR TITLE
WIP: test: fs_event_error_reporting

### PR DESCRIPTION
**Pull request by davisjam**
Towards MacOSX 12.

This commit introduces logging so we can see why
the timeout is occurring.

This PR will eventually fix one bug reported in #1910.

### CODE REVIEW

**Comment by davisjam** [comment]
@mhdawson Let's see if the answer is really obvious after a single CI run?

**Comment by mhdawson** [comment]
Launched https://ci.nodejs.org/view/libuv/job/libuv-test-commit-osx12/2/

**Comment by davisjam** [comment]
@mhdawson Can you start a CI for the full set of MacOS versions in the test matrix? (Including commit 6ce5bca which adds fine-grained logging). That will let us see time differences as a function of MacOS version, which should tell us what's going on here.

**For MacOSX 12**
During the 5 second timeout window, this test initializes 356 loops out of the 1024 it had planned and does not encounter an initialization failure to break the loop early ([code](https://github.com/libuv/libuv/blob/7f3069dd54949e480643c7f008452f292a868490/test/test-fs-event.c#L1024)).

*Statistics (ms/loop)*
- Min: 1.8
- Mean: 14
- Median: 18
- Max: 18.7

The distribution is bi-modal. Half of the loops took ~18 ms, and half took ~10 seconds.

*Explanation for test failure*
I see two possibilities:
1. On MacOSX 12, `uv_fs_event_init` or `uv_fs_event_start` is much slower than previous MacOS versions.
2. On MacOSX 12, `fs_event_error_reported` is not triggered (at all | as early as in previous versions).

*Additional data needed*
Logs from the rest of the MacOS test matrix would be informative.

*Raw data*
Here is the relevant output from this CI run.

```
not ok 48 - fs_event_error_reporting
# timeout
# Output from process `fs_event_error_reporting`:
# 100: Test started
# 194393: uv_loop_init loop iter 0/1024
# 5707151: uv_loop_init loop iter 1/1024
# 21364744: uv_loop_init loop iter 2/1024
# 30801637: uv_loop_init loop iter 3/1024
# 49195434: uv_loop_init loop iter 4/1024
# 58654446: uv_loop_init loop iter 5/1024
# 77133857: uv_loop_init loop iter 6/1024
# 86567646: uv_loop_init loop iter 7/1024
# 95972318: uv_loop_init loop iter 8/1024
# 114452717: uv_loop_init loop iter 9/1024
# 132941889: uv_loop_init loop iter 10/1024
# 151511361: uv_loop_init loop iter 11/1024
# 163367757: uv_loop_init loop iter 12/1024
# 172975158: uv_loop_init loop iter 13/1024
# 191424373: uv_loop_init loop iter 14/1024
# 198100411: uv_loop_init loop iter 15/1024
# 208301674: uv_loop_init loop iter 16/1024
# 217718235: uv_loop_init loop iter 17/1024
# 236169005: uv_loop_init loop iter 18/1024
# 245685626: uv_loop_init loop iter 19/1024
# 264237268: uv_loop_init loop iter 20/1024
# 273783228: uv_loop_init loop iter 21/1024
# 292241754: uv_loop_init loop iter 22/1024
# 300233764: uv_loop_init loop iter 23/1024
# 309749712: uv_loop_init loop iter 24/1024
# 328234035: uv_loop_init loop iter 25/1024
# 337770188: uv_loop_init loop iter 26/1024
# 356268734: uv_loop_init loop iter 27/1024
# 365791661: uv_loop_init loop iter 28/1024
# 384275067: uv_loop_init loop iter 29/1024
# 393825137: uv_loop_init loop iter 30/1024
# 402337531: uv_loop_init loop iter 31/1024
# 411951942: uv_loop_init loop iter 32/1024
# 430327819: uv_loop_init loop iter 33/1024
# 439819047: uv_loop_init loop iter 34/1024
# 458369937: uv_loop_init loop iter 35/1024
# 467944719: uv_loop_init loop iter 36/1024
# 477409609: uv_loop_init loop iter 37/1024
# 495852045: uv_loop_init loop iter 38/1024
# 504375476: uv_loop_init loop iter 39/1024
# 522778318: uv_loop_init loop iter 40/1024
# 541224573: uv_loop_init loop iter 41/1024
# 550650599: uv_loop_init loop iter 42/1024
# 569071218: uv_loop_init loop iter 43/1024
# 578499024: uv_loop_init loop iter 44/1024
# 597023483: uv_loop_init loop iter 45/1024
# 606514075: uv_loop_init loop iter 46/1024
# 624950704: uv_loop_init loop iter 47/1024
# 634377080: uv_loop_init loop iter 48/1024
# 652997022: uv_loop_init loop iter 49/1024
# 671416430: uv_loop_init loop iter 50/1024
# 689876641: uv_loop_init loop iter 51/1024
# 699405696: uv_loop_init loop iter 52/1024
# 717871193: uv_loop_init loop iter 53/1024
# 721931859: uv_loop_init loop iter 54/1024
# 740457050: uv_loop_init loop iter 55/1024
# 758856889: uv_loop_init loop iter 56/1024
# 777299283: uv_loop_init loop iter 57/1024
# 786788167: uv_loop_init loop iter 58/1024
# 805370453: uv_loop_init loop iter 59/1024
# 810622606: uv_loop_init loop iter 60/1024
# 829063992: uv_loop_init loop iter 61/1024
# 837999962: uv_loop_init loop iter 62/1024
# 843703409: uv_loop_init loop iter 63/1024
# 846732647: uv_loop_init loop iter 64/1024
# 865074315: uv_loop_init loop iter 65/1024
# 874772678: uv_loop_init loop iter 66/1024
# 893248739: uv_loop_init loop iter 67/1024
# 902735646: uv_loop_init loop iter 68/1024
# 921152663: uv_loop_init loop iter 69/1024
# 930568706: uv_loop_init loop iter 70/1024
# 949112972: uv_loop_init loop iter 71/1024
# 958681245: uv_loop_init loop iter 72/1024
# 977208260: uv_loop_init loop iter 73/1024
# 987584157: uv_loop_init loop iter 74/1024
# 1006160137: uv_loop_init loop iter 75/1024
# 1015561358: uv_loop_init loop iter 76/1024
# 1023513932: uv_loop_init loop iter 77/1024
# 1042070054: uv_loop_init loop iter 78/1024
# 1051571325: uv_loop_init loop iter 79/1024
# 1070061814: uv_loop_init loop iter 80/1024
# 1079527095: uv_loop_init loop iter 81/1024
# 1098108305: uv_loop_init loop iter 82/1024
# 1107720796: uv_loop_init loop iter 83/1024
# 1126182723: uv_loop_init loop iter 84/1024
# 1135719042: uv_loop_init loop iter 85/1024
# 1154254473: uv_loop_init loop iter 86/1024
# 1156506828: uv_loop_init loop iter 87/1024
# 1174951831: uv_loop_init loop iter 88/1024
# 1184506783: uv_loop_init loop iter 89/1024
# 1203010089: uv_loop_init loop iter 90/1024
# 1212492438: uv_loop_init loop iter 91/1024
# 1230984014: uv_loop_init loop iter 92/1024
# 1240513062: uv_loop_init loop iter 93/1024
# 1259003388: uv_loop_init loop iter 94/1024
# 1277307240: uv_loop_init loop iter 95/1024
# 1287677791: uv_loop_init loop iter 96/1024
# 1306171272: uv_loop_init loop iter 97/1024
# 1315611077: uv_loop_init loop iter 98/1024
# 1334016500: uv_loop_init loop iter 99/1024
# 1338925651: uv_loop_init loop iter 100/1024
# 1340762327: uv_loop_init loop iter 101/1024
# 1345530758: uv_loop_init loop iter 102/1024
# 1359751576: uv_loop_init loop iter 103/1024
# 1367811569: uv_loop_init loop iter 104/1024
# 1370632159: uv_loop_init loop iter 105/1024
# 1373655355: uv_loop_init loop iter 106/1024
# 1392106488: uv_loop_init loop iter 107/1024
# 1395879297: uv_loop_init loop iter 108/1024
# 1414161072: uv_loop_init loop iter 109/1024
# 1423640220: uv_loop_init loop iter 110/1024
# 1442020821: uv_loop_init loop iter 111/1024
# 1451428711: uv_loop_init loop iter 112/1024
# 1469973172: uv_loop_init loop iter 113/1024
# 1488447463: uv_loop_init loop iter 114/1024
# 1498057450: uv_loop_init loop iter 115/1024
# 1507549678: uv_loop_init loop iter 116/1024
# 1526035621: uv_loop_init loop iter 117/1024
# 1535413245: uv_loop_init loop iter 118/1024
# 1553914636: uv_loop_init loop iter 119/1024
# 1572415666: uv_loop_init loop iter 120/1024
# 1590955600: uv_loop_init loop iter 121/1024
# 1600161869: uv_loop_init loop iter 122/1024
# 1609698899: uv_loop_init loop iter 123/1024
# 1628141954: uv_loop_init loop iter 124/1024
# 1637635355: uv_loop_init loop iter 125/1024
# 1656127951: uv_loop_init loop iter 126/1024
# 1665648297: uv_loop_init loop iter 127/1024
# 1684163620: uv_loop_init loop iter 128/1024
# 1693646766: uv_loop_init loop iter 129/1024
# 1701461959: uv_loop_init loop iter 130/1024
# 1719892858: uv_loop_init loop iter 131/1024
# 1724275986: uv_loop_init loop iter 132/1024
# 1733800959: uv_loop_init loop iter 133/1024
# 1752208758: uv_loop_init loop iter 134/1024
# 1761695117: uv_loop_init loop iter 135/1024
# 1780081425: uv_loop_init loop iter 136/1024
# 1789518427: uv_loop_init loop iter 137/1024
# 1803599703: uv_loop_init loop iter 138/1024
# 1822011635: uv_loop_init loop iter 139/1024
# 1831517151: uv_loop_init loop iter 140/1024
# 1850029279: uv_loop_init loop iter 141/1024
# 1859459572: uv_loop_init loop iter 142/1024
# 1877822212: uv_loop_init loop iter 143/1024
# 1896331227: uv_loop_init loop iter 144/1024
# 1905689545: uv_loop_init loop iter 145/1024
# 1924117237: uv_loop_init loop iter 146/1024
# 1926411895: uv_loop_init loop iter 147/1024
# 1944811101: uv_loop_init loop iter 148/1024
# 1963348314: uv_loop_init loop iter 149/1024
# 1972719961: uv_loop_init loop iter 150/1024
# 1987805151: uv_loop_init loop iter 151/1024
# 1997479801: uv_loop_init loop iter 152/1024
# 2007739179: uv_loop_init loop iter 153/1024
# 2025603279: uv_loop_init loop iter 154/1024
# 2044264620: uv_loop_init loop iter 155/1024
# 2053665294: uv_loop_init loop iter 156/1024
# 2071912963: uv_loop_init loop iter 157/1024
# 2090375535: uv_loop_init loop iter 158/1024
# 2108920833: uv_loop_init loop iter 159/1024
# 2127384004: uv_loop_init loop iter 160/1024
# 2145894703: uv_loop_init loop iter 161/1024
# 2162940685: uv_loop_init loop iter 162/1024
# 2172537023: uv_loop_init loop iter 163/1024
# 2191081505: uv_loop_init loop iter 164/1024
# 2200796354: uv_loop_init loop iter 165/1024
# 2210990828: uv_loop_init loop iter 166/1024
# 2229326399: uv_loop_init loop iter 167/1024
# 2238811091: uv_loop_init loop iter 168/1024
# 2257434535: uv_loop_init loop iter 169/1024
# 2275917342: uv_loop_init loop iter 170/1024
# 2294389414: uv_loop_init loop iter 171/1024
# 2312770344: uv_loop_init loop iter 172/1024
# 2331222018: uv_loop_init loop iter 173/1024
# 2340793582: uv_loop_init loop iter 174/1024
# 2359295402: uv_loop_init loop iter 175/1024
# 2368750577: uv_loop_init loop iter 176/1024
# 2387236128: uv_loop_init loop iter 177/1024
# 2396644615: uv_loop_init loop iter 178/1024
# 2415105720: uv_loop_init loop iter 179/1024
# 2424550397: uv_loop_init loop iter 180/1024
# 2443015048: uv_loop_init loop iter 181/1024
# 2452555319: uv_loop_init loop iter 182/1024
# 2470989008: uv_loop_init loop iter 183/1024
# 2480424357: uv_loop_init loop iter 184/1024
# 2498968291: uv_loop_init loop iter 185/1024
# 2508744394: uv_loop_init loop iter 186/1024
# 2527288462: uv_loop_init loop iter 187/1024
# 2537268038: uv_loop_init loop iter 188/1024
# 2546809164: uv_loop_init loop iter 189/1024
# 2565246279: uv_loop_init loop iter 190/1024
# 2574604011: uv_loop_init loop iter 191/1024
# 2593087422: uv_loop_init loop iter 192/1024
# 2602485289: uv_loop_init loop iter 193/1024
# 2620859349: uv_loop_init loop iter 194/1024
# 2639362384: uv_loop_init loop iter 195/1024
# 2648783695: uv_loop_init loop iter 196/1024
# 2667198076: uv_loop_init loop iter 197/1024
# 2676666016: uv_loop_init loop iter 198/1024
# 2695108181: uv_loop_init loop iter 199/1024
# 2704477590: uv_loop_init loop iter 200/1024
# 2722891081: uv_loop_init loop iter 201/1024
# 2726763680: uv_loop_init loop iter 202/1024
# 2745406404: uv_loop_init loop iter 203/1024
# 2763508848: uv_loop_init loop iter 204/1024
# 2781912041: uv_loop_init loop iter 205/1024
# 2800412379: uv_loop_init loop iter 206/1024
# 2818931705: uv_loop_init loop iter 207/1024
# 2837513584: uv_loop_init loop iter 208/1024
# 2856004239: uv_loop_init loop iter 209/1024
# 2865412324: uv_loop_init loop iter 210/1024
# 2883821434: uv_loop_init loop iter 211/1024
# 2902311840: uv_loop_init loop iter 212/1024
# 2911835191: uv_loop_init loop iter 213/1024
# 2930292622: uv_loop_init loop iter 214/1024
# 2939807003: uv_loop_init loop iter 215/1024
# 2958226935: uv_loop_init loop iter 216/1024
# 2967734750: uv_loop_init loop iter 217/1024
# 2986130690: uv_loop_init loop iter 218/1024
# 2995595675: uv_loop_init loop iter 219/1024
# 3014127807: uv_loop_init loop iter 220/1024
# 3023477316: uv_loop_init loop iter 221/1024
# 3027769717: uv_loop_init loop iter 222/1024
# 3046144985: uv_loop_init loop iter 223/1024
# 3055659760: uv_loop_init loop iter 224/1024
# 3074173910: uv_loop_init loop iter 225/1024
# 3083730198: uv_loop_init loop iter 226/1024
# 3102248096: uv_loop_init loop iter 227/1024
# 3111640522: uv_loop_init loop iter 228/1024
# 3130047940: uv_loop_init loop iter 229/1024
# 3139555158: uv_loop_init loop iter 230/1024
# 3157977120: uv_loop_init loop iter 231/1024
# 3167461877: uv_loop_init loop iter 232/1024
# 3186009120: uv_loop_init loop iter 233/1024
# 3196223699: uv_loop_init loop iter 234/1024
# 3205647198: uv_loop_init loop iter 235/1024
# 3224112206: uv_loop_init loop iter 236/1024
# 3233851108: uv_loop_init loop iter 237/1024
# 3252320496: uv_loop_init loop iter 238/1024
# 3261800216: uv_loop_init loop iter 239/1024
# 3280212429: uv_loop_init loop iter 240/1024
# 3289696812: uv_loop_init loop iter 241/1024
# 3308112023: uv_loop_init loop iter 242/1024
# 3317536712: uv_loop_init loop iter 243/1024
# 3335956526: uv_loop_init loop iter 244/1024
# 3345483100: uv_loop_init loop iter 245/1024
# 3363871607: uv_loop_init loop iter 246/1024
# 3382397188: uv_loop_init loop iter 247/1024
# 3400920421: uv_loop_init loop iter 248/1024
# 3419445391: uv_loop_init loop iter 249/1024
# 3437924679: uv_loop_init loop iter 250/1024
# 3456362830: uv_loop_init loop iter 251/1024
# 3465859391: uv_loop_init loop iter 252/1024
# 3484218371: uv_loop_init loop iter 253/1024
# 3493798714: uv_loop_init loop iter 254/1024
# 3512309303: uv_loop_init loop iter 255/1024
# 3521416667: uv_loop_init loop iter 256/1024
# 3539910935: uv_loop_init loop iter 257/1024
# 3558279574: uv_loop_init loop iter 258/1024
# 3567775739: uv_loop_init loop iter 259/1024
# 3586292852: uv_loop_init loop iter 260/1024
# 3595795050: uv_loop_init loop iter 261/1024
# 3614186516: uv_loop_init loop iter 262/1024
# 3623835218: uv_loop_init loop iter 263/1024
# 3642326849: uv_loop_init loop iter 264/1024
# 3651801240: uv_loop_init loop iter 265/1024
# 3670234789: uv_loop_init loop iter 266/1024
# 3679716353: uv_loop_init loop iter 267/1024
# 3698207732: uv_loop_init loop iter 268/1024
# 3707738067: uv_loop_init loop iter 269/1024
# 3726229631: uv_loop_init loop iter 270/1024
# 3735906556: uv_loop_init loop iter 271/1024
# 3754272037: uv_loop_init loop iter 272/1024
# 3763777316: uv_loop_init loop iter 273/1024
# 3782246388: uv_loop_init loop iter 274/1024
# 3791768611: uv_loop_init loop iter 275/1024
# 3810300060: uv_loop_init loop iter 276/1024
# 3819871546: uv_loop_init loop iter 277/1024
# 3838399281: uv_loop_init loop iter 278/1024
# 3856933138: uv_loop_init loop iter 279/1024
# 3875472075: uv_loop_init loop iter 280/1024
# 3893967421: uv_loop_init loop iter 281/1024
# 3903529383: uv_loop_init loop iter 282/1024
# 3906057283: uv_loop_init loop iter 283/1024
# 3915569569: uv_loop_init loop iter 284/1024
# 3934006373: uv_loop_init loop iter 285/1024
# 3943466062: uv_loop_init loop iter 286/1024
# 3961989233: uv_loop_init loop iter 287/1024
# 3980369020: uv_loop_init loop iter 288/1024
# 3990006446: uv_loop_init loop iter 289/1024
# 3999529075: uv_loop_init loop iter 290/1024
# 4017936546: uv_loop_init loop iter 291/1024
# 4029771426: uv_loop_init loop iter 292/1024
# 4048365769: uv_loop_init loop iter 293/1024
# 4066888360: uv_loop_init loop iter 294/1024
# 4085382942: uv_loop_init loop iter 295/1024
# 4103859290: uv_loop_init loop iter 296/1024
# 4122241453: uv_loop_init loop iter 297/1024
# 4131760932: uv_loop_init loop iter 298/1024
# 4150250566: uv_loop_init loop iter 299/1024
# 4159752832: uv_loop_init loop iter 300/1024
# 4178253501: uv_loop_init loop iter 301/1024
# 4187779228: uv_loop_init loop iter 302/1024
# 4206187142: uv_loop_init loop iter 303/1024
# 4215717771: uv_loop_init loop iter 304/1024
# 4234371796: uv_loop_init loop iter 305/1024
# 4243906315: uv_loop_init loop iter 306/1024
# 4261913506: uv_loop_init loop iter 307/1024
# 4280354611: uv_loop_init loop iter 308/1024
# 4289875062: uv_loop_init loop iter 309/1024
# 4308392110: uv_loop_init loop iter 310/1024
# 4326875596: uv_loop_init loop iter 311/1024
# 4345313811: uv_loop_init loop iter 312/1024
# 4354837481: uv_loop_init loop iter 313/1024
# 4373325320: uv_loop_init loop iter 314/1024
# 4382680518: uv_loop_init loop iter 315/1024
# 4401286882: uv_loop_init loop iter 316/1024
# 4410728556: uv_loop_init loop iter 317/1024
# 4429096132: uv_loop_init loop iter 318/1024
# 4438645726: uv_loop_init loop iter 319/1024
# 4457172320: uv_loop_init loop iter 320/1024
# 4466521197: uv_loop_init loop iter 321/1024
# 4484935273: uv_loop_init loop iter 322/1024
# 4503462721: uv_loop_init loop iter 323/1024
# 4521940277: uv_loop_init loop iter 324/1024
# 4540502446: uv_loop_init loop iter 325/1024
# 4558918744: uv_loop_init loop iter 326/1024
# 4577413844: uv_loop_init loop iter 327/1024
# 4595868573: uv_loop_init loop iter 328/1024
# 4614414037: uv_loop_init loop iter 329/1024
# 4632898403: uv_loop_init loop iter 330/1024
# 4651356070: uv_loop_init loop iter 331/1024
# 4660897398: uv_loop_init loop iter 332/1024
# 4679393631: uv_loop_init loop iter 333/1024
# 4697933027: uv_loop_init loop iter 334/1024
# 4716451019: uv_loop_init loop iter 335/1024
# 4729725393: uv_loop_init loop iter 336/1024
# 4748297027: uv_loop_init loop iter 337/1024
# 4757797583: uv_loop_init loop iter 338/1024
# 4767477551: uv_loop_init loop iter 339/1024
# 4785947470: uv_loop_init loop iter 340/1024
# 4795399826: uv_loop_init loop iter 341/1024
# 4813905222: uv_loop_init loop iter 342/1024
# 4832423262: uv_loop_init loop iter 343/1024
# 4847466445: uv_loop_init loop iter 344/1024
# 4866005074: uv_loop_init loop iter 345/1024
# 4875497468: uv_loop_init loop iter 346/1024
# 4894037708: uv_loop_init loop iter 347/1024
# 4903557982: uv_loop_init loop iter 348/1024
# 4922134593: uv_loop_init loop iter 349/1024
# 4931572360: uv_loop_init loop iter 350/1024
# 4949977109: uv_loop_init loop iter 351/1024
# 4968367673: uv_loop_init loop iter 352/1024
# 4977834325: uv_loop_init loop iter 353/1024
# 4996301190: uv_loop_init loop iter 354/1024
# 5006003172: uv_loop_init loop iter 355/1024
# 5015517473: uv_loop_init loop iter 356/1024
```

**Comment by mhdawson** [comment]
Requested ci run: https://ci.nodejs.org/view/libuv/job/libuv-test-commit-osx/1047/
and one with osx12:  https://ci.nodejs.org/view/libuv/job/libuv-test-commit-osx12/4

**Comment by davisjam** [comment]
Thanks @mhdawson.

Though the CIs for OSX 10, 11, and 12 all used the same revision ("Revision: 6ce5bca, from origin/FixFSEventErrorReportingTest"), only the OSX12 prints my log statements.

I'm not super familiar with the history of this code. @cjihrig Any idea what might be going on? ifdefs enabled for MacOSX12 only or something?

**Comment by richardlau** [comment]
@davisjam The test runner only prints the output if the test fails or if it was listed in [`test/test-list.h`](https://github.com/libuv/libuv/blob/b9a0840307843ba0bfa85af95f8ade081c0fed5b/test/test-list.h#L440) using [`TEST_ENTRY_CUSTOM`](https://github.com/libuv/libuv/blob/e4087dedf837f415056a45a838f639a3d9dc3ced/test/runner.h#L69) with `show_output` set:
https://github.com/libuv/libuv/blob/e4087dedf837f415056a45a838f639a3d9dc3ced/test/runner.c#L293-L320

**Comment by davisjam** [comment]
Aw shucks, I forgot that. Thanks @richardlau!

**Comment by davisjam** [comment]
@mhdawson When you get a chance...894ee32 should cause output to appear on the other MacOS job.

**Comment by mhdawson** [comment]
New CI run: https://ci.nodejs.org/view/libuv/job/libuv-test-commit-osx/1049/

**Comment by cjihrig** [comment]
This seems to have stalled out. Jamie (or anyone else), feel free to pick this back up when you have the time.

**Pull request closed without merging**
