### PR TITLE
add uv_device_t as stream on windows and Linux to handle device I/O

### PR DESCRIPTION
**Pull request by zhaozg**

### CODE REVIEW

**Comment by zhaozg** [comment]
https://github.com/libuv/libuv/pull/19

**Comment by saghul** [comment]
Thanks for bumping this up!

**Comment by saghul** [comment]
lets try to handle this for v1.x

**Comment by Fishrock123** [comment]
@saghul is there a related issue, since this was closed out?

**Comment by saghul** [comment]
Sure: https://github.com/libuv/libuv/pull/379

**Pull request closed without merging**
