### PR TITLE
Merge 1.47.0 to master

### PR DESCRIPTION
**Pull request by vtjnash**
~Currently WIP, given that v1.46.0 hasn't merged yet, and this includes that PR too.~

### CODE REVIEW

**Comment by vtjnash** [comment]
If you haven't experienced it yet, the VSCode merge tool was very helpful with this (until I accidentally clicked the wrong button half way through test-fs.c and had to finish that one manually). It has an smart merge feature that can do a merge at the word level granularity, instead of lines, which meant it figured out most of the resolutions and I just needed to accept them.

**Comment by vtjnash** [comment]
ASAN expected to fail without the workaround (https://github.com/libuv/libuv/pull/4200#pullrequestreview-1731847813), but I try to avoid porting too many commits when it is easier to just make a release and merge all of them at once.

**Comment by vtjnash** [comment]
bump?

**Review by bnoordhuis — APPROVED** [review]
RSLGTM once more :-)

**Pull request merged**
