### PR TITLE
unix: use vfork instead of fork for uv_spawn

### PR DESCRIPTION
**Pull request by saghul**
When using vfork the calling thread is suspended until the child calls
execve, and they share the memory space, so we can replace the error
reporting mechanism from using a pipe to just writing to a variable.

I hope I understood vfork vs fork right. While tests pass here locally, lets discuss and have Jenkins test it. FWIW, the spawn benchmark improves significantly (average of 3 runs):

* v1.x: 733 spaws/sec
* vfork: 967 spaws/sec

R=@bnoordhuis

### CODE REVIEW

**Comment by saghul** [comment]
Forgot to mention, I ran the tests on Linux.

**Comment by saghul** [comment]
https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/54/

**Comment by bnoordhuis** [comment]
I don't think we can apply this change as-is.  Here is what the spec says about vfork():

> The vfork() function shall be equivalent to fork(), except that the behavior is undefined if the process created by vfork() either modifies any data other than a variable of type pid_t used to store the return value from vfork(), or returns from the function in which vfork() was called, or calls any other function before successfully calling _exit() or one of the exec family of functions.

In other words, you cannot do anything after the call to vfork() except call execve() or _exit().  It's not legal to call chdir(), setuid(), etc.  In those cases, we would have to fall back to fork().

Linux relaxes the standard restrictions a little but there is an important catch: fork handlers registered with pthread_atfork() don't run when you use vfork().  I think that alone is a significant enough change that it's probably better to just stick with fork().

We could perhaps add a UV_PROCESS_USE_VFORK flag but it should come with a big fat warning that you shouldn't use it unless you know what you're doing.

**Comment by saghul** [comment]
Damn, too good to be true, I guess :-( Thanks for having a look either way Ben! I don't feel like adding UV_PROCESS_USE_VFORK, it would make the code more complex for probably little gain. I just explored this idea out of curiosity.

**Comment by bnoordhuis** [comment]
Oh, for a bit of historic background: node used to use vfork() pre-libuv.  It was causing no end of trouble and the real world speed up was mostly negligible; the real cost center is normally the dynamic linker.

**Comment by saghul** [comment]
I see. Thanks again Ben. Closing then!

**Pull request closed without merging**
