### PR TITLE
win, build: add support for VS2019

### PR DESCRIPTION
**Pull request by bzoz**
This PR adds support for building libuv using VS2019.

To keep things more clear, it is split into two commits.

First commit makes libuv use the gyp code from the nodejs/node repo. It is the exact copy of the sourcecode from https://github.com/nodejs/node/tree/24a4f76709bd9edc8d86e9f3fb4d5e3c7d4c3d69/tools/gyp. This brings VS2019 (and Python 3) support to gyp used by libuv.

Second commit modifies vcbuild.bat to support new `vs2019` parameter. By default (with no parameter) VS2015 is used as before. This commit also updates the documentation, also mentioning how to build libuv on Windows using CMake.

From my testing CMake alrteady supports building libuv using VS2019, with all the test passing.

### CODE REVIEW

**Comment by bzoz** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1759/

**Comment by richardlau** [comment]
Bundling gyp seems contrary to the direction of https://github.com/libuv/libuv/pull/2682. The version of gyp from nodejs/node doesn’t support z/os.

**Comment by saghul** [comment]
Indeed this goes in the opposite direction as #2682 so my vote here would be for not landing this.

**Comment by bzoz** [comment]
No point in keeping this open

**Pull request closed without merging**
