### PR TITLE
kqueue: replace EV_OOBAND handling with EVFILT_EXCEPT + NOTE_OOB

### PR DESCRIPTION
**Pull request by juanarbol**
Refs: https://github.com/libuv/libuv/issues/3947

### CODE REVIEW

**Comment by juanarbol** [comment]
> I assume the filter here should be EVFILT_READ and EV_OOBAND added to the flags.
https://github.com/libuv/libuv/issues/3947#issue-1659280874

I think it is right. Currently, `EVFILT_READ` filter is being applied only for `POLLIN`.
https://github.com/libuv/libuv/blob/d4ab6fbba4669935a6bc23645372dfe4ac29ab39/src/unix/kqueue.c#L381

Should we consider includeing `EVFILT_READ` for `POLLPRI`?

**Comment by bnoordhuis** [comment]
That seems more correct than passing 0. `EVFILT_EXCEPT` + `NOTE_OOB` would be better still but is not universally supported (macos, openbsd, dragonflybsd, but not freebsd; don't know about netbsd)

**Comment by juanarbol** [comment]
@bnoordhuis at least macOS is happy -and maybe openbsd, dragonflybsd-, not fully convinced that this patch is gonna break anything as `EV_SET` seems to be fine w/ "invalid args" as libuv ignores the errors.

> Luckily (?) this bit of code ignores errors when doing a pollpri, so I guess that's why the test passes:
> https://github.com/libuv/libuv/blob/7a68f5ab4b3b7a4aada44ffa0f7addc295174c7b/src/unix/poll.c#L47
https://github.com/libuv/libuv/issues/3947#issue-1659280874

**Comment by juanarbol** [comment]
ping @bnoordhuis

**Review by bnoordhuis — APPROVED** [review]
Thanks, CI seems happy.

**Comment by santigimeno** [comment]
This is breaking `FreeBSD`: https://ci.nodejs.org/job/libuv-test-commit-freebsd/2186/nodes=freebsd13-x64/console. /cc @juanarbol

**Comment by bnoordhuis** [comment]
Right, we no longer have a freebsd buildbot. I'll revert this change.

**Comment by bnoordhuis** [comment]
#4623

**Pull request merged**
