### PR TITLE
test: fix android build error.

### PR DESCRIPTION
**Pull request by kod21236**
Do not compile 'tty_pty' test for android.

### CODE REVIEW

**Comment by saghul** [comment]
LGTM

**Comment by cjihrig** [comment]
Code changes LGTM, but is the change in file permissions necessary?

**Comment by saghul** [comment]
@cjihrig good catch! it's certainly not necessary.

**Comment by kod21236** [comment]
Thank you for review. I remove unnecessary file permissions.

**Comment by cjihrig** [comment]
Android isn't tested, but CI to make sure it doesn't break anything else: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/89/

**Comment by cjihrig** [comment]
Landed in 791c817891fdfde806a3814e1eeed94502eb56b8. Thanks!

**Pull request closed without merging**
