### PR TITLE
some lintings

### PR DESCRIPTION
**Pull request by fperrad**
this set of patches solves problems found with a lint tool.

I try to have a commit per kind of problem.

### CODE REVIEW

**Comment by cjihrig** [comment]
Some of the changes look good. I'm not sure what, if any, history there is in linting the libuv code. What linter is this from? Is linting something that could become part of the PR process here?

**Comment by saghul** [comment]
I'm -0 here. Do any of these changes fix any actual issue? We have stayed away from linting tools because they add noise to git history. IMHO we either go all-in with linting and make it part of landing PRs and lint the existing code in a single go, or we don't. IIRC previous attempts at finding settings for clang-format which we like have not been very succesful.

**Comment by kthelgason** [comment]
IMO some of these changes, 57db694 specifically, seem really unnecessary.

**Comment by fperrad** [comment]
About tools:
I use a linter from [Gimpel](http://www.gimpel.com).
`clang-format` is not a linter, but it is a code formatter. `clang-tidy` is a linter.
If you need a code formatter, my advice is AStyle (see this example of setting [astylerc](https://gist.github.com/fperrad/32b9f9e4a5cad78808aa07fec3d72a23)).

About commits in this PR:
I understand that you think some of them are not valuable.
You could cherry pick the good ones or I could update my PR.

**Comment by saghul** [comment]
@libuv/collaborators thoughts?

**Comment by cjihrig** [comment]
@saghul I agree with your comment about picking a style and doing it all at once, or not doing it at all.

**Comment by iWuzHere** [comment]
Agree with @cjihrig and @saghul

**Comment by saghul** [comment]
Ok, let's close then.

**Pull request closed without merging**
