### PR TITLE
unix,win: add uv_fs_statfs()

### PR DESCRIPTION
**Pull request by cjihrig**
Fixes: https://github.com/libuv/libuv/issues/2386

### CODE REVIEW

**Comment by saghul** [comment]
Looking good so far!

**Comment by santigimeno** [comment]
LGTM

**Comment by cjihrig** [comment]
Added the rest of the missing pieces. PTAL.

CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1476/

**Comment by cjihrig** [comment]
CI after resolving conflicts and squashing: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1478/

**Pull request merged**
