### PR TITLE
windows: simple compilation warnings

### PR DESCRIPTION
**Pull request by carenas**
while doing a crosscompile using latest gcc-7 with --host=x86_64-w64-mingw32

### CODE REVIEW

**Comment by cjihrig** [comment]
Did you intentionally target master instead of the v1.x branch?

**Comment by carenas** [comment]
yes, because I though it will be easy to cherry-pick into v1.x whatever is relevant and ABI neutral, that way.

FWIW I did locally cherry-pick this change into v1.x and it is IMHO safe there as well, except that there is a second copy of the RB_GENERATE_STATIC macro in timer.c which will need to be added.

Will provide and independent PR for that if you are interested

**Comment by cjihrig** [comment]
Generally, we target everything that can go into libuv 1.x.x at the `v1.x` branch, and only things that break API/ABI go into `master`. Periodically, `master` is updated from `v1.x` (for example, #1520).

**Comment by carenas** [comment]
created PR #1542 for the v1.x branch, not sure if merging this as well would help or hinder the merge though

**Comment by cjihrig** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/740/

**Comment by cjihrig** [comment]
Landed on master in https://github.com/libuv/libuv/commit/884dd9f1be4e74d31d498ffbbc7db8f4b434815a. Thanks!

**Pull request closed without merging**
