### PR TITLE
win: remove duplicated code when processing fsevents

### PR DESCRIPTION
**Pull request by saghul**
R=@libuv/collaborators

### CODE REVIEW

**Comment by saghul** [comment]
CI: https://ci.nodejs.org/job/libuv+any-pr+multi/275/

**Comment by bnoordhuis** [comment]
While you're here, I believe I spotted an out-of-bounds write in the block right above:
```c
               if (size) {
                 long_filenamew = (WCHAR*)uv__malloc(size * sizeof(WCHAR));
                 if (!long_filenamew) {
                   uv_fatal_error(ERROR_OUTOFMEMORY, "uv__malloc");
                 }
 
                 size = GetLongPathNameW(filenamew, long_filenamew, size);
                 if (size) {
                   long_filenamew[size] = '\0';
                 } else {
                   uv__free(long_filenamew);
                   long_filenamew = NULL;
                 }
               }
```
`long_filename` has `0..size-1` elements but the trailing nul is stored at position `size`.

**Comment by bnoordhuis** [comment]
LGTM BTW

**Comment by cjihrig** [comment]
LGTM

**Comment by saghul** [comment]
@bnoordhuis I'll take a look, thanks for the heads up! There is a pending PR in that area which I also need to review, I'll keep it in mind!

**Pull request merged**
