### PR TITLE
test,freebsd: skip udp_dual_stack if not supported

### PR DESCRIPTION
**Pull request by santigimeno**
By default, FreeBSD has net.inet6.ip6.v6only set to 1 (i.e., no dual stack
support). A new function can_ipv6_ipv4_dual is added to check its value and
decide whether `udp_dual_stack` test must be skipped or not.

### CODE REVIEW

**Comment by saghul** [comment]
Since this is only used in a single test, can you please inline it? The IPv6 support check has its own function since we use it in many places.

**Comment by santigimeno** [comment]
Should I also move it to the actual test file or can I leave it in `task.h`?

**Comment by saghul** [comment]
To the test file itself, please. Thanks a lot!

**Comment by santigimeno** [comment]
@saghul PR updated

**Comment by saghul** [comment]
CI: https://ci.nodejs.org/job/libuv+any-pr+multi/182/

**Comment by saghul** [comment]
Can you drop the inline?

~~~~
test/test-udp-ipv6.c:51:8: warning: extension used [-Wlanguage-extension-token]
static inline int can_ipv6_ipv4_dual() {
       ^
1 warning generated.
~~~~

Also, are any tests supposed to pass now on our CI? I don't see any test being skipped with the given message.

**Comment by santigimeno** [comment]
@saghul `inline` removed.
It's normal it does not show because the `udp_dual_stack` has already been skipped because of no loopback IPv6 support (https://github.com/libuv/libuv/issues/128#issuecomment-156114196)

**Comment by saghul** [comment]
LGTM

**Comment by saghul** [comment]
Landed in 4052c74, thanks Santi!

**Pull request closed without merging**
