### PR TITLE
CMake build

### PR DESCRIPTION
**Pull request by cjntaylor**
I've got a project that is using libuv but builds with CMake. While gyp does provide a CMake generator, I've found it difficult to integrate with other projects / CMake generators. I've handwritten a CMake build that aims for parity with the original gyp build. This allows tighter integration with projects that already use CMake.

I'd be happy to maintain this build against the gyp build if it is merged into the project. I've attempted to comment the build file to indicate what the various file lists contain with respect to the various platform targets and configurations. If there is something you'd like to see different, just let me know.

This merge request is just in case there is any interest in adding CMake as an additional build system for the project.

### CODE REVIEW

**Comment by saghul** [comment]
This comes up every now and then. I'm still -1 because we already support 2 build systems (you could say 3 with the MinGW Makefile).

If you look in the [wiki](https://github.com/libuv/libuv/wiki/Projects-that-use-libuv#other) there are already 2 projects providing CMake support for libuv.

**Comment by saghul** [comment]
@libuv/collaborators thoughts? Also, FWIW, this versions is way larger than the ones I've seen so far.

**Comment by bnoordhuis** [comment]
-0.  More maintenance work and it's almost as many lines of code as the autotools, gyp and mingw build scripts combined.

**Comment by cjihrig** [comment]
-1 because of the size and because you referenced some other projects in the wiki providing CMake support.

**Comment by indutny** [comment]
-1, maintenance price is too large.

**Comment by iWuzHere** [comment]
-1 from me, same reasons listed above

**Comment by saghul** [comment]
Sorry @cjntaylor the crowd has spoken. Feel free to create a repo and add your project to the wiki, and thanks for yopur willingness to contribute to libuv!

**Comment by cjntaylor** [comment]
No worries.  I needed it for my own purposes, just thought I'd share.

😅 Didn't realize those other projects in the wiki existed. I'll certainly add myself to the list.

For all of you who complained about size, 95% of that is boilerplate that never needs changing. Most of that provides useful features (RPATH support, cross platform install/uninstall, CMake find_package support, in-tree linking, etc). The only thing that'd have to change is the lists of files. Its very similar to Autotools from that perspective (although the straw-man to line count was quite humorous).

I was **volunteering** to maintain the new build for you, not asking you all to do it. I know adding more infrastructure adds complexity; it'd be rude for me to propose adding anything without providing help.

Anywho, libuv is fantastic and I'm happy to help; Let me know if you need help porting to gn/bazel 😛

**Comment by breznak** [comment]
@cjntaylor thanks for your contribution! I'm going to be using one of the cmake "forks". As a newbie to `libuv`, can you please provide some info which of the 3 "-cmake" alternatives I should use? Would you "three cmake guys" consider merging to a single fork?

**Pull request closed without merging**
