### PR TITLE
win,udp: fix error code returned by connect()

### PR DESCRIPTION
**Pull request by santigimeno**

### CODE REVIEW

**Comment by santigimeno** [comment]
> LGTM, but can the test be run on non-Windows platforms?

It can, but this is a specific Windows error where `connect()` returns an error when using `INADDR_ANY`. I'll enable the test on every platform and accept the `0` as return value as well.

**Comment by santigimeno** [comment]
Test updated

**Comment by santigimeno** [comment]
Ci: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/2041/

**Comment by cjihrig** [comment]
Landed in https://github.com/libuv/libuv/commit/13ca3bfae89511f9ad67c54b530c827fe092178b. Thanks!

**Pull request closed without merging**
