### PR TITLE
v1.41.1 release [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by vtjnash**
My first release attempt, so would appreciate if someone could check that this looks correct before I tag it

### CODE REVIEW

**Comment by vtjnash** [comment]
Is there a script for automating these steps?

**Comment by vtjnash** [comment]
Ah, I see I need to use https://github.com/libuv/libuv-release-tool (and also move to a machine with my GPG key), but does the commits otherwise look correct?

**Comment by vtjnash** [comment]
Note that z/OS is expected to be broken in CI on this security patch release due to https://github.com/nodejs/build/issues/2491, which will be fixed in v1.42.x

**Comment by cjihrig** [comment]
The commits do look OK, but yea, you should use the release tool. If you use the release tool, the only thing you'll need to account for is that it will include all of the other commits still on v1.x. At this point, I'm not sure that we need to worry about that though.

**Comment by vtjnash** [comment]
Alright, I have a better version now at https://github.com/vtjnash/libuv/releases/tag/v1.41.1 but need access to dist.libuv.org to finish publishing it

**Pull request closed without merging**
