### PR TITLE
win: CREATE_NO_WINDOW when stdio is not inherited

### LINKED ISSUE #1625: win: possible regression related to UV_PROCESS_WINDOWS_HIDE change
Here is a before/after of [win: let UV_PROCESS_WINDOWS_HIDE hide consoles ](https://github.com/libuv/libuv/commit/b21c1f900c55572917d64c5e208c3eb8850ffd18) via identical commits of MoarVM/Perl6 on Win10, where we can notice a change in how an inherited handle works:

##### before (output of child is seen)
```
C:\Users\nloga\foo>perl6 -e "my $proc = Proc::Async.new('cmd.exe','/c','dir'); my $promise = $proc.start; await $promise; say 'done'; say $promise.result"
 Volume in drive C has no label.
 Volume Serial Number is 22C4-E412

 Directory of C:\Users\nloga\foo

11/10/2017  02:40 PM    <DIR>          .
11/10/2017  02:40 PM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  32,038,256,640 bytes free
done
Proc.new(in => IO::Pipe, out => IO::Pipe, err => IO::Pipe, exitcode => 0, signal => 0, command => ["cmd.exe", "/c", "dir"])
```
##### after (output of child is -not- seen) 
```
C:\Users\nloga\foo>perl6 -e "my $proc = Proc::Async.new('cmd.exe','/c','dir'); my $promise = $proc.start; await $promise; say 'done'; say $promise.result"
done
Proc.new(in => IO::Pipe, out => IO::Pipe, err => IO::Pipe, exitcode => 0, signal => 0, command => ["cmd.exe", "/c", "dir"])
```

[irc discussion](http://logs.nodejs.org/libuv/2017-11-10#18:39:51.433)

It is possible [MoarMV/src/io/procops.c#L629](https://github.com/MoarVM/MoarVM/blob/87191078c38be29be16a0801963552f3455ea495/src/io/procops.c#L629) could be doing something wrong with UV_INHERIT_FD, but I'm not sure how to determine this (and hence give you a more pure example).

---

[This](https://github.com/haskell/process/blob/d17cda7356628f45e7e8a64b59324f84fe2e6e07/cbits/runProcess.c#L680-L684) hints that additional checks may be needed somewhere:
```
    if (sInfo.hStdInput  != GetStdHandle(STD_INPUT_HANDLE)  &&
        sInfo.hStdOutput != GetStdHandle(STD_OUTPUT_HANDLE) &&
        sInfo.hStdError  != GetStdHandle(STD_ERROR_HANDLE)  &&
        (flags & RUN_PROCESS_IN_NEW_GROUP) == 0)
            dwFlags |= CREATE_NO_WINDOW;   // Run without console window only when both output and error are redirected

```

### PR DESCRIPTION
**Pull request by ugexe**
Resolves #1625

### CODE REVIEW

**Comment by ugexe** [comment]
To clarify:

`CREATE_NO_WINDOW` does not appear compatible with inherited console handles (no console, and hence console handles, get created). MoarVM showed a regression post v1.15.0 because it uses inherited stdio handles by default, and -always- sets `UV_PROCESS_WINDOWS_HIDE`. The problem was not immediately obvious on nodejs because it defaults to stdio pipes, but indeed a deadlock can be shown with the right parameters:
`node -e "const cp = require('child_process'); { const bat = cp.spawn('cmd.exe', ['/k', 'dir'], { stdio: 'inherit', detached: false, windowsHide: true }); }"`

---

In the case of MoarVM this PR fixes the regression introduced in https://github.com/libuv/libuv/commit/b21c1f900c55572917d64c5e208c3eb8850ffd18

In the case of nodejs this PR should bring back the console 'blip' *but only if* `stdio: 'inherit'` is used, with the possible caveat (bonus) that it no longer deadlocks.

**Comment by cjihrig** [comment]
@bzoz do you have any thoughts on this?

**Comment by bzoz** [comment]
Sorry, was on vacations.

This sounds reasonable, since it solves regression in libuv. @ugexe could you add a test for this?

**Comment by ugexe** [comment]
@bzoz @cjihrig  I'm not sure how to write a test for this ( at this low of a level anyway ). Specifically the last step mentioned below:

---

```
  /* process setup to test */
  options.stdio[0].flags = UV_IGNORE;
  options.stdio[1].flags = UV_INHERIT_FD;
  options.stdio[1].data.fd = 1;
  options.stdio[2].flags = UV_INHERIT_FD;
  options.stdio[2].data.fd = 2;
  options.stdio_count = 3;
  options.flags = UV_PROCESS_WINDOWS_HIDE;
```

and then:

* spawn process -- expected to write '1' to stdout and '2' to stderr.

* check that stdout contains '1' and stderr eq '2' ( both would be empty before this PR )

**Comment by cjihrig** [comment]
> I'm not sure how to write a test for this ( at this low of a level anyway )

IIRC, I saw somewhere that you can make Node.js deadlock with this bug. Am I remembering correctly? If so, maybe a PR to Node adding a test case would be better than nothing. We're in the process of trying to get a CI job that tests libuv commits in Node.

**Comment by ugexe** [comment]
@cjihrig  

`node -e "const cp = require('child_process'); { const bat = cp.spawn('cmd.exe', ['/k', 'dir'], { stdio: 'inherit', detached: false, windowsHide: true }); }"`

Change `windowsHide` to `false` and it no longer deadlocks. But note that this is probably counting on some other node bug; `cmd.exe` up/down history list no longer works after running that with `windowsHide: false` until pressing Cntrl+C, possibly indicating an open handle? Either way I'm not sure it's a good test.

Technically tests exist as part of the Perl 6 spectests, but unfortunately we don't yet have the tooling/infrastructure to apply a build system our ( MoarVM ) dependencies.

**Comment by cjihrig** [comment]
> But note that this is probably counting on some other node bug; cmd.exe up/down history list no longer works after running that with windowsHide: false until pressing Cntrl+C, possibly indicating an open handle?

I'm not a Windows user, but `/k` executes `dir` and then gives you back a command prompt (which doesn't exit). My guess would be that the up/down key presses are being sent to the child process that is still running, and pressing `Ctrl+C` kills it, bringing you back to your original command prompt, with working up/down history.

**Comment by bzoz** [comment]
The Node issue is here https://github.com/nodejs/node/issues/17824

Just gave it a spin. The "deadlock" is because of `/k`, if you change it to `/c` it exits correctly. Nonetheless, `dir` output is lost, so there is a genuine bug here.

Also, if you redirect stdout to a pipe or file it works, so this is a `tty` specific thing. I don't know if we can reliably test this in CI. I'm compiling Node with this change on my box right now, I'll test manually if this fixes that issue.

Anyhow, libuv CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/698/

**Comment by bzoz** [comment]
I had to rebase this on top of `libuv/v1.x` to make it work with Node. One of the Node tests is failing:
```
C:\...\node>Release\node.exe test\parallel\test-tty-get-color-depth.js
tty.js:83
    throw new errors.SystemError(ctx);
    ^

Error [ERR_SYSTEM_ERROR]: bad file descriptor: EBADF [uv_tty_init]
    at new WriteStream (tty.js:83:11)
    at Object.<anonymous> (C:\...\node\test\parallel\test-tty-get-color-depth.js:31:21)
    at Module._compile (module.js:666:30)
    at Object.Module._extensions..js (module.js:677:10)
    at Module.load (module.js:578:32)
    at tryModuleLoad (module.js:518:12)
    at Function.Module._load (module.js:510:3)
    at Function.Module.runMain (module.js:707:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:683:3
```

**Comment by bzoz** [comment]
This PR fixes the issue in Node, CI failures are unrelated and the failing test is currently also failing on master. So, this LGTM.

**Comment by ugexe** [comment]
Thanks for the help digging into this

**Comment by bzoz** [comment]
Sorry, forgot about this. I'll land this tomorrow. 

CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/709/

**Comment by bzoz** [comment]
Landed in https://github.com/libuv/libuv/commit/48ba92c93ecdb3719436f44fe26c81a5d2da642f

**Comment by santigimeno** [comment]
@bzoz, yeah will do that

**Comment by santigimeno** [comment]
Landed in https://github.com/libuv/libuv/commit/491848a0ad20031fa26bfb4a934b82293e0f7732 with the correct author.

**Comment by bzoz** [comment]
Thanks!

**Pull request closed without merging**
