### PR TITLE
Fix cmake build for Windows, with cmake versions before v3.14

### PR DESCRIPTION
**Pull request by drfloob**
Before v3.14, cmake throws the following error:

```
CMake Error at third_party/libuv/CMakeLists.txt:663 (install):
  install Library TARGETS given no DESTINATION!
```

I confirmed on Windows 7 and Windows Server 2016, with about a dozen
cmake versions between 3.7 and 3.22. I also confirmed that the
DESTINATION `${CMAKE_INSTALL_LIBDIR}` is populated with a valid path.

### CODE REVIEW

**Comment by cjihrig** [comment]
@drfloob can you please resolve the newly introduced conflicts.

**Comment by drfloob** [comment]
@cjihrig Done, thanks. PTAL.

**Review by cjihrig — APPROVED** [review]
LGTM

I ran the Jenkins based CI in addition to GitHub actions: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/2202/. It doesn't look like any of the failures are related to the changes here, but @richardlau would you sign off for the IBM platforms.

**Review by richardlau — APPROVED** [review]
I think this looks okay. I've opened https://github.com/libuv/libuv/issues/3349 for the z/OS test failures (which are unrelated to this PR).

**Comment by SylvainCorlay** [comment]
Hello @cjihrig this appears to cause some regressions in that `uv.lib` (the import library for `uv.dll`) is not installed anymore.

**Comment by SylvainCorlay** [comment]
I opened https://github.com/libuv/libuv/pull/3414 to revert this PR.

**Comment by vtjnash** [comment]
I opened https://github.com/libuv/libuv/pull/3415 to fix that regression

**Pull request merged**
