### PR TITLE
Readable/writable states fixes

### LINKED ISSUE #1798: What logic is behind uv_is_readable/writable applicable to tcp sockets?
* **Version**: 1.15
* **Platform**: windows, unix(android) 

Hi, I observe behavior that looks confusing to me with these functions.

1. On windows when connection has been reset by remote side, in read callback that got error socket still remains readable and writable. But obviously we can do nothing else with it except close.

2. On windows immediately after uv_shutdown(), socket becomes not writable. 
But on unix(in my case it was Android, but source file for that is the same) after uv_shutdown(), it's still writable.

I check latest source files and have not found any changes related to those flags.

### PR DESCRIPTION
**Pull request by OleksandrKvl**
Fixes uv_is_readable(), uv_is_writable() states for sockets.
However, it doen't deal with uv_write() errors, so following scenario is possible:
connect - read_stop - write - error(ECONNRESET) - still writable & readable.
As I understand, to handle this we need to check write error code, and update R/W state only for some of them. Do we need this?
Closes #1798 .

### CODE REVIEW

**Comment by cjihrig** [comment]
This has conflicts, and hasn't gotten any reviews in nearly a year and a half. I'm going to close this out for now.

**Comment by bnoordhuis** [comment]
I feel kind of bad, I completely missed @OleksandrKvl opened this pull request.

**Comment by saghul** [comment]
Their first ever too :-(

**Comment by vtjnash** [comment]
The conflicts are very trivial. Should I push a rebased version & make a new PR? It looks like the OP did a nice job with creating tests too.

**Comment by cjihrig** [comment]
@vtjnash that sounds like a good idea - unless @OleksandrKvl is interested in picking it back up now that it seems to have some eyes on it.

**Comment by OleksandrKvl** [comment]
I don't use libuv now, so do whatever you think is appropriate with this PR :)

**Pull request closed without merging**
