### PR TITLE
Add missing casts.

### PR DESCRIPTION
**Pull request by PeterJohnson**
Essentially all of these are the void* variety.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
None of these are necessary in C since `void*` can be coerced to any pointer type.  Are you building libuv as a C++ project?

**Comment by PeterJohnson** [comment]
Yes, I happen to be, and you're right they're not necessary for C, but basically the project is C++ clean otherwise.  Also, a fairly large number of places in libuv already have similar casts, so this improves consistency across the project.  Plus, I think it's good C coding style (admittedly that's personal opinion).

**Comment by bnoordhuis** [comment]
> a fairly large number of places in libuv already have similar casts

If you mean in src/win, they're remnants of when Visual Studio used to complain if you didn't put them in (really because it treated C as if it was C++ minus a few keywords.)

I'll leave this PR open so other collaborators can chime in but I personally don't see it happening, it's not idiomatic C.

**Comment by cjihrig** [comment]
If we don't need it, I'd say -1 to avoid the git history churn.

**Comment by PeterJohnson** [comment]
I'm not sure what you mean by "git history churn"?  Isn't the whole point of git to track history and changes?  It makes a change, yes, but I'm not seeing that it will cause increased long term churn of multiple changes.  Once the cast is there, it should be fine essentially forever.  The reason I upstreamed this PR is that without it merged, it makes tracking upstream changes much more difficult than it needs to be (due to merge conflicts) when the code is so close to compiling cleanly with C++ anyway.

I noticed that I rolled some const changes in here too (e.g. strchr returns a const char*).  Is that something that would be considered for merging even if the void* casts aren't?

**Comment by bnoordhuis** [comment]
> e.g. strchr returns a const char*

It doesn't, it returns a mutable pointer. :-)

If you're referring to `uv__basename_r()`, I think that's an acceptable change.

**Comment by cjihrig** [comment]
> I'm not sure what you mean by "git history churn"?

Sorry, I just meant that it makes tools like `git blame` a little less useful for what seems like no gain.

**Comment by bnoordhuis** [comment]
> If you're referring to uv__basename_r(), I think that's an acceptable change.

@PeterJohnson Do you want to follow up on this or should we close this out?

**Comment by cjihrig** [comment]
No follow up. Closing for now.

**Pull request closed without merging**
