### PR TITLE
Combined fixes for uv_spawn stdio mangling

### PR DESCRIPTION
**Pull request by saghul**
This PR combines #224 (Sam's patch + my test) and #226 (alternate implementation by yours truly and a test).

R=@bnoordhuis
/cc @sam-github

### CODE REVIEW

**Comment by saghul** [comment]
CI: https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/76/

**Comment by saghul** [comment]
@bnoordhuis thanks for the review, pushed a few fixups, can you PTAL?

**Comment by bnoordhuis** [comment]
LGTM with a question.

**Comment by saghul** [comment]
@bnoordhuis added a couple more fixups, if you have no further comments I'll rebase and land later. Thanks Ben!

**Comment by bnoordhuis** [comment]
LGTM. I would perhaps not assign the result of dup2 to fd on the off chance that dup2 has a bug but that's bordering on paranoid.

**Comment by saghul** [comment]
The CI was as unhappy as before (https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/78/) so I landed it.

I made a small change while landing: https://github.com/libuv/libuv/pull/309/files#diff-993e2d1f75ebf418adfbe81df8050a95R289 it's possible that we get a legit -1 there, so fcntl would fail with EBADF.

Thanks again for the review Ben!

**Comment by sam-github** [comment]
@saghul Thanks for finishing this up, I wasn't able to dig myself out of my work pile far enough to finish this.

**Comment by saghul** [comment]
No problem Sam!

**Pull request merged**
