### PR TITLE
socket_created_cb callback for TCP/UDP

### PR DESCRIPTION
**Pull request by ssrlive**
Give users a chance to do something when the socket is created.

To develop VPN software in the Android system, we must call the [VpnService.protect(int socket)](https://developer.android.com/reference/android/net/VpnService#protect(int)) function on a new created socket as early as possible before the socket connecting to the remote server, otherwise the subsequent call to the connect function will fail.

Here is an example [toyvpn](https://android.googlesource.com/platform/development/+/refs/tags/android-platform-12.1.0_r3/samples/ToyVpn/src/com/example/android/toyvpn/ToyVpnConnection.java#169)

Please accept this patch, It's very important for Android VPN developing. thanks.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
This PR changes the ABI (the struct sizes) - i.e., it's backwards incompatible - so it can't land in the v1.x branch.

And, expectation management, there are no plans for a v2 release.

**Comment by ssrlive** [comment]
Hi @bnoordhuis , I have lookup this field 

https://github.com/libuv/libuv/blob/730e07e2f77a4001bdf6894112271c926399f5a8/include/uv.h#L441-L444

can we use this union to do our business?

**Comment by ssrlive** [comment]
Hi @vtjnash , can you review this patch and merge it?

**Comment by ssrlive** [comment]
Hi @bnoordhuis and @vtjnash , can you review this patch and merge it?

**Comment by bnoordhuis** [comment]
Full disclosure: I'm not thrilled about adding a new API for a single user for a single platform.

I might change my mind if other people run into the same issue, or if another maintainer thinks it's a good idea, but all other things being equal, I'd rather not merge this.

**Pull request closed without merging**
