### PR TITLE
include: define _GNU_SOURCE

### PR DESCRIPTION
**Pull request by RaisinTen**
_GNU_SOURCE needs to be defined before including the other header files.

Fixes: https://github.com/libuv/libuv/issues/3164

### CODE REVIEW

**Comment by vtjnash** [comment]
It would be better not to put this in the public header, but only in the files that need it. In particular, this turns on all compiler and posix extensions, overriding the `-std=gnu90` flag on the command line. Or we could include these function prototypes directly.

**Comment by RaisinTen** [comment]
@vtjnash Thanks for the review. Moved it to the affected files. PTAL.

**Comment by bnoordhuis** [comment]
I realize we do this ifndef-then-define dance in one or two other files but it shouldn't be necessary neither there nor here because we already build with `-D_GNU_SOURCE`.

I'm fairly sure the reporter from #3164 (or the project he's building) uses some custom build script, in which case it's their responsibility to ensure the proper flags are used.

**Comment by RaisinTen** [comment]
@bnoordhuis I agree, these are not necessary if we are building with that option.
I have opened another PR to remove the `_GNU_SOURCE` macros here: https://github.com/libuv/libuv/pull/3168
Closing this in favour of that.

**Pull request closed without merging**
