### PR TITLE
udp: call udp recv_cb with 0 and NULL when nread is 0

### PR DESCRIPTION
**Pull request by theanarkh**
Be consistent with `uv__udp_recvmmsg`.

### CODE REVIEW

**Comment by saghul** [comment]
What does this try to fix? The only difference with the current code path is the peer address would now be null, right?

**Comment by theanarkh** [comment]
Yes. it is not a bug.  I noticed this when I looked at the Node.js code, so I submit this pr to change the return value of `recv_cb`.
image

**Comment by saghul** [comment]
IMHO this would be a change in behavior. Right now you can tell the difference between an empty datagram and a returned buffer, with your change that won't be the case...

**Comment by theanarkh** [comment]
Oh. We can send 0 byte by UDP socket.

**Pull request closed without merging**
