### PR TITLE
Ignore ERROR_ACCESS_DENIED in one more case.

### PR DESCRIPTION
**Pull request by lschoe**

### CODE REVIEW

**Comment by lschoe** [comment]
Ignoring ERROR_ACCESS_DENIED also in this place is essential to make multiple tests for [winloop](https://github.com/Vizonex/Winloop) (Windows port of uvloop) pass. Specifically tests involving processes for the record:
```
test_process.Test_UV_Process
test_process.TestAsyncio_UV_Process
test_process.Test_UV_Process_Delayed
test_pipes.Test_UV_Pipes
```
There are about 15 errors/failures in total, typical error message:
```
RuntimeError: unable to perform operation on <WriteUnixTransport closed=True reading=False 0x29fb9100210>; the handler is closed
```
This seems to be one more case for ignoring ERROR_ACCESS_DENIED, which is also done in a few other cases in `src/win/pipe.c` and in `src/win/process.c`. 

With this change, Winloop passes all of 500+ uvloops unit tests (except for some tests that are not relevant on Windows).

**Comment by saghul** [comment]
Is it possible to reproduce the problem with a libuv-only test case?

**Comment by lschoe** [comment]
I'm not sure how to do that right now. Would have to "investigate" the call chain etc. Maybe you have a suggestion when you inspect one of the test cases, like this one (same test for uvloop and winloop):

https://github.com/Vizonex/Winloop/blob/main/tests/test_process.py#L633-L648

The test result is:
```
======================================================================
ERROR: test_communicate (test_process.TestAsyncio_UV_Process.test_communicate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Berry\Documents\GitHub\Winloop\tests\test_process.py", line 646, in test_communicate
    exitcode, stdout = self.loop.run_until_complete(task)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "winloop\loop.pyx", line 1520, in winloop.loop.Loop.run_until_complete
  File "C:\Users\Berry\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Berry\Documents\GitHub\Winloop\tests\test_process.py", line 641, in run
    stdout, stderr = await proc.communicate(data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Berry\AppData\Local\Programs\Python\Python312\Lib\asyncio\subprocess.py", line 201, in communicate
    stdin, stdout, stderr = await tasks.gather(stdin, stdout, stderr)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Berry\AppData\Local\Programs\Python\Python312\Lib\asyncio\subprocess.py", line 152, in _feed_stdin
    self.stdin.write(input)
  File "C:\Users\Berry\AppData\Local\Programs\Python\Python312\Lib\asyncio\streams.py", line 346, in write
    self._transport.write(data)
  File "winloop\handles/stream.pyx", line 689, in winloop.loop.UVStream.write
  File "winloop\handles/handle.pyx", line 159, in winloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <WriteUnixTransport closed=True reading=False 0x196ad2dbc10>; the handler is closed
```
Or, can you point to some test cases for the other cases where ERROR_ACCESS_DENIED is ignored, like this one maybe:

https://github.com/libuv/libuv/blob/5d1ccc12c48099d720bb39f7430c480a52953039/src/win/pipe.c#L229

**Review by vtjnash — CHANGES_REQUESTED** [review]
I am fairly certain this indicates some sort of bug or memory error in winloop, as ReadFile should not return this error code

**Comment by lschoe** [comment]
Hi @vtjnash, I have tried to find out what we could do differently in winloop but I couldn't find any other solution then ignoring ERROR_ACCESS_DENIED as done in this PR.

So, here's a minimal program that shows the problem:
```python
import sys, subprocess, asyncio, winloop
winloop.install()

asyncio.run(asyncio.create_subprocess_exec(sys.executable, stdin=subprocess.PIPE))
print(f'{proc.stdin=}')
```
In winloop, the pipe for `stdin` is created using a "socket pair" from a call to `uv_pipe()` as we don't have Unix sockets on Windows. The use of `uv_pipe()` seems to be the intended libuv substitute for Unix sockets, and thus gives a nice alternative on Windows.

The problem is that we get a closed transport, which shouldn't be the case:
```
proc.stdin=<StreamWriter transport=<WriteUnixTransport closed=True reading=False 0x230ca2ea2b0>>
```

The transport is closed indeed because of an ERROR_ACCESS_DENIED from this call to `ReadFile()`:
https://github.com/libuv/libuv/blob/5d1ccc12c48099d720bb39f7430c480a52953039/src/win/pipe.c#L1406-L1411
Here, the `handle->handle` resulted from this call to `uv__get_osfhandle()`:
https://github.com/libuv/libuv/blob/5d1ccc12c48099d720bb39f7430c480a52953039/src/win/pipe.c#L2373-L2374
Now, it turns out that if we check `access.AccessFlags & FILE_READ_DATA` for `os_handle` and `file`, we get different results. We use a call like this for `os_handle` (and another one for `file`):
https://github.com/libuv/libuv/blob/5d1ccc12c48099d720bb39f7430c480a52953039/src/win/pipe.c#L2413-L2417
For `file` we get `1`, but for `os_handle` we get `0`.

Hence, read access is not granted for `os_handle`, while it was for `file`. We have created `file` with the right kind of access in winloop, so I don't see what we could do differently.

Does this give you an idea for a solution?

**Comment by saghul** [comment]
Have you tried using uv_socketpair?

**Comment by lschoe** [comment]
I think I've tried that before, even before `uv_pipe`. I've now tried it again, using this call:
```
err = uv.uv_socketpair(uv.SOCK_STREAM, 0, fds, uv.UV_NONBLOCK_PIPE, uv.UV_NONBLOCK_PIPE)
```
The call succeeds, but the returned file descriptors lead to problems, like this kind of errors:
```
OSError: [Errno 9] bad file descriptor
```
Even a call like `os_set_inheritable(fds[0], False)` fails. Do you know how compatible the (WSA)socket file descriptors returned by `uv_socketpair()` are for use with calls like `os_set_inheritable`?

**Comment by vtjnash** [comment]
I think you might have to upgrade to libuv v2 (master) to use that reliably. The current v1.x is mostly for bug-compatibility with nodejs and may not work well with process spawn (something that nodejs is known to be somewhat bad at doing). It is only tested with Julia, and thus only on v2. I am away from a computer today, but can try to provide more specifics tomorrow. One possible note is that you should not necessarily automatically close a pipe when you read an error or EOF (that is a nodejs mistake), but only in certain conditions which includes checking !writable.

**Comment by saghul** [comment]
Oh, I use it for subprocesses in my small JS runtime and haven't run into issues yet!

Can you elaborate on that case about EOF?

**Comment by lschoe** [comment]
As for the possible note mentioned above by @vtjnash about not automatically closing a pipe, that looks similar to what I've tried before in winloop. See https://github.com/Vizonex/Winloop/commit/e292e029c91ca839e3093ae8b9749cbbfc1256e4, keeping the connection open for writing (but stop reading). But this kind of solution looks somewhat undesirable to me.

Isn't there a way to avoid the ERROR_ACCESS_DENIED by giving read access (to make the 0-read succeed)? 
Trying
```python
err = uv.uv_pipe(fds, uv.UV_NONBLOCK_PIPE, uv.UV_NONBLOCK_PIPE | uv.UV_READABLE_PIPE)
```
leads to ERROR_ACCESS_DENIED already early on, at this point
https://github.com/libuv/libuv/blob/5d1ccc12c48099d720bb39f7430c480a52953039/src/win/pipe.c#L299-L309
Could there be a way to fix things at this stage?

**Comment by vtjnash** [comment]
> Oh, I use it for subprocesses in my small JS runtime and haven't run into issues yet!

Way off topic here, but these bugs only manifest if you do something non-trivial: 1. libuv hijacks stdin/stderr/stdio (aka 0, 1, 2) and makes them non-blocking. When starting another application, this often leads to problems since they application that gets started doesn't expect this. (Sometimes it also changes it back to blocking, and libuv doesn't expect that and it leads to deadlock in libuv instead which is unfortunately but unfortunately posix doesn't supply anything that works better). This can be avoided by passing a `dup` handle instead. In libuv it also leaks the tty fd handle in some cases, which I have been meaning to fix recently; 2. nodejs does not support passing the same pipe to two different fd (e.g. using the same pipe for stdout/stderr) and attempting it just results in bad behaviors. It is easily avoided just by not doing that, but it means it cannot quite implement a shell (this is why we introduced `uv_pipe`); 3. nodejs defaults to autoclose when hitting EOF, which causes issues similar to this one 4. nodejs defaults to immediately starting a read, even if the user doesn't want the data from the pipe (this one might have been fixed?), which also causes issues similar to this one; 5 nodejs only supports v1.x currently, while libuv master has support for directly using Windows HANDLE objects which adds some overhead issues and limits scalability

> we still can't receive more

FWIW, this comment is false. A TTY will often still receive more after an EOF.

I still don't think this PR is correct. We never handle any other error in any other place like this, as it is up to the application to handle read results correctly, and not to incorrectly autoclose a handle.

If I had the ability to do IO all over again, I would make 2 separate application handles for the separate read and write directions. Being unable to do that though, I recommend checking `uv_is_writable` in your `keep_open` decision as well as checking on the handle type. This will still give you some issues on FreeBSD (where pipes are bi-directional), but generally keeps things like this more sane. (Aside: for FreeBSD support, we would need to implement a way of watching for write errors, which is a feature that has been requested in libuv quite often, but nobody has yet tried to figure out how to do it correctly for every platform and file type)

**Comment by lschoe** [comment]
Thx for your elaborations @vtjnash! As for the `keep_open` option, that will only be used on Windows, so no need to worry about FreeBSD or anything else. Checking `uv_iss_writable` is a helpful refinement indeed.

However, about changing the PR as suggested above, that is, ignoring a 0-read if there is no access, looks to me as in the same category as how ERROR_ACCESS_DENIED is treated in various other places in `libuv/src/win`. If we look at all
[repo:libuv/libuv ERROR_ACCESS_DENIED](https://github.com/search?q=repo%3Alibuv%2Flibuv%20ERROR_ACCESS_DENIED&type=code) occurrences, there are also instances where we do a `CreateFileW()` call and then "back up" if it turns out that we don't have read or write access. See in particular how ERROR_ACCESS_DENIED is handled throughout `win/pipe.c`. 

Dropping a 0-read attempt upon ERROR_ACCESS_DENIED seems a natural thing to do, especially because we have these situations where we don't want to read anything at all (only write things) as you are pointing out above--as we don't have separate read and write directions.

NB: this way of handling ERROR_ACCESS_DENIED applies to both 0-reads in `win/pipe.c`, for the overlapped case and non-overlapped case.

**Comment by vtjnash** [comment]
Completely ignoring an error (resulting in losing the read error) is very different from having multiple code path to do roughly the same thing that selects between them. Having `keep_open` exist anywhere (especially if not existing everywhere) sounds like a portability issue foot-gun, but that is up to you, since libuv tries to be only about mechanisms and not policies.

**Comment by vtjnash** [comment]
Your case (this PR) is more akin to https://github.com/libuv/libuv/blob/4e310d0f90af29e699e2dedad5fa0dcee181a7cc/src/win/fs.c#L870-L872 where this flag gets explicitly remapped to EBADF (handle not open for reading). We might consider applying that same error remapping here too, since EBADF is more accurate than EPERM. However, we map this one incorrectly on v1.x for legacy support of nodejs. It is fixed on master (a877ca243).

**Comment by lschoe** [comment]
Yes, thx a lot @vtjnash. Fiddling with `keep_open` was indeed not desirable. I've now found the place where the `uv.UV_EPERM` you are mentioning above "surfaces" in winloop, and there I'll skip closing the stream.

Specifically, for the record, replacing this line calling `sc._on_eof()`, see https://github.com/Vizonex/Winloop/blob/00fd2897f64d7a00ba5675a08419d0b8d4b94e3b/winloop/handles/stream.pyx#L821
by
```python
 if system.PLATFORM_IS_WINDOWS and nread == uv.UV_EPERM:
      sc._stop_reading()
  else:
      sc._on_eof()
```
makes all tests pass;)

We're sticking with v1.x for winloop because uvloop is also still on v1.x.

So, no need for this PR anymore.

**Pull request closed without merging**
