### PR TITLE
unix: Fix null pointer check

### PR DESCRIPTION
**Pull request by rikardfalkeborn**
Check the pointer to the allocated memory, not the pointer to the
pointer of the allocated memory. Previously, a failed allocation of
*envitems would lead to a NULL pointer dereference.

### CODE REVIEW

**Comment by addaleax** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1842/

**Comment by rikardfalkeborn** [comment]
I just checked and the corresponding windows code had the same issue, ok to put it in the same PR (I just pushed it, so maybe I should've asked sooner)?

**Comment by addaleax** [comment]
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1843/

@rikardfalkeborn This is just fine :+1:

**Comment by cjihrig** [comment]
Landed in ad618647...cd11c2b1. Thanks!

**Pull request closed without merging**
