### PR TITLE
misc: enable stalebot

### PR DESCRIPTION
**Pull request by saghul**
Let The Purge begin!

/cc @libuv/collaborators WDYT? (happy to bikeshed on the values, I just picked some that I felt were ok as a starting point)

### CODE REVIEW

**Comment by bnoordhuis** [comment]
GH announced this today: https://github.com/actions/stale

**Comment by saghul** [comment]
Is actions still in beta though? I don't mind which one we use (I've been using stalebot succesfully on other projects) as long as it achieves the same :-)

**Comment by bnoordhuis** [comment]
Yes, it's still in beta. I think what Actions has going for it is that we wouldn't need to grant a third party write access to our repo. GH already has that implicitly.

OTOH, stalebot requires only limited permissions (RW access to issues and pull requests, IIRC) so the scope for damage in case it strays or goes rogue is limited.

**Comment by bnoordhuis** [comment]
Oh, I hadn't noticed it won't be publicly available until mid-November (I'm in the beta program.) Okay, stalebot it is then. :-)

**Comment by saghul** [comment]
🚀  let's see how it goes!

**Comment by zbjornson** [comment]
:-\ Is closing something like #2133 (which still exists, has a clear description, difficult resolution) because it's old a good resolution? I get closing issues without activity and without clear repros, but I don't get closing ones like #2133 as much. Maybe a libuv maintainer just needs to manually go through open issues to add not-stale where appropriate.

(I'm not a major stakeholder here, so I defer entirely to y'all, but I generally prefer using reply templates+manually closing instead of stalebot.)

**Comment by bnoordhuis** [comment]
Thoughts on disabling stalebot for issues tagged enhancement or feature-request? I revived a couple manually (let's hope stalebot is smart enough to understand that manual removal of the tag means it's not stale - we'll find out) but I didn't go through all of them.

**Comment by saghul** [comment]
@zbjornson Leaving a comment will mark them as not stale, and then we can tag them with no-stale and they'll never be stale again.

> Thoughts on disabling stalebot for issues tagged enhancement or feature-request?

I don't know. If 0 progress was made in 3 months I guess they actually are stale, are they now? Anyway, happy to test either way and refine as we move forward.

**Comment by bnoordhuis** [comment]
Yeah, I can see both benefits and drawbacks to keeping them open.

Aside: I noticed we don't actually have a no-stale label. I'll go create one. :-)

**Comment by vtjnash** [comment]
> 3 months I guess they actually are stale

3 months seems pretty short, given the pace of code adoptions in libuv, to assume that something is actually stale, although an appropriately long amount of time to bump it and maybe get it moving again

**Pull request merged**
