### PR TITLE
windows: compilation warnings

### PR DESCRIPTION
**Pull request by carenas**
closes #1530

### CODE REVIEW

**Comment by bnoordhuis** [comment]
@bzoz @refack Can one of you review?  The changes LGTM but I don't know if `DebugBreak()` is something you can expect to be available.

**Comment by refack** [comment]
`DebugBreak()` is WIN32 API (https://msdn.microsoft.com/library/windows/desktop/ms679297.aspxx) and it's implemented by MinGW, so it should be avalible.

**Comment by refack** [comment]
BTW: Do we have an official recipe for building for MinGW?
@carenas How do you do it?

**Comment by carenas** [comment]
I was using a crosscompiler running in macOS, but the procedure will be the same if running in linux or windows with msys2 :

  $ ./autogen.sh
  $ ./configure --host=x86_64-w64-mingw32
  $ make

if using MSYS2 MinGW {32,64}-bit, --host is not needed, @refack

**Comment by cjihrig** [comment]
Landed in 939a8f1a5b8a7b419cf4c44295e0de57a5c37500. Thanks!

**Pull request closed without merging**
