### PR TITLE
win: enable uv_thread_{get,set}name on MinGW

### PR DESCRIPTION
**Pull request by saghul**
It supports the API: https://github.com/mirror/mingw-w64/blob/93f3505a758fe70e56678f00e753af3bc4f640bb/mingw-w64-headers/include/processthreadsapi.h#L358

### CODE REVIEW

**Comment by saghul** [comment]
Potential alternative, if we want to go the NT API route: NtSetInformationThread.

**Comment by santigimeno** [comment]
The test should be enabled: https://github.com/libuv/libuv/blob/v1.x/test/test-thread-name.c#L69

**Comment by saghul** [comment]
> The test should be enabled: https://github.com/libuv/libuv/blob/v1.x/test/test-thread-name.c#L69

Oh, thanks!

**Review by santigimeno — APPROVED** [review]

**Review by cjihrig — APPROVED** [review]

**Review by vtjnash — APPROVED** [review]

**Comment by juanarbol** [comment]
I think you had to squash haha https://github.com/libuv/libuv/commit/7752218db2cd3de28a2924d2e9b0f6e062b441c7

**Comment by vtjnash** [comment]
We should potentially disable that UI option. We have it enabled so that if you carefully craft the commits to add the PR number for a series, then you can rebase+merge that. But that is very rare and can be pushed directly to v1.x when that ever comes up.

**Comment by saghul** [comment]
Opsie, my bad 😅

**Pull request merged**
