### PR TITLE
loop: Process closing handles during loop close.

### PR DESCRIPTION
**Pull request by coreyfarrell**
This resolves the UV_EBUSY error given by uv_loop_close if it is
called while closing handles (unix) or endgame handles (Windows)
are still outstanding.

This mostly effects signal handlers that are removed after uv_run
finishes.  uv_loop_close could not succeed until uv_run was called
again to process the closing handles.

### CODE REVIEW

**Comment by coreyfarrell** [comment]
This change has been tested under Linux.  I do not have access to any Windows machines to test with.

**Comment by saghul** [comment]
Sorry, but this is not the right approach. uv_loop_close should return
EBUSY if there are pending handles, so you must call uv_run again until all
callbacks have fired. This is by design. Then uv_loop_close will return 0.

**Comment by coreyfarrell** [comment]
I understand, can't have uv_loop_close running callbacks, not even the ones registered by uv_close.  Oh well at least there is a work around.  Sorry for taking your time, thanks for helping me understand.

**Comment by saghul** [comment]
No worries! Sorry I wasn't clear enough earlier :-S

**Pull request closed without merging**
