### PR TITLE
Range lock access

### PR DESCRIPTION
**Pull request by Adam-K-P**
Hi I saw issue #318 and I wanted to try to help.  I've just written this for unix and would like some feedback on this implementation.  Any thoughts on whether this is the right direction?

### CODE REVIEW

**Comment by saghul** [comment]
This implementation does not conform to the `uv_fs_*` API. You need to use a `uv_fs_t` request and take a callback, which controls if the operation is blocking or not.

As for the code that does the actual range locking, I'm not very familiar with it, but the code you provided looked simple enough. It seems to match what the manual says on Linux, but we need consistent behavior across platforms. I'm not sure what the situation is on BSDs nor Windows, though.

**Comment by bnoordhuis** [comment]
I've railed against it before but I'll repeat it here so you don't waste too much time on it: `fcntl(F_SETLK)` is broken by design and extremely difficult to use securely and robustly.  To quote the man page:

> If a process closes any file descriptor referring to a file, then all of the process's locks on that file are released, regardless of  the  file  descriptor(s) which  the  locks were obtained.  This is bad: it means that a process can lose its locks on a file such as /etc/passwd or /etc/mtab when for some reason a library function decides to open, read, and close the same file.

As well:

> The threads in a process share locks.  In other words, a multithreaded program can't use record locking to ensure that threads don't simultaneously access the same region of a file.

**Comment by saghul** [comment]
@bnoordhuis I remembered you had said something about it, but couldn't remember what, thatnks for clarifying once again.

If the problems are irreconcilable let's close this and have it as an offical "wontfix". WDYT?

**Comment by bnoordhuis** [comment]
I agree, I'll close the PR.  Sorry @Adam-K-P, but thanks for contributing.

**Comment by llafuente** [comment]
Just reading found that the man page says...

> Open file description locks solve both of these problems.

I don't see why not give it a try, if the implementation is the same in all OS... I don't mind if it's unsafe because otherwise i will use it directly, and that no cross platform.

and repeat... if the implementation is the same in all OS. Not otherwise.

**Comment by bnoordhuis** [comment]
@llafuente OFD locks are not portable - they're Linux-only - and they were introduced not two years ago in Linux 3.15.  Meanwhile we support 2.6.18, released almost 10 years ago.

**Comment by llafuente** [comment]
There is always a catch :hammer: 

Why not use it when available, and document the odd behaviour like `man` does?
I'm just curious about why drop a feature for safety reasons when there is no alternative...

**Comment by saghul** [comment]
> Why not use it when available, and document the odd behaviour like man does?

How does that help? People will still need to program around that.

> I'm just curious about why drop a feature for safety reasons when there is no alternative...

The feature doesn't quite exist in libuv, so technically we're not dropping anything. Generally speaking, if a given feature doesn't give us enough cross platform consistency we leave it out.

**Pull request closed without merging**
