### PR TITLE
win, fs: use CopyFileExW instead of CopyFile

### PR DESCRIPTION
**Pull request by RaisinTen**
Fixes: https://github.com/libuv/libuv/issues/3116

### CODE REVIEW

**Comment by cjihrig** [comment]
Have you benchmarked these changes anywhere?

**Comment by RaisinTen** [comment]
@cjihrig I'm sorry, I don't use Windows, so I couldn't test out the code but I think this works as intended as I referred to the [docs](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-copyfileexw) while making this PR.

**Comment by cjihrig** [comment]
I'd like to get @bzoz input based on https://github.com/nodejs/node/issues/36158#issuecomment-729576876.

**Comment by bzoz** [comment]
The original comment is in https://github.com/nodejs/node/issues/36158. As discussed there - the performance gains are supposed to come from `CopyFileEx` being an async function. We simulate async through the thread pool.

But... you never know, we have already seen massive performance improvments by using memory-mapped files when Windows Defender is running 🙃.  We should benchmark this. But until then and until the benchmarks show performance improvements, since there are always risks with such API changes, I'm -0.5 on this.

**Comment by RaisinTen** [comment]
Could we please run the benchmark on the Jenkins server we use for running CI tests?

**Comment by vtjnash** [comment]
I doesn't seem like this is likely to be faster, and absent anyone being able to test it, there is not likely any advantage to this currently

**Pull request closed without merging**
